// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Connection is a connection as it was named when the write was made. The id
 * alone would not survive the connection being deleted or renamed.
 */
export class Connection {
    "id": number;
    "name"?: string;
    "family"?: string;

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection($$parsedSource as Partial<Connection>);
    }
}
