// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RecordResult is what the cluster did with the send.
 */
export class RecordResult {
    /**
     * Sent is how many the cluster acknowledged.
     */
    "sent": number;

    /**
     * Partition and Offset are where the last one landed. They are the whole
     * reason to report anything: an operator who just sent a record can go and
     * read it back by those coordinates.
     */
    "partition": number;
    "offset": number;

    /**
     * Failed is how many the cluster refused, and Reason is its words for the
     * last refusal.
     */
    "failed": number;
    "reason": string;

    /** Creates a new RecordResult instance. */
    constructor($$source: Partial<RecordResult> = {}) {
        if (!("sent" in $$source)) {
            this["sent"] = 0;
        }
        if (!("partition" in $$source)) {
            this["partition"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordResult($$parsedSource as Partial<RecordResult>);
    }
}
