// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccountUsage is what the account is using against what it may use.
 * 
 * Its own type rather than part of the census, because the census is a count
 * of objects and this is a pair of meters. The limits matter as much as the
 * usage: -1 means no cap, and a meter drawn against -1 can never move.
 */
export class AccountUsage {
    "memoryUsed": number;
    "memoryLimit": number;
    "storeUsed": number;
    "storeLimit": number;
    "streams": number;
    "streamLimit": number;
    "consumers": number;
    "consumerLimit": number;

    /**
     * Domain is set where the cluster has been split by a leaf node. Empty is
     * the ordinary case.
     */
    "domain": string;

    /**
     * Tier names which limit set applies, on an account with several. Empty
     * where the account has one, which is almost always.
     */
    "tier": string;

    /** Creates a new AccountUsage instance. */
    constructor($$source: Partial<AccountUsage> = {}) {
        if (!("memoryUsed" in $$source)) {
            this["memoryUsed"] = 0;
        }
        if (!("memoryLimit" in $$source)) {
            this["memoryLimit"] = 0;
        }
        if (!("storeUsed" in $$source)) {
            this["storeUsed"] = 0;
        }
        if (!("storeLimit" in $$source)) {
            this["storeLimit"] = 0;
        }
        if (!("streams" in $$source)) {
            this["streams"] = 0;
        }
        if (!("streamLimit" in $$source)) {
            this["streamLimit"] = 0;
        }
        if (!("consumers" in $$source)) {
            this["consumers"] = 0;
        }
        if (!("consumerLimit" in $$source)) {
            this["consumerLimit"] = 0;
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("tier" in $$source)) {
            this["tier"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountUsage($$parsedSource as Partial<AccountUsage>);
    }
}

/**
 * PublishResult is what the server said, which depends on how much was asked.
 */
export class PublishResult {
    /**
     * Sent is how many of Count went out.
     */
    "sent": number;

    /**
     * Acknowledged is whether a stream confirmed storing them.
     * 
     * False on a core publish is not a failure: core NATS acknowledges
     * nothing, by design. The board says which kind of send this was rather
     * than showing an unticked box.
     */
    "acknowledged": boolean;

    /**
     * Stream and Sequence name where the last message landed, when a stream
     * stored it. Empty on a core publish, which lands nowhere in particular.
     */
    "stream": string;
    "sequence": number;

    /**
     * Duplicate is the server reporting that it recognised the deduplication
     * id and did not store the message again. It is a success rather than an
     * error, and the difference is worth showing: the message is not there
     * twice, and it is also not there once more.
     */
    "duplicate": boolean;

    /**
     * Reply is what answered a request, when one was asked for.
     */
    "reply": string;

    /**
     * Answered separates "nobody replied" from "somebody replied with
     * nothing", which are different diagnoses of the same blank box.
     */
    "answered": boolean;

    /** Creates a new PublishResult instance. */
    constructor($$source: Partial<PublishResult> = {}) {
        if (!("sent" in $$source)) {
            this["sent"] = 0;
        }
        if (!("acknowledged" in $$source)) {
            this["acknowledged"] = false;
        }
        if (!("stream" in $$source)) {
            this["stream"] = "";
        }
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }
        if (!("duplicate" in $$source)) {
            this["duplicate"] = false;
        }
        if (!("reply" in $$source)) {
            this["reply"] = "";
        }
        if (!("answered" in $$source)) {
            this["answered"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublishResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PublishResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublishResult($$parsedSource as Partial<PublishResult>);
    }
}
