// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClientSubscription is one topic filter a client holds.
 * 
 * It is this package's own type rather than model.Subscription, which is a
 * consumer group: it has a lag, an offset and members. An MQTT subscription
 * has none of those - it is one client's filter, and it stops existing when
 * the client goes. Reporting it as a group would put a lag column on a page
 * that can never fill one in.
 */
export class ClientSubscription {
    "clientId": string;
    "node": string;
    "topic": string;
    "qos": number;

    /**
     * The three MQTT 5.0 subscription options. They decide whether a client
     * gets its own publishes back, whether the retain flag survives, and
     * whether retained messages are replayed - all of which change what a
     * consumer sees and none of which 3.1.1 can express.
     */
    "noLocal": boolean;
    "retainAsPublished": boolean;
    "retainHandling": number;
    "durable": boolean;

    /** Creates a new ClientSubscription instance. */
    constructor($$source: Partial<ClientSubscription> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("node" in $$source)) {
            this["node"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("qos" in $$source)) {
            this["qos"] = 0;
        }
        if (!("noLocal" in $$source)) {
            this["noLocal"] = false;
        }
        if (!("retainAsPublished" in $$source)) {
            this["retainAsPublished"] = false;
        }
        if (!("retainHandling" in $$source)) {
            this["retainHandling"] = 0;
        }
        if (!("durable" in $$source)) {
            this["durable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClientSubscription instance from a string or object.
     */
    static createFrom($$source: any = {}): ClientSubscription {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClientSubscription($$parsedSource as Partial<ClientSubscription>);
    }
}

/**
 * PublishResult is what the broker said, which depends on how much was asked.
 */
export class PublishResult {
    /**
     * Sent is how many of Count went out.
     */
    "sent": number;

    /**
     * Acknowledged is false at QoS 0, where the protocol has no
     * acknowledgement at all: the message reached the socket and nothing
     * further is knowable. Reporting that honestly is the difference between
     * "the broker has it" and "we wrote it somewhere".
     */
    "acknowledged": boolean;

    /**
     * NoMatchingSubscribers is the broker saying it took the message and had
     * nobody to give it to (5.0 reason code 16). It is not a failure - MQTT
     * has no mandatory flag and a retained publish is often meant for nobody
     * yet - but it is the difference between a send that did something and one
     * that did not.
     */
    "noMatchingSubscribers": boolean;

    /**
     * ReasonCode and Reason are the broker's own answer. 3.1.1 has neither, so
     * they stay zero and empty there rather than being invented.
     */
    "reasonCode": number;
    "reason": string;

    /** Creates a new PublishResult instance. */
    constructor($$source: Partial<PublishResult> = {}) {
        if (!("sent" in $$source)) {
            this["sent"] = 0;
        }
        if (!("acknowledged" in $$source)) {
            this["acknowledged"] = false;
        }
        if (!("noMatchingSubscribers" in $$source)) {
            this["noMatchingSubscribers"] = false;
        }
        if (!("reasonCode" in $$source)) {
            this["reasonCode"] = 0;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublishResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PublishResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublishResult($$parsedSource as Partial<PublishResult>);
    }
}
