// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Usage is what a turn cost, in tokens, where the service says.
 */
export class Usage {
    "input": number;
    "output": number;
    "cacheRead"?: number;
    "cacheWrite"?: number;

    /** Creates a new Usage instance. */
    constructor($$source: Partial<Usage> = {}) {
        if (!("input" in $$source)) {
            this["input"] = 0;
        }
        if (!("output" in $$source)) {
            this["output"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Usage instance from a string or object.
     */
    static createFrom($$source: any = {}): Usage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Usage($$parsedSource as Partial<Usage>);
    }
}
