// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AclVersionInfo holds ACL config version information.
 */
export class AclVersionInfo {
    "brokerAddr": string;
    "brokerName": string;
    "clusterName": string;
    "version": string;

    /** Creates a new AclVersionInfo instance. */
    constructor($$source: Partial<AclVersionInfo> = {}) {
        if (!("brokerAddr" in $$source)) {
            this["brokerAddr"] = "";
        }
        if (!("brokerName" in $$source)) {
            this["brokerName"] = "";
        }
        if (!("clusterName" in $$source)) {
            this["clusterName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AclVersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AclVersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AclVersionInfo($$parsedSource as Partial<AclVersionInfo>);
    }
}

/**
 * AuthMechanism is how a connection authenticates.
 */
export enum AuthMechanism {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthNone = "none",

    /**
     * RocketMQ AccessKey / SecretKey
     */
    AuthACL = "acl",
    AuthPlain = "plain",
    AuthSASLPlain = "sasl-plain",
    AuthSASLScram = "sasl-scram",
    AuthToken = "token",
    AuthMutualTLS = "mtls",
};

/**
 * Capabilities is what one live connection can actually do.
 * 
 * Three states reach the UI, and they must stay distinguishable: a capability
 * in Supported renders normally; one in Degraded renders disabled with the
 * reason; one in neither is hidden outright. Silent absence and explained
 * absence look identical to a user otherwise, which makes a deliberately
 * limited endpoint read as a bug.
 */
export class Capabilities {
    "supported": Capability[];

    /**
     * Degraded explains a capability the family has but this endpoint lacks.
     * A RocketMQ Proxy endpoint is a data plane only, so it reports no topic
     * listing, no cluster topology and no ACL.
     */
    "degraded": { [_ in Capability]?: string };

    /**
     * Caveats annotates a capability that works but has a consequence worth
     * warning about. Browsing a RabbitMQ queue goes through basic.get, which
     * alters queue state even when the message is requeued.
     */
    "caveats": { [_ in Capability]?: string };

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = [];
        }
        if (!("degraded" in $$source)) {
            this["degraded"] = {};
        }
        if (!("caveats" in $$source)) {
            this["caveats"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supported" in $$parsedSource) {
            $$parsedSource["supported"] = $$createField0_0($$parsedSource["supported"]);
        }
        if ("degraded" in $$parsedSource) {
            $$parsedSource["degraded"] = $$createField1_0($$parsedSource["degraded"]);
        }
        if ("caveats" in $$parsedSource) {
            $$parsedSource["caveats"] = $$createField2_0($$parsedSource["caveats"]);
        }
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

/**
 * Capability names one operation the UI gates on.
 * 
 * The values cross the bridge and are matched as literals in the renderer, so
 * renaming one means changing frontend/src/mq/capabilities.ts in the same
 * commit.
 */
export enum Capability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CapDestinationList = "destination.list",
    CapDestinationCreate = "destination.create",
    CapDestinationUpdate = "destination.update",
    CapDestinationDelete = "destination.delete",
    CapPartitions = "destination.partitions",
    CapSubscriptionList = "subscription.list",
    CapSubscriptionCreate = "subscription.create",
    CapSubscriptionDelete = "subscription.delete",
    CapSubscriptionLag = "subscription.lag",
    CapOffsetReset = "subscription.resetOffset",
    CapMessageQuery = "message.query",
    CapMessageByID = "message.byId",
    CapMessageTrack = "message.track",
    CapMessageResend = "message.resend",
    CapMessageLiveTail = "message.liveTail",
    CapDLQ = "message.dlq",
    CapPublish = "message.publish",

    /**
     * CapDelayedDelivery is scheduling a message for later. RocketMQ has delay
     * levels, Kafka has nothing, RabbitMQ needs a plugin.
     */
    CapDelayedDelivery = "message.delayedDelivery",
    CapClusterTopology = "cluster.topology",
    CapClusterMetrics = "cluster.metrics",
    CapAccessControl = "access.control",
    CapRouting = "routing.exchanges",
};

/**
 * ClusterOverview is the aggregate the Cluster page header shows.
 */
export class ClusterOverview {
    "name": string;
    "totalNodes": number;
    "onlineNodes": number;

    /**
     * UnknownMetric when not enumerable
     */
    "destinations": number;
    "subscriptions": number;

    /**
     * percent; UnknownMetric when not reported
     */
    "avgDiskUsage": number;

    /** Creates a new ClusterOverview instance. */
    constructor($$source: Partial<ClusterOverview> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("totalNodes" in $$source)) {
            this["totalNodes"] = 0;
        }
        if (!("onlineNodes" in $$source)) {
            this["onlineNodes"] = 0;
        }
        if (!("destinations" in $$source)) {
            this["destinations"] = 0;
        }
        if (!("subscriptions" in $$source)) {
            this["subscriptions"] = 0;
        }
        if (!("avgDiskUsage" in $$source)) {
            this["avgDiskUsage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterOverview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterOverview($$parsedSource as Partial<ClusterOverview>);
    }
}

/**
 * ClusterSummary holds cluster status summary for the frontend.
 */
export class ClusterSummary {
    /**
     * Cluster count
     */
    "totalClusters": number;

    /**
     * Total Broker count
     */
    "totalBrokers": number;

    /**
     * Online Broker count
     */
    "onlineBrokers": number;

    /**
     * Warning Broker count
     */
    "warningBrokers": number;

    /**
     * Offline Broker count
     */
    "offlineBrokers": number;

    /**
     * Average disk usage percent
     */
    "avgDiskUsage": number;

    /** Creates a new ClusterSummary instance. */
    constructor($$source: Partial<ClusterSummary> = {}) {
        if (!("totalClusters" in $$source)) {
            this["totalClusters"] = 0;
        }
        if (!("totalBrokers" in $$source)) {
            this["totalBrokers"] = 0;
        }
        if (!("onlineBrokers" in $$source)) {
            this["onlineBrokers"] = 0;
        }
        if (!("warningBrokers" in $$source)) {
            this["warningBrokers"] = 0;
        }
        if (!("offlineBrokers" in $$source)) {
            this["offlineBrokers"] = 0;
        }
        if (!("avgDiskUsage" in $$source)) {
            this["avgDiskUsage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterSummary($$parsedSource as Partial<ClusterSummary>);
    }
}

/**
 * ConnectionStatus is the connection status.
 */
export enum ConnectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusOnline = "online",
    StatusOffline = "offline",
};

/**
 * Destination is a topic, queue or stream as the canonical pages see it.
 * 
 * Attributes carries whatever the family has and the canonical model does not:
 * RocketMQ permissions and queue counts, RabbitMQ durability and queue type,
 * Kafka replication factor. Its keys are a contract between one driver's Go
 * side and that driver's frontend module, not part of the shared vocabulary.
 */
export class Destination {
    /**
     * list key for the renderer, not broker data
     */
    "id": number;
    "ref": DestinationRef;

    /**
     * UnknownMetric where the family has none
     */
    "partitions": number;

    /**
     * consumer groups, subscriptions or consumers
     */
    "subscribers": number;

    /**
     * messages held; UnknownMetric when not reported
     */
    "depth": number;

    /**
     * messages per second in
     */
    "rateIn": number;

    /**
     * messages per second out
     */
    "rateOut": number;
    "lastUpdated": string;
    "attributes": { [_ in string]?: string };

    /** Creates a new Destination instance. */
    constructor($$source: Partial<Destination> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ref" in $$source)) {
            this["ref"] = (new DestinationRef());
        }
        if (!("partitions" in $$source)) {
            this["partitions"] = 0;
        }
        if (!("subscribers" in $$source)) {
            this["subscribers"] = 0;
        }
        if (!("depth" in $$source)) {
            this["depth"] = 0;
        }
        if (!("rateIn" in $$source)) {
            this["rateIn"] = 0;
        }
        if (!("rateOut" in $$source)) {
            this["rateOut"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = "";
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Destination instance from a string or object.
     */
    static createFrom($$source: any = {}): Destination {
        const $$createField1_0 = $$createType2;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField1_0($$parsedSource["ref"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField8_0($$parsedSource["attributes"]);
        }
        return new Destination($$parsedSource as Partial<Destination>);
    }
}

/**
 * DestinationRef identifies a destination across families.
 * 
 * Flat families leave Namespace empty; Pulsar fills tenant/namespace and
 * RabbitMQ fills the vhost. It is a struct rather than a string because
 * joining and re-splitting those parts loses information for any name that
 * contains the separator.
 */
export class DestinationRef {
    "namespace": string;
    "name": string;

    /** Creates a new DestinationRef instance. */
    constructor($$source: Partial<DestinationRef> = {}) {
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DestinationRef instance from a string or object.
     */
    static createFrom($$source: any = {}): DestinationRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DestinationRef($$parsedSource as Partial<DestinationRef>);
    }
}

/**
 * DriverDescriptor is what a family can do before any connection is open.
 * 
 * Display strings are deliberately absent: the renderer resolves them from
 * the i18n bundle under mq.<kind>.*, so translations stay where translations
 * live.
 */
export class DriverDescriptor {
    "kind": MQKind;
    "defaultPort": string;
    "form": FormField[];

    /**
     * MaxCapabilities is the best case for the family. A live connection can
     * only narrow it, never widen it, and the driver conformance test asserts
     * every entry is backed by an implemented interface.
     */
    "maxCapabilities": Capability[];

    /** Creates a new DriverDescriptor instance. */
    constructor($$source: Partial<DriverDescriptor> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = MQKind.$zero;
        }
        if (!("defaultPort" in $$source)) {
            this["defaultPort"] = "";
        }
        if (!("form" in $$source)) {
            this["form"] = [];
        }
        if (!("maxCapabilities" in $$source)) {
            this["maxCapabilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DriverDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): DriverDescriptor {
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("form" in $$parsedSource) {
            $$parsedSource["form"] = $$createField2_0($$parsedSource["form"]);
        }
        if ("maxCapabilities" in $$parsedSource) {
            $$parsedSource["maxCapabilities"] = $$createField3_0($$parsedSource["maxCapabilities"]);
        }
        return new DriverDescriptor($$parsedSource as Partial<DriverDescriptor>);
    }
}

/**
 * FieldCond hides a field unless another field holds one of Equals.
 */
export class FieldCond {
    "field": string;
    "equals": string[];

    /** Creates a new FieldCond instance. */
    constructor($$source: Partial<FieldCond> = {}) {
        if (!("field" in $$source)) {
            this["field"] = "";
        }
        if (!("equals" in $$source)) {
            this["equals"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldCond instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldCond {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("equals" in $$parsedSource) {
            $$parsedSource["equals"] = $$createField1_0($$parsedSource["equals"]);
        }
        return new FieldCond($$parsedSource as Partial<FieldCond>);
    }
}

/**
 * FieldTarget says which part of a ConnectionProfile a field writes into.
 * Secrets are encrypted at rest and never serialised back to the renderer.
 */
export enum FieldTarget {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TargetEndpoints = "endpoints",
    TargetOption = "option",
    TargetSecret = "secret",
    TargetAuth = "auth",
};

/**
 * FieldType is how the renderer draws one connection-form field.
 */
export enum FieldType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FieldText = "text",
    FieldPassword = "password",
    FieldNumber = "number",
    FieldSelect = "select",
    FieldSwitch = "switch",
    FieldEndpointList = "endpoint-list",
};

/**
 * FormField is one row of a driver's connection form.
 */
export class FormField {
    "key": string;
    "target": FieldTarget;
    "type": FieldType;

    /**
     * i18n key, never a literal
     */
    "labelKey": string;
    "placeholder": string;
    "default": string;
    "required": boolean;
    "visibleWhen": FieldCond | null;
    "options": FormOption[];

    /**
     * Validate names a validator the renderer already implements, such as
     * "host-port" or "url". Shipping a regex across the bridge would move
     * validation logic out of review and into data.
     */
    "validate": string;

    /** Creates a new FormField instance. */
    constructor($$source: Partial<FormField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = FieldTarget.$zero;
        }
        if (!("type" in $$source)) {
            this["type"] = FieldType.$zero;
        }
        if (!("labelKey" in $$source)) {
            this["labelKey"] = "";
        }
        if (!("placeholder" in $$source)) {
            this["placeholder"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("required" in $$source)) {
            this["required"] = false;
        }
        if (!("visibleWhen" in $$source)) {
            this["visibleWhen"] = null;
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }
        if (!("validate" in $$source)) {
            this["validate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormField instance from a string or object.
     */
    static createFrom($$source: any = {}): FormField {
        const $$createField7_0 = $$createType8;
        const $$createField8_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("visibleWhen" in $$parsedSource) {
            $$parsedSource["visibleWhen"] = $$createField7_0($$parsedSource["visibleWhen"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField8_0($$parsedSource["options"]);
        }
        return new FormField($$parsedSource as Partial<FormField>);
    }
}

/**
 * FormOption is one choice in a select field.
 */
export class FormOption {
    "value": string;
    "labelKey": string;

    /** Creates a new FormOption instance. */
    constructor($$source: Partial<FormOption> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("labelKey" in $$source)) {
            this["labelKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormOption instance from a string or object.
     */
    static createFrom($$source: any = {}): FormOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FormOption($$parsedSource as Partial<FormOption>);
    }
}

/**
 * MQKind identifies a broker family.
 * 
 * The values are the key for the driver registry, the per-kind settings
 * defaults and the `kind` field in connections.json, so they are part of the
 * on-disk format and must not be renamed.
 */
export enum MQKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindRocketMQ = "rocketmq",
    KindKafka = "kafka",
    KindRabbitMQ = "rabbitmq",
    KindPulsar = "pulsar",
    KindRedisStream = "redis-stream",
    KindMQTT = "mqtt",
};

/**
 * MessageItem holds message information.
 */
export class MessageItem {
    /**
     * Message sequence number
     */
    "id": number;

    /**
     * Cluster name
     */
    "cluster": string;

    /**
     * Topic name
     */
    "topic": string;

    /**
     * Message ID
     */
    "messageId": string;

    /**
     * Message tags
     */
    "tags": string;

    /**
     * Message keys
     */
    "keys": string;

    /**
     * Queue ID
     */
    "queueId": number;

    /**
     * Queue offset
     */
    "queueOffset": number;

    /**
     * Store host
     */
    "storeHost": string;

    /**
     * Born host
     */
    "bornHost": string;

    /**
     * Store time
     */
    "storeTime": string;

    /**
     * Store timestamp
     */
    "storeTimestamp": number;

    /**
     * Message status
     */
    "status": MessageStatus;

    /**
     * Retry times
     */
    "retryTimes": number;

    /**
     * Message body
     */
    "body": string;

    /**
     * Message properties
     */
    "properties": { [_ in string]?: string };

    /** Creates a new MessageItem instance. */
    constructor($$source: Partial<MessageItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = "";
        }
        if (!("keys" in $$source)) {
            this["keys"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = 0;
        }
        if (!("queueOffset" in $$source)) {
            this["queueOffset"] = 0;
        }
        if (!("storeHost" in $$source)) {
            this["storeHost"] = "";
        }
        if (!("bornHost" in $$source)) {
            this["bornHost"] = "";
        }
        if (!("storeTime" in $$source)) {
            this["storeTime"] = "";
        }
        if (!("storeTimestamp" in $$source)) {
            this["storeTimestamp"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = MessageStatus.$zero;
        }
        if (!("retryTimes" in $$source)) {
            this["retryTimes"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageItem {
        const $$createField15_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField15_0($$parsedSource["properties"]);
        }
        return new MessageItem($$parsedSource as Partial<MessageItem>);
    }
}

/**
 * MessageStatus is the message status.
 */
export enum MessageStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MsgNormal = "normal",
    MsgRetry = "retry",
    MsgDLQ = "dlq",
};

/**
 * MessageTrackItem holds message track information.
 */
export class MessageTrackItem {
    /**
     * Consumer group
     */
    "consumerGroup": string;

    /**
     * Track type: CONSUMED / NOT_CONSUME_YET / CONSUMED_BUT_FILTERED / UNKNOWN
     */
    "trackType": string;

    /**
     * Consume status description
     */
    "consumeStatus": string;

    /**
     * Exception description
     */
    "exceptionDesc": string;

    /** Creates a new MessageTrackItem instance. */
    constructor($$source: Partial<MessageTrackItem> = {}) {
        if (!("consumerGroup" in $$source)) {
            this["consumerGroup"] = "";
        }
        if (!("trackType" in $$source)) {
            this["trackType"] = "";
        }
        if (!("consumeStatus" in $$source)) {
            this["consumeStatus"] = "";
        }
        if (!("exceptionDesc" in $$source)) {
            this["exceptionDesc"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageTrackItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageTrackItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageTrackItem($$parsedSource as Partial<MessageTrackItem>);
    }
}

/**
 * Node is one broker, RabbitMQ node or Kafka broker as the canonical Cluster
 * page sees it.
 * 
 * It is deliberately thinner than BrokerNode: the TPS history arrays there are
 * filled by the cluster service from local samples, not by any broker, so they
 * stay out of what a driver has to produce.
 */
export class Node {
    /**
     * list key for the renderer, not broker data
     */
    "id": number;
    "name": string;
    "address": string;

    /**
     * grouping label; empty where the family has none
     */
    "cluster": string;
    "version": string;
    "status": NodeStatus;

    /**
     * messages per second in
     */
    "rateIn": number;

    /**
     * messages per second out
     */
    "rateOut": number;

    /**
     * percent; UnknownMetric when not reported
     */
    "diskUsage": number;
    "lastSeen": string;

    /**
     * TPS history is sampled locally by the collector, not reported by any
     * broker, which is why a driver never fills these.
     * Unix seconds
     */
    "tpsHistoryTimestamps": number[];
    "tpsInHistory": number[];
    "tpsOutHistory": number[];

    /**
     * Attributes carries family-specific detail the canonical page renders
     * through the driver's own column set: RocketMQ master/slave role and
     * CommitLog usage, Kafka controller and ISR, RabbitMQ disc/ram node type.
     */
    "attributes": { [_ in string]?: string };

    /** Creates a new Node instance. */
    constructor($$source: Partial<Node> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = NodeStatus.$zero;
        }
        if (!("rateIn" in $$source)) {
            this["rateIn"] = 0;
        }
        if (!("rateOut" in $$source)) {
            this["rateOut"] = 0;
        }
        if (!("diskUsage" in $$source)) {
            this["diskUsage"] = 0;
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = "";
        }
        if (!("tpsHistoryTimestamps" in $$source)) {
            this["tpsHistoryTimestamps"] = [];
        }
        if (!("tpsInHistory" in $$source)) {
            this["tpsInHistory"] = [];
        }
        if (!("tpsOutHistory" in $$source)) {
            this["tpsOutHistory"] = [];
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     */
    static createFrom($$source: any = {}): Node {
        const $$createField10_0 = $$createType11;
        const $$createField11_0 = $$createType12;
        const $$createField12_0 = $$createType12;
        const $$createField13_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tpsHistoryTimestamps" in $$parsedSource) {
            $$parsedSource["tpsHistoryTimestamps"] = $$createField10_0($$parsedSource["tpsHistoryTimestamps"]);
        }
        if ("tpsInHistory" in $$parsedSource) {
            $$parsedSource["tpsInHistory"] = $$createField11_0($$parsedSource["tpsInHistory"]);
        }
        if ("tpsOutHistory" in $$parsedSource) {
            $$parsedSource["tpsOutHistory"] = $$createField12_0($$parsedSource["tpsOutHistory"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField13_0($$parsedSource["attributes"]);
        }
        return new Node($$parsedSource as Partial<Node>);
    }
}

/**
 * NodeStatus is the node status.
 */
export enum NodeStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodeOnline = "online",
    NodeWarning = "warning",
    NodeOffline = "offline",
};

/**
 * ResetOffsetRequest is a request to reset offsets.
 */
export class ResetOffsetRequest {
    /**
     * Consumer group name
     */
    "group": string;

    /**
     * Topic name
     */
    "topic": string;

    /**
     * Timestamp (milliseconds)
     */
    "timestamp": number;

    /**
     * Whether to force reset
     */
    "force": boolean;

    /** Creates a new ResetOffsetRequest instance. */
    constructor($$source: Partial<ResetOffsetRequest> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("force" in $$source)) {
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetOffsetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetOffsetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetOffsetRequest($$parsedSource as Partial<ResetOffsetRequest>);
    }
}

/**
 * Subscription is a consumer group, a Pulsar subscription or a RabbitMQ queue
 * consumer, as the canonical pages see it.
 * 
 * Backlog is deliberately not called lag: RocketMQ and Kafka compute it from
 * offsets, RabbitMQ reads ready plus unacknowledged, and Redis Stream reads
 * XPENDING. The number means "messages still owed to this subscriber" in all
 * three, but only the first two have an offset behind it — which is why
 * resetting position is a separate capability.
 */
export class Subscription {
    /**
     * list key for the renderer, not broker data
     */
    "id": number;
    "ref": SubscriptionRef;
    "status": SubscriptionStatus;

    /**
     * connected consumers
     */
    "members": number;

    /**
     * how many it reads from
     */
    "destinations": number;

    /**
     * UnknownMetric when not reported
     */
    "backlog": number;

    /**
     * messages per second consumed
     */
    "rateOut": number;
    "lastUpdated": string;
    "attributes": { [_ in string]?: string };

    /** Creates a new Subscription instance. */
    constructor($$source: Partial<Subscription> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ref" in $$source)) {
            this["ref"] = (new SubscriptionRef());
        }
        if (!("status" in $$source)) {
            this["status"] = SubscriptionStatus.$zero;
        }
        if (!("members" in $$source)) {
            this["members"] = 0;
        }
        if (!("destinations" in $$source)) {
            this["destinations"] = 0;
        }
        if (!("backlog" in $$source)) {
            this["backlog"] = 0;
        }
        if (!("rateOut" in $$source)) {
            this["rateOut"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = "";
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Subscription instance from a string or object.
     */
    static createFrom($$source: any = {}): Subscription {
        const $$createField1_0 = $$createType13;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField1_0($$parsedSource["ref"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField8_0($$parsedSource["attributes"]);
        }
        return new Subscription($$parsedSource as Partial<Subscription>);
    }
}

/**
 * SubscriptionRef identifies a consumer group, subscription or queue consumer.
 */
export class SubscriptionRef {
    "namespace": string;
    "name": string;

    /** Creates a new SubscriptionRef instance. */
    constructor($$source: Partial<SubscriptionRef> = {}) {
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubscriptionRef instance from a string or object.
     */
    static createFrom($$source: any = {}): SubscriptionRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubscriptionRef($$parsedSource as Partial<SubscriptionRef>);
    }
}

/**
 * SubscriptionStatus is the health of a subscription.
 */
export enum SubscriptionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SubscriptionOnline = "online",
    SubscriptionWarning = "warning",
    SubscriptionOffline = "offline",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = DestinationRef.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = FormField.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = FieldCond.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = FormOption.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = $Create.Array($Create.Any);
const $$createType13 = SubscriptionRef.createFrom;
