// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccessPolicy grants or denies actions on one resource.
 */
export class AccessPolicy {
    /**
     * a topic, a group, or the cluster
     */
    "resource": string;

    /**
     * PUB, SUB, and the family's own verbs
     */
    "actions": string[];

    /**
     * Allow, Deny
     */
    "effect": string;

    /**
     * SourceIPs narrows the rule to callers from these addresses. Empty means
     * any source.
     */
    "sourceIps": string[];

    /**
     * Decision is what the broker actually decided for this policy, which is
     * not always its effect - a later rule can override an earlier one.
     */
    "decision": string;

    /** Creates a new AccessPolicy instance. */
    constructor($$source: Partial<AccessPolicy> = {}) {
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("actions" in $$source)) {
            this["actions"] = [];
        }
        if (!("effect" in $$source)) {
            this["effect"] = "";
        }
        if (!("sourceIps" in $$source)) {
            this["sourceIps"] = [];
        }
        if (!("decision" in $$source)) {
            this["decision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessPolicy {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField1_0($$parsedSource["actions"]);
        }
        if ("sourceIps" in $$parsedSource) {
            $$parsedSource["sourceIps"] = $$createField3_0($$parsedSource["sourceIps"]);
        }
        return new AccessPolicy($$parsedSource as Partial<AccessPolicy>);
    }
}

/**
 * AccessPrincipal is one identity the broker authenticates.
 * 
 * RocketMQ 5.3 calls it a user, Kafka a principal. Type and status stay the
 * family's own words: what values they take differs per family, and
 * normalising them would lose exactly what an operator has to type back.
 */
export class AccessPrincipal {
    "name": string;
    "type": string;
    "status": string;

    /** Creates a new AccessPrincipal instance. */
    constructor($$source: Partial<AccessPrincipal> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessPrincipal instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessPrincipal {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessPrincipal($$parsedSource as Partial<AccessPrincipal>);
    }
}

/**
 * AccessRule is everything one subject is permitted to do.
 * 
 * Identity-based rather than key-based, which is what separates it from
 * AccessConfig: a rule names a subject the broker already knows, where an
 * AccessConfig carries the credential and the permissions together.
 */
export class AccessRule {
    "subject": string;
    "policies": AccessPolicy[];
    "description": string;

    /** Creates a new AccessRule instance. */
    constructor($$source: Partial<AccessRule> = {}) {
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("policies" in $$source)) {
            this["policies"] = [];
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessRule instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessRule {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("policies" in $$parsedSource) {
            $$parsedSource["policies"] = $$createField1_0($$parsedSource["policies"]);
        }
        return new AccessRule($$parsedSource as Partial<AccessRule>);
    }
}

/**
 * AclVersionInfo holds ACL config version information.
 */
export class AclVersionInfo {
    "brokerAddr": string;
    "brokerName": string;
    "clusterName": string;
    "version": string;

    /** Creates a new AclVersionInfo instance. */
    constructor($$source: Partial<AclVersionInfo> = {}) {
        if (!("brokerAddr" in $$source)) {
            this["brokerAddr"] = "";
        }
        if (!("brokerName" in $$source)) {
            this["brokerName"] = "";
        }
        if (!("clusterName" in $$source)) {
            this["clusterName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AclVersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AclVersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AclVersionInfo($$parsedSource as Partial<AclVersionInfo>);
    }
}

/**
 * AuthMechanism is how a connection authenticates.
 */
export enum AuthMechanism {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthNone = "none",

    /**
     * RocketMQ AccessKey / SecretKey
     */
    AuthACL = "acl",
    AuthPlain = "plain",
    AuthSASLPlain = "sasl-plain",
    AuthSASLScram = "sasl-scram",
    AuthToken = "token",
    AuthMutualTLS = "mtls",
};

/**
 * Binding is a route from an exchange to a queue or another exchange.
 * 
 * Only RabbitMQ has first-class bindings, which is why the canonical page set
 * has no counterpart for them and the driver contributes a page of its own.
 */
export class Binding {
    /**
     * list key for the renderer
     */
    "id": number;
    "namespace": string;
    "source": string;
    "destination": string;

    /**
     * DestinationKind separates a queue target from an exchange target; the
     * same source and name can bind to both.
     */
    "destinationKind": string;
    "routingKey": string;
    "arguments": { [_ in string]?: string };

    /** Creates a new Binding instance. */
    constructor($$source: Partial<Binding> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("destinationKind" in $$source)) {
            this["destinationKind"] = "";
        }
        if (!("routingKey" in $$source)) {
            this["routingKey"] = "";
        }
        if (!("arguments" in $$source)) {
            this["arguments"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Binding instance from a string or object.
     */
    static createFrom($$source: any = {}): Binding {
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("arguments" in $$parsedSource) {
            $$parsedSource["arguments"] = $$createField6_0($$parsedSource["arguments"]);
        }
        return new Binding($$parsedSource as Partial<Binding>);
    }
}

/**
 * Capabilities is what one live connection can actually do.
 * 
 * Three states reach the UI, and they must stay distinguishable: a capability
 * in Supported renders normally; one in Degraded renders disabled with the
 * reason; one in neither is hidden outright. Silent absence and explained
 * absence look identical to a user otherwise, which makes a deliberately
 * limited endpoint read as a bug.
 */
export class Capabilities {
    "supported": Capability[];

    /**
     * Degraded explains a capability the family has but this endpoint lacks.
     * A RocketMQ Proxy endpoint is a data plane only, so it reports no topic
     * listing, no cluster topology and no ACL.
     */
    "degraded": { [_ in Capability]?: string };

    /**
     * Caveats annotates a capability that works but has a consequence worth
     * warning about. Browsing a RabbitMQ queue goes through basic.get, which
     * alters queue state even when the message is requeued.
     */
    "caveats": { [_ in Capability]?: string };

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = [];
        }
        if (!("degraded" in $$source)) {
            this["degraded"] = {};
        }
        if (!("caveats" in $$source)) {
            this["caveats"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supported" in $$parsedSource) {
            $$parsedSource["supported"] = $$createField0_0($$parsedSource["supported"]);
        }
        if ("degraded" in $$parsedSource) {
            $$parsedSource["degraded"] = $$createField1_0($$parsedSource["degraded"]);
        }
        if ("caveats" in $$parsedSource) {
            $$parsedSource["caveats"] = $$createField2_0($$parsedSource["caveats"]);
        }
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

/**
 * Capability names one operation the UI gates on.
 * 
 * The values cross the bridge and are matched as literals in the renderer, so
 * renaming one means changing frontend/src/mq/capabilities.ts in the same
 * commit.
 */
export enum Capability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CapDestinationList = "destination.list",
    CapDestinationCreate = "destination.create",
    CapDestinationUpdate = "destination.update",
    CapDestinationDelete = "destination.delete",
    CapPartitions = "destination.partitions",
    CapSubscriptionList = "subscription.list",
    CapSubscriptionCreate = "subscription.create",
    CapSubscriptionDelete = "subscription.delete",
    CapSubscriptionLag = "subscription.lag",
    CapOffsetReset = "subscription.resetOffset",

    /**
     * CapOffsetClone is copying one subscription's read position onto another.
     * It is not CapOffsetReset: reset moves a group in time, this hands a
     * second group the first one's exact per-queue positions.
     */
    CapOffsetClone = "subscription.cloneOffset",

    /**
     * CapSubscriptionRuntime is asking a connected consumer what it is doing:
     * which queues it holds and how fast it is getting through them. Only a
     * live client can answer, so a family without client introspection - or a
     * group with nothing connected - simply has no answer.
     */
    CapSubscriptionRuntime = "subscription.runtime",
    CapMessageQuery = "message.query",
    CapMessageByID = "message.byId",
    CapMessageTrack = "message.track",
    CapMessageResend = "message.resend",

    /**
     * CapMessageReplay is handing one message back to one connected consumer
     * and reporting what its handler returned. Distinct from CapMessageResend,
     * which puts a copy back on the retry path for whoever picks it up.
     */
    CapMessageReplay = "message.replay",
    CapMessageLiveTail = "message.liveTail",
    CapDLQ = "message.dlq",
    CapPublish = "message.publish",

    /**
     * CapProducerInspect is asking who is currently publishing. It needs a
     * producer group to ask about: the broker tracks connections per group and
     * offers no way to enumerate the groups themselves.
     */
    CapProducerInspect = "message.producerInspect",

    /**
     * CapDelayedDelivery is scheduling a message for later. RocketMQ has delay
     * levels, Kafka has nothing, RabbitMQ needs a plugin.
     */
    CapDelayedDelivery = "message.delayedDelivery",
    CapClusterTopology = "cluster.topology",

    /**
     * CapDirectory is listing the discovery tier a cluster is reached
     * through. Families whose nodes find each other have no such tier and do
     * not report it.
     */
    CapDirectory = "cluster.directory",

    /**
     * CapNodeConfig is reading the effective settings of a node or of the
     * cluster's discovery tier - what they are actually running with, which is
     * not always what their config files say.
     */
    CapNodeConfig = "cluster.nodeConfig",

    /**
     * CapNodeMaintenance is running a broker's own housekeeping on demand -
     * reclaiming space the broker would otherwise get to on its own schedule.
     */
    CapNodeMaintenance = "cluster.nodeMaintenance",
    CapClusterMetrics = "cluster.metrics",
    CapAccessControl = "access.control",

    /**
     * CapAccessDirectory is identity-based access control: principals the
     * broker authenticates and rules attached to a subject. Distinct from
     * CapAccessControl, which is the credential-carrying kind a broker will
     * take a write for and never read back.
     */
    CapAccessDirectory = "access.directory",
    CapRouting = "routing.exchanges",
};

/**
 * CloneOffsetRequest copies one subscription's read position onto another.
 * 
 * The usual reason is standing up a replacement consumer group without
 * replaying everything the old one already handled: the new group starts
 * exactly where the old one is.
 */
export class CloneOffsetRequest {
    "from": string;
    "to": string;

    /**
     * Destination narrows the copy to one topic. Empty copies every topic the
     * source group reads.
     */
    "destination": string;

    /**
     * FromOffline reads the source's positions from stored offsets rather than
     * from its live consumers. Required when the source group is already shut
     * down, which is the ordinary case during a migration.
     */
    "fromOffline": boolean;

    /** Creates a new CloneOffsetRequest instance. */
    constructor($$source: Partial<CloneOffsetRequest> = {}) {
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("fromOffline" in $$source)) {
            this["fromOffline"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloneOffsetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CloneOffsetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloneOffsetRequest($$parsedSource as Partial<CloneOffsetRequest>);
    }
}

/**
 * ClusterOverview is the aggregate the Cluster page header shows.
 */
export class ClusterOverview {
    "name": string;
    "totalNodes": number;
    "onlineNodes": number;

    /**
     * UnknownMetric when not enumerable
     */
    "destinations": number;
    "subscriptions": number;

    /**
     * percent; UnknownMetric when not reported
     */
    "avgDiskUsage": number;

    /** Creates a new ClusterOverview instance. */
    constructor($$source: Partial<ClusterOverview> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("totalNodes" in $$source)) {
            this["totalNodes"] = 0;
        }
        if (!("onlineNodes" in $$source)) {
            this["onlineNodes"] = 0;
        }
        if (!("destinations" in $$source)) {
            this["destinations"] = 0;
        }
        if (!("subscriptions" in $$source)) {
            this["subscriptions"] = 0;
        }
        if (!("avgDiskUsage" in $$source)) {
            this["avgDiskUsage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterOverview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterOverview($$parsedSource as Partial<ClusterOverview>);
    }
}

/**
 * ConnectionStatus is the connection status.
 */
export enum ConnectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusOnline = "online",
    StatusOffline = "offline",
};

/**
 * ConsumeThroughput is one destination's consume rates for one client.
 */
export class ConsumeThroughput {
    "destination": string;
    "pullLatencyMs": number;
    "pullRate": number;
    "consumeLatencyMs": number;
    "successRate": number;
    "failureRate": number;
    "failedMessages": number;

    /** Creates a new ConsumeThroughput instance. */
    constructor($$source: Partial<ConsumeThroughput> = {}) {
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("pullLatencyMs" in $$source)) {
            this["pullLatencyMs"] = 0;
        }
        if (!("pullRate" in $$source)) {
            this["pullRate"] = 0;
        }
        if (!("consumeLatencyMs" in $$source)) {
            this["consumeLatencyMs"] = 0;
        }
        if (!("successRate" in $$source)) {
            this["successRate"] = 0;
        }
        if (!("failureRate" in $$source)) {
            this["failureRate"] = 0;
        }
        if (!("failedMessages" in $$source)) {
            this["failedMessages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumeThroughput instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsumeThroughput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsumeThroughput($$parsedSource as Partial<ConsumeThroughput>);
    }
}

/**
 * Destination is a topic, queue or stream as the canonical pages see it.
 * 
 * Attributes carries whatever the family has and the canonical model does not:
 * RocketMQ permissions and queue counts, RabbitMQ durability and queue type,
 * Kafka replication factor. Its keys are a contract between one driver's Go
 * side and that driver's frontend module, not part of the shared vocabulary.
 */
export class Destination {
    /**
     * list key for the renderer, not broker data
     */
    "id": number;
    "ref": DestinationRef;

    /**
     * UnknownMetric where the family has none
     */
    "partitions": number;

    /**
     * consumer groups, subscriptions or consumers
     */
    "subscribers": number;

    /**
     * messages held; UnknownMetric when not reported
     */
    "depth": number;

    /**
     * messages per second in
     */
    "rateIn": number;

    /**
     * messages per second out
     */
    "rateOut": number;
    "lastUpdated": string;
    "attributes": { [_ in string]?: string };

    /** Creates a new Destination instance. */
    constructor($$source: Partial<Destination> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ref" in $$source)) {
            this["ref"] = (new DestinationRef());
        }
        if (!("partitions" in $$source)) {
            this["partitions"] = 0;
        }
        if (!("subscribers" in $$source)) {
            this["subscribers"] = 0;
        }
        if (!("depth" in $$source)) {
            this["depth"] = 0;
        }
        if (!("rateIn" in $$source)) {
            this["rateIn"] = 0;
        }
        if (!("rateOut" in $$source)) {
            this["rateOut"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = "";
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Destination instance from a string or object.
     */
    static createFrom($$source: any = {}): Destination {
        const $$createField1_0 = $$createType6;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField1_0($$parsedSource["ref"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField8_0($$parsedSource["attributes"]);
        }
        return new Destination($$parsedSource as Partial<Destination>);
    }
}

/**
 * DestinationRef identifies a destination across families.
 * 
 * Flat families leave Namespace empty; Pulsar fills tenant/namespace and
 * RabbitMQ fills the vhost. It is a struct rather than a string because
 * joining and re-splitting those parts loses information for any name that
 * contains the separator.
 */
export class DestinationRef {
    "namespace": string;
    "name": string;

    /** Creates a new DestinationRef instance. */
    constructor($$source: Partial<DestinationRef> = {}) {
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DestinationRef instance from a string or object.
     */
    static createFrom($$source: any = {}): DestinationRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DestinationRef($$parsedSource as Partial<DestinationRef>);
    }
}

/**
 * DriverDescriptor is what a family can do before any connection is open.
 * 
 * Display strings are deliberately absent: the renderer resolves them from
 * the i18n bundle under mq.<kind>.*, so translations stay where translations
 * live.
 */
export class DriverDescriptor {
    "kind": MQKind;
    "defaultPort": string;
    "form": FormField[];

    /**
     * MaxCapabilities is the best case for the family. A live connection can
     * only narrow it, never widen it, and the driver conformance test asserts
     * every entry is backed by an implemented interface.
     */
    "maxCapabilities": Capability[];

    /** Creates a new DriverDescriptor instance. */
    constructor($$source: Partial<DriverDescriptor> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = MQKind.$zero;
        }
        if (!("defaultPort" in $$source)) {
            this["defaultPort"] = "";
        }
        if (!("form" in $$source)) {
            this["form"] = [];
        }
        if (!("maxCapabilities" in $$source)) {
            this["maxCapabilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DriverDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): DriverDescriptor {
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("form" in $$parsedSource) {
            $$parsedSource["form"] = $$createField2_0($$parsedSource["form"]);
        }
        if ("maxCapabilities" in $$parsedSource) {
            $$parsedSource["maxCapabilities"] = $$createField3_0($$parsedSource["maxCapabilities"]);
        }
        return new DriverDescriptor($$parsedSource as Partial<DriverDescriptor>);
    }
}

/**
 * FieldCond hides a field unless another field holds one of Equals.
 */
export class FieldCond {
    "field": string;
    "equals": string[];

    /** Creates a new FieldCond instance. */
    constructor($$source: Partial<FieldCond> = {}) {
        if (!("field" in $$source)) {
            this["field"] = "";
        }
        if (!("equals" in $$source)) {
            this["equals"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldCond instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldCond {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("equals" in $$parsedSource) {
            $$parsedSource["equals"] = $$createField1_0($$parsedSource["equals"]);
        }
        return new FieldCond($$parsedSource as Partial<FieldCond>);
    }
}

/**
 * FieldTarget says which part of a ConnectionProfile a field writes into.
 * Secrets are encrypted at rest and never serialised back to the renderer.
 */
export enum FieldTarget {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TargetEndpoints = "endpoints",
    TargetOption = "option",
    TargetSecret = "secret",
    TargetAuth = "auth",
};

/**
 * FieldType is how the renderer draws one connection-form field.
 */
export enum FieldType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FieldText = "text",
    FieldPassword = "password",
    FieldNumber = "number",
    FieldSelect = "select",
    FieldSwitch = "switch",
    FieldEndpointList = "endpoint-list",
};

/**
 * FormField is one row of a driver's connection form.
 */
export class FormField {
    "key": string;
    "target": FieldTarget;
    "type": FieldType;

    /**
     * i18n key, never a literal
     */
    "labelKey": string;
    "placeholder": string;
    "default": string;
    "required": boolean;
    "visibleWhen": FieldCond | null;
    "options": FormOption[];

    /**
     * Validate names a validator the renderer already implements, such as
     * "host-port" or "url". Shipping a regex across the bridge would move
     * validation logic out of review and into data.
     */
    "validate": string;

    /** Creates a new FormField instance. */
    constructor($$source: Partial<FormField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = FieldTarget.$zero;
        }
        if (!("type" in $$source)) {
            this["type"] = FieldType.$zero;
        }
        if (!("labelKey" in $$source)) {
            this["labelKey"] = "";
        }
        if (!("placeholder" in $$source)) {
            this["placeholder"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("required" in $$source)) {
            this["required"] = false;
        }
        if (!("visibleWhen" in $$source)) {
            this["visibleWhen"] = null;
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }
        if (!("validate" in $$source)) {
            this["validate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormField instance from a string or object.
     */
    static createFrom($$source: any = {}): FormField {
        const $$createField7_0 = $$createType10;
        const $$createField8_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("visibleWhen" in $$parsedSource) {
            $$parsedSource["visibleWhen"] = $$createField7_0($$parsedSource["visibleWhen"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField8_0($$parsedSource["options"]);
        }
        return new FormField($$parsedSource as Partial<FormField>);
    }
}

/**
 * FormOption is one choice in a select field.
 */
export class FormOption {
    "value": string;
    "labelKey": string;

    /** Creates a new FormOption instance. */
    constructor($$source: Partial<FormOption> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("labelKey" in $$source)) {
            this["labelKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormOption instance from a string or object.
     */
    static createFrom($$source: any = {}): FormOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FormOption($$parsedSource as Partial<FormOption>);
    }
}

/**
 * MQKind identifies a broker family.
 * 
 * The values are the key for the driver registry, the per-kind settings
 * defaults and the `kind` field in connections.json, so they are part of the
 * on-disk format and must not be renamed.
 */
export enum MQKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindRocketMQ = "rocketmq",
    KindKafka = "kafka",
    KindRabbitMQ = "rabbitmq",
    KindPulsar = "pulsar",
    KindActiveMQ = "activemq",
    KindRedisStream = "redis-stream",
    KindNATS = "nats",
    KindNSQ = "nsq",
    KindMQTT = "mqtt",

    /**
     * Hosted families authenticate through Options and Secrets rather than
     * Endpoints: there is no broker address to dial, only a region and a
     * credential.
     */
    KindSQS = "sqs",
    KindGooglePubSub = "google-pubsub",
    KindAzureServiceBus = "azure-servicebus",
    KindKinesis = "kinesis",
    KindIBMMQ = "ibmmq",
    KindSolace = "solace",
};

/**
 * MessageItem holds message information.
 */
export class MessageItem {
    /**
     * Message sequence number
     */
    "id": number;

    /**
     * Cluster name
     */
    "cluster": string;

    /**
     * Topic name
     */
    "topic": string;

    /**
     * Message ID
     */
    "messageId": string;

    /**
     * Message tags
     */
    "tags": string;

    /**
     * Message keys
     */
    "keys": string;

    /**
     * Queue ID
     */
    "queueId": number;

    /**
     * Queue offset
     */
    "queueOffset": number;

    /**
     * Store host
     */
    "storeHost": string;

    /**
     * Born host
     */
    "bornHost": string;

    /**
     * Store time
     */
    "storeTime": string;

    /**
     * Store timestamp
     */
    "storeTimestamp": number;

    /**
     * Message status
     */
    "status": MessageStatus;

    /**
     * Retry times
     */
    "retryTimes": number;

    /**
     * Message body
     */
    "body": string;

    /**
     * Message properties
     */
    "properties": { [_ in string]?: string };

    /** Creates a new MessageItem instance. */
    constructor($$source: Partial<MessageItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = "";
        }
        if (!("keys" in $$source)) {
            this["keys"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = 0;
        }
        if (!("queueOffset" in $$source)) {
            this["queueOffset"] = 0;
        }
        if (!("storeHost" in $$source)) {
            this["storeHost"] = "";
        }
        if (!("bornHost" in $$source)) {
            this["bornHost"] = "";
        }
        if (!("storeTime" in $$source)) {
            this["storeTime"] = "";
        }
        if (!("storeTimestamp" in $$source)) {
            this["storeTimestamp"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = MessageStatus.$zero;
        }
        if (!("retryTimes" in $$source)) {
            this["retryTimes"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageItem {
        const $$createField15_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField15_0($$parsedSource["properties"]);
        }
        return new MessageItem($$parsedSource as Partial<MessageItem>);
    }
}

/**
 * MessageStatus is the message status.
 */
export enum MessageStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MsgNormal = "normal",
    MsgRetry = "retry",
    MsgDLQ = "dlq",
};

/**
 * MessageTrackItem holds message track information.
 */
export class MessageTrackItem {
    /**
     * Consumer group
     */
    "consumerGroup": string;

    /**
     * Track type: CONSUMED / NOT_CONSUME_YET / CONSUMED_BUT_FILTERED / UNKNOWN
     */
    "trackType": string;

    /**
     * Consume status description
     */
    "consumeStatus": string;

    /**
     * Exception description
     */
    "exceptionDesc": string;

    /** Creates a new MessageTrackItem instance. */
    constructor($$source: Partial<MessageTrackItem> = {}) {
        if (!("consumerGroup" in $$source)) {
            this["consumerGroup"] = "";
        }
        if (!("trackType" in $$source)) {
            this["trackType"] = "";
        }
        if (!("consumeStatus" in $$source)) {
            this["consumeStatus"] = "";
        }
        if (!("exceptionDesc" in $$source)) {
            this["exceptionDesc"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageTrackItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageTrackItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageTrackItem($$parsedSource as Partial<MessageTrackItem>);
    }
}

/**
 * Node is one broker, RabbitMQ node or Kafka broker as the canonical Cluster
 * page sees it.
 * 
 * It is deliberately thinner than BrokerNode: the TPS history arrays there are
 * filled by the cluster service from local samples, not by any broker, so they
 * stay out of what a driver has to produce.
 */
export class Node {
    /**
     * list key for the renderer, not broker data
     */
    "id": number;
    "name": string;
    "address": string;

    /**
     * grouping label; empty where the family has none
     */
    "cluster": string;
    "version": string;
    "status": NodeStatus;

    /**
     * messages per second in
     */
    "rateIn": number;

    /**
     * messages per second out
     */
    "rateOut": number;

    /**
     * percent; UnknownMetric when not reported
     */
    "diskUsage": number;
    "lastSeen": string;

    /**
     * TPS history is sampled locally by the collector, not reported by any
     * broker, which is why a driver never fills these.
     * Unix seconds
     */
    "tpsHistoryTimestamps": number[];
    "tpsInHistory": number[];
    "tpsOutHistory": number[];

    /**
     * Replicas is how far each follower of this node trails it, where the
     * family replicates. Empty on a follower, and on a leader with none.
     * 
     * Canonical rather than an attribute because every replicating family has
     * the question - RocketMQ slaves, Kafka ISR, RabbitMQ quorum members - and
     * "is a replica falling behind" is the one thing a cluster page is opened
     * to answer during an incident.
     * 
     * Filled only by NodeDetail: it costs a request per node, which a list
     * should not pay.
     */
    "replicas": ReplicaStatus[];

    /**
     * Attributes carries family-specific detail the canonical page renders
     * through the driver's own column set: RocketMQ master/slave role and
     * CommitLog usage, Kafka controller and ISR, RabbitMQ disc/ram node type.
     */
    "attributes": { [_ in string]?: string };

    /** Creates a new Node instance. */
    constructor($$source: Partial<Node> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = NodeStatus.$zero;
        }
        if (!("rateIn" in $$source)) {
            this["rateIn"] = 0;
        }
        if (!("rateOut" in $$source)) {
            this["rateOut"] = 0;
        }
        if (!("diskUsage" in $$source)) {
            this["diskUsage"] = 0;
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = "";
        }
        if (!("tpsHistoryTimestamps" in $$source)) {
            this["tpsHistoryTimestamps"] = [];
        }
        if (!("tpsInHistory" in $$source)) {
            this["tpsInHistory"] = [];
        }
        if (!("tpsOutHistory" in $$source)) {
            this["tpsOutHistory"] = [];
        }
        if (!("replicas" in $$source)) {
            this["replicas"] = [];
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     */
    static createFrom($$source: any = {}): Node {
        const $$createField10_0 = $$createType13;
        const $$createField11_0 = $$createType14;
        const $$createField12_0 = $$createType14;
        const $$createField13_0 = $$createType16;
        const $$createField14_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tpsHistoryTimestamps" in $$parsedSource) {
            $$parsedSource["tpsHistoryTimestamps"] = $$createField10_0($$parsedSource["tpsHistoryTimestamps"]);
        }
        if ("tpsInHistory" in $$parsedSource) {
            $$parsedSource["tpsInHistory"] = $$createField11_0($$parsedSource["tpsInHistory"]);
        }
        if ("tpsOutHistory" in $$parsedSource) {
            $$parsedSource["tpsOutHistory"] = $$createField12_0($$parsedSource["tpsOutHistory"]);
        }
        if ("replicas" in $$parsedSource) {
            $$parsedSource["replicas"] = $$createField13_0($$parsedSource["replicas"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField14_0($$parsedSource["attributes"]);
        }
        return new Node($$parsedSource as Partial<Node>);
    }
}

/**
 * NodeStatus is the node status.
 */
export enum NodeStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodeOnline = "online",
    NodeWarning = "warning",
    NodeOffline = "offline",

    /**
     * NodeUnknown is a node whose health the family does not report. A
     * RocketMQ name server is one: the admin protocol names the addresses the
     * client dials and says nothing about whether each of them answers, and
     * calling that "online" would be inventing a check nobody ran.
     */
    NodeUnknown = "unknown",
};

/**
 * ProducerClient is one connected publisher.
 * 
 * There is no list of publishers the way there is of subscriptions: a broker
 * tracks connections per producer group and offers no way to enumerate the
 * groups, so a caller has to name one. That is why this is not a Producer
 * type with a Ref - there is nothing to list, only something to look up.
 */
export class ProducerClient {
    "clientId": string;
    "address": string;
    "language": string;
    "version": string;

    /** Creates a new ProducerClient instance. */
    constructor($$source: Partial<ProducerClient> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProducerClient instance from a string or object.
     */
    static createFrom($$source: any = {}): ProducerClient {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProducerClient($$parsedSource as Partial<ProducerClient>);
    }
}

/**
 * QueueAssignment is one queue a consumer holds, and how far behind it is.
 */
export class QueueAssignment {
    "destination": string;

    /**
     * the broker holding this queue
     */
    "node": string;
    "queueId": number;

    /**
     * Pending is what this client has buffered but not yet finished, which is
     * not the same as the group's backlog on the broker.
     */
    "pending": number;
    "pendingBytes": number;
    "lastPull": string;
    "lastConsume": string;

    /**
     * Locked matters only where a family locks a queue to one consumer for
     * ordered delivery; Dropped means the client is releasing it in a rebalance.
     */
    "locked": boolean;
    "dropped": boolean;

    /** Creates a new QueueAssignment instance. */
    constructor($$source: Partial<QueueAssignment> = {}) {
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("node" in $$source)) {
            this["node"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = 0;
        }
        if (!("pending" in $$source)) {
            this["pending"] = 0;
        }
        if (!("pendingBytes" in $$source)) {
            this["pendingBytes"] = 0;
        }
        if (!("lastPull" in $$source)) {
            this["lastPull"] = "";
        }
        if (!("lastConsume" in $$source)) {
            this["lastConsume"] = "";
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }
        if (!("dropped" in $$source)) {
            this["dropped"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueAssignment instance from a string or object.
     */
    static createFrom($$source: any = {}): QueueAssignment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueAssignment($$parsedSource as Partial<QueueAssignment>);
    }
}

/**
 * QueuePosition is one partition's place in a tail.
 */
export class QueuePosition {
    /**
     * the broker holding it
     */
    "node": string;
    "queueId": number;
    "offset": number;

    /** Creates a new QueuePosition instance. */
    constructor($$source: Partial<QueuePosition> = {}) {
        if (!("node" in $$source)) {
            this["node"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueuePosition instance from a string or object.
     */
    static createFrom($$source: any = {}): QueuePosition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueuePosition($$parsedSource as Partial<QueuePosition>);
    }
}

/**
 * ReplayResult is what that consumer's own handler returned.
 * 
 * This is not a delivery receipt: the broker forwarded the message and the
 * client ran its listener, so a failure here is the application's, reported
 * back verbatim in Remark.
 */
export class ReplayResult {
    "result": string;
    "remark": string;
    "spentMs": number;

    /**
     * Ordered and AutoCommit describe how the client was configured to consume,
     * which changes what a failure means: an ordered consumer blocks its queue
     * on one it cannot handle.
     */
    "ordered": boolean;
    "autoCommit": boolean;

    /** Creates a new ReplayResult instance. */
    constructor($$source: Partial<ReplayResult> = {}) {
        if (!("result" in $$source)) {
            this["result"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("spentMs" in $$source)) {
            this["spentMs"] = 0;
        }
        if (!("ordered" in $$source)) {
            this["ordered"] = false;
        }
        if (!("autoCommit" in $$source)) {
            this["autoCommit"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplayResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplayResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplayResult($$parsedSource as Partial<ReplayResult>);
    }
}

/**
 * ReplicaStatus is one follower's replication state.
 */
export class ReplicaStatus {
    "address": string;

    /**
     * BehindBytes is how far this replica trails the leader's log. Zero means
     * caught up; UnknownMetric means the family reports no such figure.
     */
    "behindBytes": number;

    /**
     * InSync is the family's own verdict, which is not simply BehindBytes == 0:
     * a replica can be a little behind and still count as in sync.
     */
    "inSync": boolean;

    /** Creates a new ReplicaStatus instance. */
    constructor($$source: Partial<ReplicaStatus> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("behindBytes" in $$source)) {
            this["behindBytes"] = 0;
        }
        if (!("inSync" in $$source)) {
            this["inSync"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplicaStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplicaStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplicaStatus($$parsedSource as Partial<ReplicaStatus>);
    }
}

/**
 * ResetOffsetRequest is a request to reset offsets.
 */
export class ResetOffsetRequest {
    /**
     * Consumer group name
     */
    "group": string;

    /**
     * Topic name
     */
    "topic": string;

    /**
     * Timestamp (milliseconds)
     */
    "timestamp": number;

    /**
     * Whether to force reset
     */
    "force": boolean;

    /** Creates a new ResetOffsetRequest instance. */
    constructor($$source: Partial<ResetOffsetRequest> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("force" in $$source)) {
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetOffsetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetOffsetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetOffsetRequest($$parsedSource as Partial<ResetOffsetRequest>);
    }
}

/**
 * Subscription is a consumer group, a Pulsar subscription or a RabbitMQ queue
 * consumer, as the canonical pages see it.
 * 
 * Backlog is deliberately not called lag: RocketMQ and Kafka compute it from
 * offsets, RabbitMQ reads ready plus unacknowledged, and Redis Stream reads
 * XPENDING. The number means "messages still owed to this subscriber" in all
 * three, but only the first two have an offset behind it — which is why
 * resetting position is a separate capability.
 */
export class Subscription {
    /**
     * list key for the renderer, not broker data
     */
    "id": number;
    "ref": SubscriptionRef;
    "status": SubscriptionStatus;

    /**
     * connected consumers
     */
    "members": number;

    /**
     * how many it reads from
     */
    "destinations": number;

    /**
     * UnknownMetric when not reported
     */
    "backlog": number;

    /**
     * messages per second consumed
     */
    "rateOut": number;
    "lastUpdated": string;
    "attributes": { [_ in string]?: string };

    /** Creates a new Subscription instance. */
    constructor($$source: Partial<Subscription> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ref" in $$source)) {
            this["ref"] = (new SubscriptionRef());
        }
        if (!("status" in $$source)) {
            this["status"] = SubscriptionStatus.$zero;
        }
        if (!("members" in $$source)) {
            this["members"] = 0;
        }
        if (!("destinations" in $$source)) {
            this["destinations"] = 0;
        }
        if (!("backlog" in $$source)) {
            this["backlog"] = 0;
        }
        if (!("rateOut" in $$source)) {
            this["rateOut"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = "";
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Subscription instance from a string or object.
     */
    static createFrom($$source: any = {}): Subscription {
        const $$createField1_0 = $$createType17;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField1_0($$parsedSource["ref"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField8_0($$parsedSource["attributes"]);
        }
        return new Subscription($$parsedSource as Partial<Subscription>);
    }
}

/**
 * SubscriptionClient is what one connected consumer is actually doing.
 * 
 * It is separate from the client list a Subscription carries because the two
 * answer different questions and cost different things. The list says who is
 * connected, and comes back with the group. This is a round trip to that one
 * client, so it is fetched when someone asks about it.
 */
export class SubscriptionClient {
    "clientId": string;

    /**
     * Assignments is which queues this client currently holds. It is the
     * answer to "why is one consumer behind and the others idle", which a
     * group-level backlog cannot give.
     */
    "assignments": QueueAssignment[];

    /**
     * Throughput is per destination, because a client reading two topics can
     * be healthy on one and stalled on the other.
     */
    "throughput": ConsumeThroughput[];

    /**
     * Properties is what the client reports about itself - version, consume
     * mode, thread counts. Free-form because every family names them
     * differently and none of it is worth a canonical field.
     */
    "properties": { [_ in string]?: string };

    /** Creates a new SubscriptionClient instance. */
    constructor($$source: Partial<SubscriptionClient> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("assignments" in $$source)) {
            this["assignments"] = [];
        }
        if (!("throughput" in $$source)) {
            this["throughput"] = [];
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubscriptionClient instance from a string or object.
     */
    static createFrom($$source: any = {}): SubscriptionClient {
        const $$createField1_0 = $$createType19;
        const $$createField2_0 = $$createType21;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assignments" in $$parsedSource) {
            $$parsedSource["assignments"] = $$createField1_0($$parsedSource["assignments"]);
        }
        if ("throughput" in $$parsedSource) {
            $$parsedSource["throughput"] = $$createField2_0($$parsedSource["throughput"]);
        }
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField3_0($$parsedSource["properties"]);
        }
        return new SubscriptionClient($$parsedSource as Partial<SubscriptionClient>);
    }
}

/**
 * SubscriptionRef identifies a consumer group, subscription or queue consumer.
 */
export class SubscriptionRef {
    "namespace": string;
    "name": string;

    /** Creates a new SubscriptionRef instance. */
    constructor($$source: Partial<SubscriptionRef> = {}) {
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubscriptionRef instance from a string or object.
     */
    static createFrom($$source: any = {}): SubscriptionRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubscriptionRef($$parsedSource as Partial<SubscriptionRef>);
    }
}

/**
 * SubscriptionStatus is the health of a subscription.
 */
export enum SubscriptionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SubscriptionOnline = "online",
    SubscriptionWarning = "warning",
    SubscriptionOffline = "offline",
};

/**
 * TailBatch is one poll's worth of a tail.
 */
export class TailBatch {
    /**
     * Messages are oldest first, which is the order a tail appends in.
     */
    "messages": (MessageItem | null)[];

    /**
     * Cursor is what to pass next time. It advances even when no message came
     * back, because a partition can move on without this tail matching any.
     */
    "cursor": TailCursor;

    /**
     * Dropped counts messages that aged out of the log between two polls -
     * a tail slower than the retention it is watching. Reporting it is the
     * difference between a quiet tail and one that is silently losing.
     */
    "dropped": number;

    /** Creates a new TailBatch instance. */
    constructor($$source: Partial<TailBatch> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("cursor" in $$source)) {
            this["cursor"] = (new TailCursor());
        }
        if (!("dropped" in $$source)) {
            this["dropped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TailBatch instance from a string or object.
     */
    static createFrom($$source: any = {}): TailBatch {
        const $$createField0_0 = $$createType24;
        const $$createField1_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        if ("cursor" in $$parsedSource) {
            $$parsedSource["cursor"] = $$createField1_0($$parsedSource["cursor"]);
        }
        return new TailBatch($$parsedSource as Partial<TailBatch>);
    }
}

/**
 * TailCursor is where a tail has read to, per partition.
 * 
 * An empty cursor means "start at the end": a tail opens on what arrives next
 * rather than replaying what is already stored, which is what the message
 * query is for.
 */
export class TailCursor {
    "positions": QueuePosition[];

    /** Creates a new TailCursor instance. */
    constructor($$source: Partial<TailCursor> = {}) {
        if (!("positions" in $$source)) {
            this["positions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TailCursor instance from a string or object.
     */
    static createFrom($$source: any = {}): TailCursor {
        const $$createField0_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("positions" in $$parsedSource) {
            $$parsedSource["positions"] = $$createField0_0($$parsedSource["positions"]);
        }
        return new TailCursor($$parsedSource as Partial<TailCursor>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AccessPolicy.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = DestinationRef.createFrom;
const $$createType7 = FormField.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = FieldCond.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = FormOption.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($Create.Any);
const $$createType14 = $Create.Array($Create.Any);
const $$createType15 = ReplicaStatus.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = SubscriptionRef.createFrom;
const $$createType18 = QueueAssignment.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = ConsumeThroughput.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = MessageItem.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = TailCursor.createFrom;
const $$createType26 = QueuePosition.createFrom;
const $$createType27 = $Create.Array($$createType26);
