// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AccessPolicy grants or denies actions on one resource.
 */
export class AccessPolicy {
    /**
     * a topic, a group, or the cluster
     */
    "resource": string;

    /**
     * PUB, SUB, and the family's own verbs
     */
    "actions": string[];

    /**
     * Allow, Deny
     */
    "effect": string;

    /**
     * SourceIPs narrows the rule to callers from these addresses. Empty means
     * any source.
     */
    "sourceIps": string[];

    /**
     * Decision is what the broker actually decided for this policy, which is
     * not always its effect - a later rule can override an earlier one.
     */
    "decision": string;

    /** Creates a new AccessPolicy instance. */
    constructor($$source: Partial<AccessPolicy> = {}) {
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("actions" in $$source)) {
            this["actions"] = [];
        }
        if (!("effect" in $$source)) {
            this["effect"] = "";
        }
        if (!("sourceIps" in $$source)) {
            this["sourceIps"] = [];
        }
        if (!("decision" in $$source)) {
            this["decision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessPolicy instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessPolicy {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField1_0($$parsedSource["actions"]);
        }
        if ("sourceIps" in $$parsedSource) {
            $$parsedSource["sourceIps"] = $$createField3_0($$parsedSource["sourceIps"]);
        }
        return new AccessPolicy($$parsedSource as Partial<AccessPolicy>);
    }
}

/**
 * AccessPrincipal is one identity the broker authenticates.
 * 
 * RocketMQ 5.3 calls it a user, Kafka a principal. Type and status stay the
 * family's own words: what values they take differs per family, and
 * normalising them would lose exactly what an operator has to type back.
 */
export class AccessPrincipal {
    "name": string;
    "type": string;
    "status": string;

    /** Creates a new AccessPrincipal instance. */
    constructor($$source: Partial<AccessPrincipal> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessPrincipal instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessPrincipal {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessPrincipal($$parsedSource as Partial<AccessPrincipal>);
    }
}

/**
 * AccessRule is everything one subject is permitted to do.
 * 
 * Identity-based rather than key-based, which is what separates it from
 * AccessConfig: a rule names a subject the broker already knows, where an
 * AccessConfig carries the credential and the permissions together.
 */
export class AccessRule {
    "subject": string;
    "policies": AccessPolicy[];
    "description": string;

    /** Creates a new AccessRule instance. */
    constructor($$source: Partial<AccessRule> = {}) {
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("policies" in $$source)) {
            this["policies"] = [];
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessRule instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessRule {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("policies" in $$parsedSource) {
            $$parsedSource["policies"] = $$createField1_0($$parsedSource["policies"]);
        }
        return new AccessRule($$parsedSource as Partial<AccessRule>);
    }
}

/**
 * AclVersionInfo holds ACL config version information.
 */
export class AclVersionInfo {
    "brokerAddr": string;
    "brokerName": string;
    "clusterName": string;
    "version": string;

    /** Creates a new AclVersionInfo instance. */
    constructor($$source: Partial<AclVersionInfo> = {}) {
        if (!("brokerAddr" in $$source)) {
            this["brokerAddr"] = "";
        }
        if (!("brokerName" in $$source)) {
            this["brokerName"] = "";
        }
        if (!("clusterName" in $$source)) {
            this["clusterName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AclVersionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AclVersionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AclVersionInfo($$parsedSource as Partial<AclVersionInfo>);
    }
}

/**
 * AuthMechanism is how a connection authenticates.
 */
export enum AuthMechanism {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthNone = "none",

    /**
     * RocketMQ AccessKey / SecretKey
     */
    AuthACL = "acl",
    AuthPlain = "plain",
    AuthSASLPlain = "sasl-plain",
    AuthSASLScram = "sasl-scram",
    AuthToken = "token",
    AuthMutualTLS = "mtls",
};

/**
 * Binding is a route from an exchange to a queue or another exchange.
 * 
 * Only RabbitMQ has first-class bindings, which is why the canonical page set
 * has no counterpart for them and the driver contributes a page of its own.
 */
export class Binding {
    /**
     * list key for the renderer
     */
    "id": number;
    "namespace": string;
    "source": string;
    "destination": string;

    /**
     * DestinationKind separates a queue target from an exchange target; the
     * same source and name can bind to both.
     */
    "destinationKind": string;
    "routingKey": string;
    "arguments": { [_ in string]?: string };

    /**
     * PropertiesKey is the broker's own identifier for this binding, and the
     * only way to delete one. A binding has no name, and the same source,
     * destination and routing key can exist more than once with different
     * arguments - so anything a caller made up would delete a different
     * binding or none. It comes back with the listing.
     */
    "propertiesKey": string;

    /** Creates a new Binding instance. */
    constructor($$source: Partial<Binding> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("destinationKind" in $$source)) {
            this["destinationKind"] = "";
        }
        if (!("routingKey" in $$source)) {
            this["routingKey"] = "";
        }
        if (!("arguments" in $$source)) {
            this["arguments"] = {};
        }
        if (!("propertiesKey" in $$source)) {
            this["propertiesKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Binding instance from a string or object.
     */
    static createFrom($$source: any = {}): Binding {
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("arguments" in $$parsedSource) {
            $$parsedSource["arguments"] = $$createField6_0($$parsedSource["arguments"]);
        }
        return new Binding($$parsedSource as Partial<Binding>);
    }
}

/**
 * BrokerCensus is a broker-wide snapshot: how many of each object exists, how
 * much is sitting in queues, and how fast messages are moving through.
 * 
 * It is separate from ClusterOverview because the two answer different
 * questions. ClusterOverview is the topology - how many nodes, how many are
 * up - and every family has one. This is the broker's own running total, which
 * only a family with a single endpoint that aggregates the cluster can report;
 * RabbitMQ's management API is one, and RocketMQ has no counterpart.
 * 
 * Counts a family does not report carry UnknownMetric rather than zero, so the
 * page renders an em dash instead of a measurement that was never taken.
 */
export class BrokerCensus {
    "clusterName": string;
    "version": string;
    "runtimeVersion": string;
    "queues": number;
    "exchanges": number;
    "connections": number;
    "channels": number;
    "consumers": number;

    /**
     * Ready is deliverable now, Unacknowledged is with a consumer that has not
     * acked yet. Total is what the broker holds and is not always their sum:
     * it counts messages in states neither covers.
     */
    "ready": number;
    "unacknowledged": number;
    "total": number;
    "rates": BrokerRates;

    /** Creates a new BrokerCensus instance. */
    constructor($$source: Partial<BrokerCensus> = {}) {
        if (!("clusterName" in $$source)) {
            this["clusterName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("runtimeVersion" in $$source)) {
            this["runtimeVersion"] = "";
        }
        if (!("queues" in $$source)) {
            this["queues"] = 0;
        }
        if (!("exchanges" in $$source)) {
            this["exchanges"] = 0;
        }
        if (!("connections" in $$source)) {
            this["connections"] = 0;
        }
        if (!("channels" in $$source)) {
            this["channels"] = 0;
        }
        if (!("consumers" in $$source)) {
            this["consumers"] = 0;
        }
        if (!("ready" in $$source)) {
            this["ready"] = 0;
        }
        if (!("unacknowledged" in $$source)) {
            this["unacknowledged"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("rates" in $$source)) {
            this["rates"] = (new BrokerRates());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrokerCensus instance from a string or object.
     */
    static createFrom($$source: any = {}): BrokerCensus {
        const $$createField11_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rates" in $$parsedSource) {
            $$parsedSource["rates"] = $$createField11_0($$parsedSource["rates"]);
        }
        return new BrokerCensus($$parsedSource as Partial<BrokerCensus>);
    }
}

/**
 * BrokerHealth is everything a cluster page asks beyond the node list.
 */
export class BrokerHealth {
    "checks": (HealthCheck | null)[];
    "alarms": (ResourceAlarm | null)[];
    "featureFlags": (FeatureFlag | null)[];
    "deprecatedFeatures": (DeprecatedFeature | null)[];

    /** Creates a new BrokerHealth instance. */
    constructor($$source: Partial<BrokerHealth> = {}) {
        if (!("checks" in $$source)) {
            this["checks"] = [];
        }
        if (!("alarms" in $$source)) {
            this["alarms"] = [];
        }
        if (!("featureFlags" in $$source)) {
            this["featureFlags"] = [];
        }
        if (!("deprecatedFeatures" in $$source)) {
            this["deprecatedFeatures"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrokerHealth instance from a string or object.
     */
    static createFrom($$source: any = {}): BrokerHealth {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType13;
        const $$createField3_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("checks" in $$parsedSource) {
            $$parsedSource["checks"] = $$createField0_0($$parsedSource["checks"]);
        }
        if ("alarms" in $$parsedSource) {
            $$parsedSource["alarms"] = $$createField1_0($$parsedSource["alarms"]);
        }
        if ("featureFlags" in $$parsedSource) {
            $$parsedSource["featureFlags"] = $$createField2_0($$parsedSource["featureFlags"]);
        }
        if ("deprecatedFeatures" in $$parsedSource) {
            $$parsedSource["deprecatedFeatures"] = $$createField3_0($$parsedSource["deprecatedFeatures"]);
        }
        return new BrokerHealth($$parsedSource as Partial<BrokerHealth>);
    }
}

/**
 * BrokerRates is messages per second, as the broker computes them over its own
 * sampling window rather than as anything measured here.
 */
export class BrokerRates {
    "publish": number;
    "deliver": number;
    "ack": number;
    "redeliver": number;

    /**
     * Unroutable is publishes that matched no binding. It has no counterpart
     * in a family that publishes straight to a destination, and it is the
     * first thing worth knowing when messages "disappear" on a topology whose
     * bindings are wrong.
     */
    "unroutable": number;

    /** Creates a new BrokerRates instance. */
    constructor($$source: Partial<BrokerRates> = {}) {
        if (!("publish" in $$source)) {
            this["publish"] = 0;
        }
        if (!("deliver" in $$source)) {
            this["deliver"] = 0;
        }
        if (!("ack" in $$source)) {
            this["ack"] = 0;
        }
        if (!("redeliver" in $$source)) {
            this["redeliver"] = 0;
        }
        if (!("unroutable" in $$source)) {
            this["unroutable"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrokerRates instance from a string or object.
     */
    static createFrom($$source: any = {}): BrokerRates {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrokerRates($$parsedSource as Partial<BrokerRates>);
    }
}

/**
 * Capabilities is what one live connection can actually do.
 * 
 * Three states reach the UI, and they must stay distinguishable: a capability
 * in Supported renders normally; one in Degraded renders disabled with the
 * reason; one in neither is hidden outright. Silent absence and explained
 * absence look identical to a user otherwise, which makes a deliberately
 * limited endpoint read as a bug.
 */
export class Capabilities {
    "supported": Capability[];

    /**
     * Degraded explains a capability the family has but this endpoint lacks.
     * A RocketMQ Proxy endpoint is a data plane only, so it reports no topic
     * listing, no cluster topology and no ACL.
     */
    "degraded": { [_ in Capability]?: string };

    /**
     * Caveats annotates a capability that works but has a consequence worth
     * warning about. Browsing a RabbitMQ queue goes through basic.get, which
     * alters queue state even when the message is requeued.
     */
    "caveats": { [_ in Capability]?: string };

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = [];
        }
        if (!("degraded" in $$source)) {
            this["degraded"] = {};
        }
        if (!("caveats" in $$source)) {
            this["caveats"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        const $$createField0_0 = $$createType17;
        const $$createField1_0 = $$createType18;
        const $$createField2_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supported" in $$parsedSource) {
            $$parsedSource["supported"] = $$createField0_0($$parsedSource["supported"]);
        }
        if ("degraded" in $$parsedSource) {
            $$parsedSource["degraded"] = $$createField1_0($$parsedSource["degraded"]);
        }
        if ("caveats" in $$parsedSource) {
            $$parsedSource["caveats"] = $$createField2_0($$parsedSource["caveats"]);
        }
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

/**
 * Capability names one operation the UI gates on.
 * 
 * The values cross the bridge and are matched as literals in the renderer, so
 * renaming one means changing frontend/src/mq/capabilities.ts in the same
 * commit.
 */
export enum Capability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CapDestinationList = "destination.list",
    CapDestinationCreate = "destination.create",
    CapDestinationUpdate = "destination.update",
    CapDestinationDelete = "destination.delete",
    CapPartitions = "destination.partitions",

    /**
     * CapDestinationPurge empties a destination without deleting it, and
     * CapDestinationMove drains one into another. Separate capabilities
     * because they are separate buttons with very different blast radii: one
     * discards, the other relocates.
     */
    CapDestinationPurge = "destination.purge",
    CapDestinationMove = "destination.move",

    /**
     * CapQueueRebalance spreads replicated destinations' leaders back across
     * the cluster. Only a family that elects a leader per destination has it.
     */
    CapQueueRebalance = "destination.rebalance",
    CapSubscriptionList = "subscription.list",
    CapSubscriptionCreate = "subscription.create",
    CapSubscriptionDelete = "subscription.delete",
    CapSubscriptionLag = "subscription.lag",
    CapOffsetReset = "subscription.resetOffset",

    /**
     * CapOffsetClone is copying one subscription's read position onto another.
     * It is not CapOffsetReset: reset moves a group in time, this hands a
     * second group the first one's exact per-queue positions.
     */
    CapOffsetClone = "subscription.cloneOffset",

    /**
     * CapQueueOffset is writing one queue's read position directly. Distinct
     * from CapOffsetReset, which moves a whole subscription to a moment in
     * time and lets the broker find each queue's position for itself.
     */
    CapQueueOffset = "subscription.queueOffset",

    /**
     * CapSubscriptionRuntime is asking a connected consumer what it is doing:
     * which queues it holds and how fast it is getting through them. Only a
     * live client can answer, so a family without client introspection - or a
     * group with nothing connected - simply has no answer.
     */
    CapSubscriptionRuntime = "subscription.runtime",
    CapMessageQuery = "message.query",
    CapMessageByID = "message.byId",
    CapMessageTrack = "message.track",
    CapMessageResend = "message.resend",

    /**
     * CapMessageReplay is handing one message back to one connected consumer
     * and reporting what its handler returned. Distinct from CapMessageResend,
     * which puts a copy back on the retry path for whoever picks it up.
     */
    CapMessageReplay = "message.replay",
    CapMessageLiveTail = "message.liveTail",
    CapDLQ = "message.dlq",
    CapPublish = "message.publish",

    /**
     * CapPublishRich is a send console that can set what the family's own
     * protocol carries - an exchange and routing key, headers, and the
     * delivery guarantees - rather than only a destination and a body.
     */
    CapPublishRich = "message.publishRich",

    /**
     * CapProducerInspect is asking who is currently publishing. It needs a
     * producer group to ask about: the broker tracks connections per group and
     * offers no way to enumerate the groups themselves.
     */
    CapProducerInspect = "message.producerInspect",

    /**
     * CapDelayedDelivery is scheduling a message for later. RocketMQ has delay
     * levels, Kafka has nothing, RabbitMQ needs a plugin.
     */
    CapDelayedDelivery = "message.delayedDelivery",
    CapClusterTopology = "cluster.topology",

    /**
     * CapDirectory is listing the discovery tier a cluster is reached
     * through. Families whose nodes find each other have no such tier and do
     * not report it.
     */
    CapDirectory = "cluster.directory",

    /**
     * CapNodeConfig is reading the effective settings of a node or of the
     * cluster's discovery tier - what they are actually running with, which is
     * not always what their config files say.
     */
    CapNodeConfig = "cluster.nodeConfig",

    /**
     * CapNodeMaintenance is running a broker's own housekeeping on demand -
     * reclaiming space the broker would otherwise get to on its own schedule.
     */
    CapNodeMaintenance = "cluster.nodeMaintenance",

    /**
     * CapNodeWritePerm is taking a node out of the write path and putting it
     * back, which is how a broker is drained before it is stopped.
     */
    CapNodeWritePerm = "cluster.writePerm",
    CapClusterMetrics = "cluster.metrics",

    /**
     * CapClusterCensus is a broker that keeps its own running totals - object
     * counts, queued depth and message rates for the whole cluster in one
     * answer. A family whose figures can only be assembled by walking every
     * destination does not have it.
     */
    CapClusterCensus = "cluster.census",

    /**
     * CapClientInspect is a broker that can name the transport connections and
     * channels open against it. Families that expose producers and consumers
     * but not the sessions underneath them do not have it.
     */
    CapClientInspect = "client.inspect",

    /**
     * CapClientClose disconnects a client from the broker. Separate from
     * inspecting them: a monitoring user can list every connection and close
     * none.
     */
    CapClientClose = "client.close",

    /**
     * CapClusterHealth is a broker that answers questions about its own
     * health, rather than one whose health has to be inferred from its
     * metrics.
     */
    CapClusterHealth = "cluster.health",

    /**
     * CapDeadLetterTopology is a family whose dead-letter queues are ordinary
     * queues something else points at, found by walking the topology, rather
     * than a per-group topic the broker names for you. Both answer the same
     * page; neither can answer it the other's way.
     */
    CapDeadLetterTopology = "message.dlqTopology",
    CapAccessControl = "access.control",

    /**
     * CapAccessDirectory is identity-based access control: principals the
     * broker authenticates and rules attached to a subject. Distinct from
     * CapAccessControl, which is the credential-carrying kind a broker will
     * take a write for and never read back.
     */
    CapAccessDirectory = "access.directory",

    /**
     * CapNamespaceList and CapNamespaceAdmin are families whose namespaces are
     * objects rather than labels - a RabbitMQ virtual host holds its own
     * queues, exchanges, policies and permissions, and nothing crosses
     * between two of them.
     */
    CapNamespaceList = "namespace.list",
    CapNamespaceAdmin = "namespace.admin",

    /**
     * CapNamespaceLimits caps a namespace as a whole rather than one
     * destination inside it.
     */
    CapNamespaceLimits = "namespace.limits",
    CapRouting = "routing.exchanges",

    /**
     * CapRoutingAdmin creates and deletes exchanges and bindings. Separate
     * from reading them: a connection may list a topology it has no permission
     * to change.
     */
    CapRoutingAdmin = "routing.admin",
};

/**
 * ClientChannel is one multiplexed session inside a connection.
 * 
 * A channel is where the interesting failure lives: prefetch and
 * unacknowledged counts are per channel, and a consumer that has stopped
 * acknowledging shows up here long before the queue depth makes it obvious.
 */
export class ClientChannel {
    "name": string;
    "number": number;
    "connection": string;
    "namespace": string;
    "user": string;
    "node": string;

    /**
     * There is deliberately no state field. The management API reports one but
     * the client library does not model it, and the two flags that matter -
     * flow-blocked and idle-since - are here in full, so deriving a word from
     * them would be inventing a field rather than reporting one.
     */
    "consumers": number;
    "prefetchCount": number;

    /**
     * Unacknowledged is delivered and not yet acked. Unconfirmed is published
     * and not yet confirmed back to the publisher. They are the two sides of
     * in-flight work and fail for opposite reasons.
     */
    "unacknowledged": number;
    "unconfirmed": number;

    /**
     * Confirms and Transactional are the two delivery guarantees a channel can
     * be in, and they are mutually exclusive in AMQP.
     */
    "confirms": boolean;
    "transactional": boolean;

    /**
     * FlowBlocked is the broker telling this channel to stop publishing. It is
     * the single most useful field here: a publisher that has slowed down for
     * no apparent reason is usually looking at this.
     */
    "flowBlocked": boolean;

    /**
     * IdleSince is when the channel last did anything, as the broker spells
     * it. Empty means it is busy now.
     */
    "idleSince": string;

    /** Creates a new ClientChannel instance. */
    constructor($$source: Partial<ClientChannel> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = 0;
        }
        if (!("connection" in $$source)) {
            this["connection"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("node" in $$source)) {
            this["node"] = "";
        }
        if (!("consumers" in $$source)) {
            this["consumers"] = 0;
        }
        if (!("prefetchCount" in $$source)) {
            this["prefetchCount"] = 0;
        }
        if (!("unacknowledged" in $$source)) {
            this["unacknowledged"] = 0;
        }
        if (!("unconfirmed" in $$source)) {
            this["unconfirmed"] = 0;
        }
        if (!("confirms" in $$source)) {
            this["confirms"] = false;
        }
        if (!("transactional" in $$source)) {
            this["transactional"] = false;
        }
        if (!("flowBlocked" in $$source)) {
            this["flowBlocked"] = false;
        }
        if (!("idleSince" in $$source)) {
            this["idleSince"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClientChannel instance from a string or object.
     */
    static createFrom($$source: any = {}): ClientChannel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClientChannel($$parsedSource as Partial<ClientChannel>);
    }
}

/**
 * ClientConnection is one application's connection to the broker.
 * 
 * It has no counterpart in the canonical vocabulary on purpose. RocketMQ and
 * Kafka expose producers and consumers, which are roles; this is the transport
 * underneath them, and an operator uses it for a different job - finding which
 * host is holding a connection open, which one is being throttled, and which
 * one to close when an application will not let go.
 */
export class ClientConnection {
    /**
     * Name is the broker's own identifier, of the form "host:port -> host:port".
     * It is what a close request names, so it is the key rather than a label.
     */
    "name": string;

    /**
     * ClientName is what the application called itself, or "" when it said
     * nothing. Most libraries send nothing, which is why the peer address
     * stays the primary identifier.
     */
    "clientName": string;
    "namespace": string;
    "user": string;
    "node": string;
    "peerHost": string;
    "peerPort": number;

    /**
     * Protocol is the wire protocol this connection speaks. A broker with the
     * MQTT or STOMP plugins on carries connections that are not AMQP at all,
     * and treating them alike would misreport both.
     */
    "protocol": string;
    "state": string;
    "channels": number;

    /**
     * TLS is whether the transport is encrypted, and Cipher names how. An
     * empty cipher on a TLS connection means the broker did not report one.
     */
    "tls": boolean;
    "cipher": string;

    /**
     * HeartbeatSec is what the two sides negotiated. Zero means heartbeats are
     * off, which is worth seeing: a connection with none can sit half-open
     * through a network partition and look healthy from both ends.
     */
    "heartbeatSec": number;
    "recvBytes": number;
    "sendBytes": number;
    "recvByteRate": number;
    "sendByteRate": number;

    /**
     * ConnectedAtMs is when the connection was established, in Unix
     * milliseconds, or 0 when the broker did not report it.
     */
    "connectedAtMs": number;

    /**
     * BlockedBy is why the broker last stopped this connection publishing -
     * a resource alarm, usually memory or disk. Empty means it was never
     * blocked.
     */
    "blockedBy": string;

    /** Creates a new ClientConnection instance. */
    constructor($$source: Partial<ClientConnection> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("clientName" in $$source)) {
            this["clientName"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("node" in $$source)) {
            this["node"] = "";
        }
        if (!("peerHost" in $$source)) {
            this["peerHost"] = "";
        }
        if (!("peerPort" in $$source)) {
            this["peerPort"] = 0;
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("channels" in $$source)) {
            this["channels"] = 0;
        }
        if (!("tls" in $$source)) {
            this["tls"] = false;
        }
        if (!("cipher" in $$source)) {
            this["cipher"] = "";
        }
        if (!("heartbeatSec" in $$source)) {
            this["heartbeatSec"] = 0;
        }
        if (!("recvBytes" in $$source)) {
            this["recvBytes"] = 0;
        }
        if (!("sendBytes" in $$source)) {
            this["sendBytes"] = 0;
        }
        if (!("recvByteRate" in $$source)) {
            this["recvByteRate"] = 0;
        }
        if (!("sendByteRate" in $$source)) {
            this["sendByteRate"] = 0;
        }
        if (!("connectedAtMs" in $$source)) {
            this["connectedAtMs"] = 0;
        }
        if (!("blockedBy" in $$source)) {
            this["blockedBy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClientConnection instance from a string or object.
     */
    static createFrom($$source: any = {}): ClientConnection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClientConnection($$parsedSource as Partial<ClientConnection>);
    }
}

/**
 * CloneOffsetRequest copies one subscription's read position onto another.
 * 
 * The usual reason is standing up a replacement consumer group without
 * replaying everything the old one already handled: the new group starts
 * exactly where the old one is.
 */
export class CloneOffsetRequest {
    "from": string;
    "to": string;

    /**
     * Destination narrows the copy to one topic. Empty copies every topic the
     * source group reads.
     */
    "destination": string;

    /**
     * FromOffline reads the source's positions from stored offsets rather than
     * from its live consumers. Required when the source group is already shut
     * down, which is the ordinary case during a migration.
     */
    "fromOffline": boolean;

    /** Creates a new CloneOffsetRequest instance. */
    constructor($$source: Partial<CloneOffsetRequest> = {}) {
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("fromOffline" in $$source)) {
            this["fromOffline"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloneOffsetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CloneOffsetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloneOffsetRequest($$parsedSource as Partial<CloneOffsetRequest>);
    }
}

/**
 * ClusterOverview is the aggregate the Cluster page header shows.
 */
export class ClusterOverview {
    "name": string;
    "totalNodes": number;
    "onlineNodes": number;

    /**
     * UnknownMetric when not enumerable
     */
    "destinations": number;
    "subscriptions": number;

    /**
     * percent; UnknownMetric when not reported
     */
    "avgDiskUsage": number;

    /** Creates a new ClusterOverview instance. */
    constructor($$source: Partial<ClusterOverview> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("totalNodes" in $$source)) {
            this["totalNodes"] = 0;
        }
        if (!("onlineNodes" in $$source)) {
            this["onlineNodes"] = 0;
        }
        if (!("destinations" in $$source)) {
            this["destinations"] = 0;
        }
        if (!("subscriptions" in $$source)) {
            this["subscriptions"] = 0;
        }
        if (!("avgDiskUsage" in $$source)) {
            this["avgDiskUsage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterOverview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterOverview($$parsedSource as Partial<ClusterOverview>);
    }
}

/**
 * ConnectionStatus is the connection status.
 */
export enum ConnectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusOnline = "online",
    StatusOffline = "offline",
};

/**
 * ConsumeThroughput is one destination's consume rates for one client.
 */
export class ConsumeThroughput {
    "destination": string;
    "pullLatencyMs": number;
    "pullRate": number;
    "consumeLatencyMs": number;
    "successRate": number;
    "failureRate": number;
    "failedMessages": number;

    /** Creates a new ConsumeThroughput instance. */
    constructor($$source: Partial<ConsumeThroughput> = {}) {
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("pullLatencyMs" in $$source)) {
            this["pullLatencyMs"] = 0;
        }
        if (!("pullRate" in $$source)) {
            this["pullRate"] = 0;
        }
        if (!("consumeLatencyMs" in $$source)) {
            this["consumeLatencyMs"] = 0;
        }
        if (!("successRate" in $$source)) {
            this["successRate"] = 0;
        }
        if (!("failureRate" in $$source)) {
            this["failureRate"] = 0;
        }
        if (!("failedMessages" in $$source)) {
            this["failedMessages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumeThroughput instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsumeThroughput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsumeThroughput($$parsedSource as Partial<ConsumeThroughput>);
    }
}

/**
 * DeadLetterQueue is a queue that receives what other queues could not keep.
 * 
 * It is not the shape DeadLetterReader describes, and that is the point.
 * RocketMQ gives every consumer group a dead-letter topic of its own, named
 * after it, so a group name is enough to find one. RabbitMQ has no such thing:
 * a queue is declared with a dead-letter exchange, that exchange routes like
 * any other, and whatever it routes to becomes a dead-letter queue by
 * convention rather than by declaration. Finding one means walking the
 * topology backwards.
 */
export class DeadLetterQueue {
    "namespace": string;

    /**
     * Name is the queue dead letters land in. It has no special status on the
     * broker - it is an ordinary queue that something else points at.
     */
    "name": string;
    "depth": number;

    /**
     * Consumers is how many are draining it. A dead-letter queue with a
     * consumer is a retry pipeline; one without is a backlog nobody is
     * looking at, which is the case worth surfacing.
     */
    "consumers": number;

    /**
     * Sources are the queues whose dead-letter exchange routes here, and the
     * reason this queue matters. A dead-letter queue with no sources is one
     * whose producers were deleted or reconfigured, and it will never receive
     * anything again.
     */
    "sources": (DeadLetterSource | null)[];

    /** Creates a new DeadLetterQueue instance. */
    constructor($$source: Partial<DeadLetterQueue> = {}) {
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("depth" in $$source)) {
            this["depth"] = 0;
        }
        if (!("consumers" in $$source)) {
            this["consumers"] = 0;
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeadLetterQueue instance from a string or object.
     */
    static createFrom($$source: any = {}): DeadLetterQueue {
        const $$createField4_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField4_0($$parsedSource["sources"]);
        }
        return new DeadLetterQueue($$parsedSource as Partial<DeadLetterQueue>);
    }
}

/**
 * DeadLetterSource is one queue that dead-letters into another.
 */
export class DeadLetterSource {
    "queue": string;

    /**
     * Exchange is what the source queue was declared to dead-letter through.
     */
    "exchange": string;

    /**
     * RoutingKey is the key the message is re-published with. Empty means the
     * message keeps its original routing key, which is the default and changes
     * where it lands.
     */
    "routingKey": string;

    /** Creates a new DeadLetterSource instance. */
    constructor($$source: Partial<DeadLetterSource> = {}) {
        if (!("queue" in $$source)) {
            this["queue"] = "";
        }
        if (!("exchange" in $$source)) {
            this["exchange"] = "";
        }
        if (!("routingKey" in $$source)) {
            this["routingKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeadLetterSource instance from a string or object.
     */
    static createFrom($$source: any = {}): DeadLetterSource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeadLetterSource($$parsedSource as Partial<DeadLetterSource>);
    }
}

/**
 * DeprecatedFeature is something this cluster still allows that a later
 * release will not.
 * 
 * The list of what is deprecated is background; the list of what is deprecated
 * *and in use here* is a work item, which is why the two are reported
 * separately rather than as one list with a flag.
 */
export class DeprecatedFeature {
    "name": string;
    "description": string;

    /**
     * Phase is how far along the removal is: permitted by default, denied by
     * default, disconnected, or removed.
     */
    "phase": string;
    "providedBy": string;
    "docUrl": string;

    /**
     * InUse is set when the broker reports this feature is actually being
     * used on this cluster, which turns it from background into a work item.
     */
    "inUse": boolean;

    /** Creates a new DeprecatedFeature instance. */
    constructor($$source: Partial<DeprecatedFeature> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("providedBy" in $$source)) {
            this["providedBy"] = "";
        }
        if (!("docUrl" in $$source)) {
            this["docUrl"] = "";
        }
        if (!("inUse" in $$source)) {
            this["inUse"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeprecatedFeature instance from a string or object.
     */
    static createFrom($$source: any = {}): DeprecatedFeature {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeprecatedFeature($$parsedSource as Partial<DeprecatedFeature>);
    }
}

/**
 * Destination is a topic, queue or stream as the canonical pages see it.
 * 
 * Attributes carries whatever the family has and the canonical model does not:
 * RocketMQ permissions and queue counts, RabbitMQ durability and queue type,
 * Kafka replication factor. Its keys are a contract between one driver's Go
 * side and that driver's frontend module, not part of the shared vocabulary.
 */
export class Destination {
    /**
     * list key for the renderer, not broker data
     */
    "id": number;
    "ref": DestinationRef;

    /**
     * UnknownMetric where the family has none
     */
    "partitions": number;

    /**
     * consumer groups, subscriptions or consumers
     */
    "subscribers": number;

    /**
     * messages held; UnknownMetric when not reported
     */
    "depth": number;

    /**
     * messages per second in
     */
    "rateIn": number;

    /**
     * messages per second out
     */
    "rateOut": number;
    "lastUpdated": string;
    "attributes": { [_ in string]?: string };

    /** Creates a new Destination instance. */
    constructor($$source: Partial<Destination> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ref" in $$source)) {
            this["ref"] = (new DestinationRef());
        }
        if (!("partitions" in $$source)) {
            this["partitions"] = 0;
        }
        if (!("subscribers" in $$source)) {
            this["subscribers"] = 0;
        }
        if (!("depth" in $$source)) {
            this["depth"] = 0;
        }
        if (!("rateIn" in $$source)) {
            this["rateIn"] = 0;
        }
        if (!("rateOut" in $$source)) {
            this["rateOut"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = "";
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Destination instance from a string or object.
     */
    static createFrom($$source: any = {}): Destination {
        const $$createField1_0 = $$createType22;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField1_0($$parsedSource["ref"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField8_0($$parsedSource["attributes"]);
        }
        return new Destination($$parsedSource as Partial<Destination>);
    }
}

/**
 * DestinationRef identifies a destination across families.
 * 
 * Flat families leave Namespace empty; Pulsar fills tenant/namespace and
 * RabbitMQ fills the vhost. It is a struct rather than a string because
 * joining and re-splitting those parts loses information for any name that
 * contains the separator.
 */
export class DestinationRef {
    "namespace": string;
    "name": string;

    /** Creates a new DestinationRef instance. */
    constructor($$source: Partial<DestinationRef> = {}) {
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DestinationRef instance from a string or object.
     */
    static createFrom($$source: any = {}): DestinationRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DestinationRef($$parsedSource as Partial<DestinationRef>);
    }
}

/**
 * DriverDescriptor is what a family can do before any connection is open.
 * 
 * Display strings are deliberately absent: the renderer resolves them from
 * the i18n bundle under mq.<kind>.*, so translations stay where translations
 * live.
 */
export class DriverDescriptor {
    "kind": MQKind;
    "defaultPort": string;
    "form": FormField[];

    /**
     * MaxCapabilities is the best case for the family. A live connection can
     * only narrow it, never widen it, and the driver conformance test asserts
     * every entry is backed by an implemented interface.
     */
    "maxCapabilities": Capability[];

    /** Creates a new DriverDescriptor instance. */
    constructor($$source: Partial<DriverDescriptor> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = MQKind.$zero;
        }
        if (!("defaultPort" in $$source)) {
            this["defaultPort"] = "";
        }
        if (!("form" in $$source)) {
            this["form"] = [];
        }
        if (!("maxCapabilities" in $$source)) {
            this["maxCapabilities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DriverDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): DriverDescriptor {
        const $$createField2_0 = $$createType24;
        const $$createField3_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("form" in $$parsedSource) {
            $$parsedSource["form"] = $$createField2_0($$parsedSource["form"]);
        }
        if ("maxCapabilities" in $$parsedSource) {
            $$parsedSource["maxCapabilities"] = $$createField3_0($$parsedSource["maxCapabilities"]);
        }
        return new DriverDescriptor($$parsedSource as Partial<DriverDescriptor>);
    }
}

/**
 * FeatureFlag is a behaviour change that has to be enabled before the cluster
 * can use it, and cannot be turned off again once it is.
 * 
 * It matters on a page about nodes because a flag that is not enabled
 * everywhere blocks a rolling upgrade: the cluster cannot move to a version
 * that requires it until every node agrees.
 */
export class FeatureFlag {
    "name": string;
    "description": string;

    /**
     * State is the broker's own word - "enabled", "disabled", "unavailable".
     */
    "state": string;
    "stability": string;
    "providedBy": string;
    "docUrl": string;

    /** Creates a new FeatureFlag instance. */
    constructor($$source: Partial<FeatureFlag> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("stability" in $$source)) {
            this["stability"] = "";
        }
        if (!("providedBy" in $$source)) {
            this["providedBy"] = "";
        }
        if (!("docUrl" in $$source)) {
            this["docUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureFlag instance from a string or object.
     */
    static createFrom($$source: any = {}): FeatureFlag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureFlag($$parsedSource as Partial<FeatureFlag>);
    }
}

/**
 * FieldCond hides a field unless another field holds one of Equals.
 */
export class FieldCond {
    "field": string;
    "equals": string[];

    /** Creates a new FieldCond instance. */
    constructor($$source: Partial<FieldCond> = {}) {
        if (!("field" in $$source)) {
            this["field"] = "";
        }
        if (!("equals" in $$source)) {
            this["equals"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FieldCond instance from a string or object.
     */
    static createFrom($$source: any = {}): FieldCond {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("equals" in $$parsedSource) {
            $$parsedSource["equals"] = $$createField1_0($$parsedSource["equals"]);
        }
        return new FieldCond($$parsedSource as Partial<FieldCond>);
    }
}

/**
 * FieldTarget says which part of a ConnectionProfile a field writes into.
 * Secrets are encrypted at rest and never serialised back to the renderer.
 */
export enum FieldTarget {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TargetEndpoints = "endpoints",
    TargetOption = "option",
    TargetSecret = "secret",
    TargetAuth = "auth",
};

/**
 * FieldType is how the renderer draws one connection-form field.
 */
export enum FieldType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FieldText = "text",
    FieldPassword = "password",
    FieldNumber = "number",
    FieldSelect = "select",
    FieldSwitch = "switch",
    FieldEndpointList = "endpoint-list",
};

/**
 * FormField is one row of a driver's connection form.
 */
export class FormField {
    "key": string;
    "target": FieldTarget;
    "type": FieldType;

    /**
     * i18n key, never a literal
     */
    "labelKey": string;
    "placeholder": string;
    "default": string;
    "required": boolean;
    "visibleWhen": FieldCond | null;
    "options": FormOption[];

    /**
     * Validate names a validator the renderer already implements, such as
     * "host-port" or "url". Shipping a regex across the bridge would move
     * validation logic out of review and into data.
     */
    "validate": string;

    /** Creates a new FormField instance. */
    constructor($$source: Partial<FormField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = FieldTarget.$zero;
        }
        if (!("type" in $$source)) {
            this["type"] = FieldType.$zero;
        }
        if (!("labelKey" in $$source)) {
            this["labelKey"] = "";
        }
        if (!("placeholder" in $$source)) {
            this["placeholder"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }
        if (!("required" in $$source)) {
            this["required"] = false;
        }
        if (!("visibleWhen" in $$source)) {
            this["visibleWhen"] = null;
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }
        if (!("validate" in $$source)) {
            this["validate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormField instance from a string or object.
     */
    static createFrom($$source: any = {}): FormField {
        const $$createField7_0 = $$createType26;
        const $$createField8_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("visibleWhen" in $$parsedSource) {
            $$parsedSource["visibleWhen"] = $$createField7_0($$parsedSource["visibleWhen"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField8_0($$parsedSource["options"]);
        }
        return new FormField($$parsedSource as Partial<FormField>);
    }
}

/**
 * FormOption is one choice in a select field.
 */
export class FormOption {
    "value": string;
    "labelKey": string;

    /** Creates a new FormOption instance. */
    constructor($$source: Partial<FormOption> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("labelKey" in $$source)) {
            this["labelKey"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormOption instance from a string or object.
     */
    static createFrom($$source: any = {}): FormOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FormOption($$parsedSource as Partial<FormOption>);
    }
}

/**
 * HealthCheck is one question the broker answers about itself.
 * 
 * RabbitMQ's health endpoints are deliberately narrow: each asks one thing and
 * answers ok or not, with a sentence when not. Collapsing them into a single
 * "healthy" flag would throw away the only part an operator can act on, which
 * is which check failed and what it said.
 */
export class HealthCheck {
    /**
     * ID is a stable key the UI labels from, not a sentence.
     */
    "id": string;

    /**
     * Passed is false when the check failed and unknown when the broker could
     * not run it at all, which is why Unavailable exists rather than a third
     * value here.
     */
    "passed": boolean;

    /**
     * Unavailable means this endpoint is not on this broker - an older
     * version, or a check that needs a plugin. It reads differently from a
     * failure and must not be shown as one.
     */
    "unavailable": boolean;
    "reason": string;

    /** Creates a new HealthCheck instance. */
    constructor($$source: Partial<HealthCheck> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("passed" in $$source)) {
            this["passed"] = false;
        }
        if (!("unavailable" in $$source)) {
            this["unavailable"] = false;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthCheck instance from a string or object.
     */
    static createFrom($$source: any = {}): HealthCheck {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthCheck($$parsedSource as Partial<HealthCheck>);
    }
}

/**
 * MQKind identifies a broker family.
 * 
 * The values are the key for the driver registry, the per-kind settings
 * defaults and the `kind` field in connections.json, so they are part of the
 * on-disk format and must not be renamed.
 */
export enum MQKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindRocketMQ = "rocketmq",
    KindKafka = "kafka",
    KindRabbitMQ = "rabbitmq",
    KindPulsar = "pulsar",
    KindActiveMQ = "activemq",
    KindRedisStream = "redis-stream",
    KindNATS = "nats",
    KindNSQ = "nsq",
    KindMQTT = "mqtt",

    /**
     * Hosted families authenticate through Options and Secrets rather than
     * Endpoints: there is no broker address to dial, only a region and a
     * credential.
     */
    KindSQS = "sqs",
    KindGooglePubSub = "google-pubsub",
    KindAzureServiceBus = "azure-servicebus",
    KindKinesis = "kinesis",
    KindIBMMQ = "ibmmq",
    KindSolace = "solace",
};

/**
 * MessageItem holds message information.
 */
export class MessageItem {
    /**
     * Message sequence number
     */
    "id": number;

    /**
     * Cluster name
     */
    "cluster": string;

    /**
     * Topic name
     */
    "topic": string;

    /**
     * Message ID
     */
    "messageId": string;

    /**
     * Message tags
     */
    "tags": string;

    /**
     * Message keys
     */
    "keys": string;

    /**
     * Queue ID
     */
    "queueId": number;

    /**
     * Queue offset
     */
    "queueOffset": number;

    /**
     * Store host
     */
    "storeHost": string;

    /**
     * Born host
     */
    "bornHost": string;

    /**
     * Store time
     */
    "storeTime": string;

    /**
     * Store timestamp
     */
    "storeTimestamp": number;

    /**
     * Message status
     */
    "status": MessageStatus;

    /**
     * Retry times
     */
    "retryTimes": number;

    /**
     * Message body
     */
    "body": string;

    /**
     * Message properties
     */
    "properties": { [_ in string]?: string };

    /** Creates a new MessageItem instance. */
    constructor($$source: Partial<MessageItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = "";
        }
        if (!("keys" in $$source)) {
            this["keys"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = 0;
        }
        if (!("queueOffset" in $$source)) {
            this["queueOffset"] = 0;
        }
        if (!("storeHost" in $$source)) {
            this["storeHost"] = "";
        }
        if (!("bornHost" in $$source)) {
            this["bornHost"] = "";
        }
        if (!("storeTime" in $$source)) {
            this["storeTime"] = "";
        }
        if (!("storeTimestamp" in $$source)) {
            this["storeTimestamp"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = MessageStatus.$zero;
        }
        if (!("retryTimes" in $$source)) {
            this["retryTimes"] = 0;
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageItem {
        const $$createField15_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField15_0($$parsedSource["properties"]);
        }
        return new MessageItem($$parsedSource as Partial<MessageItem>);
    }
}

/**
 * MessageStatus is the message status.
 */
export enum MessageStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MsgNormal = "normal",
    MsgRetry = "retry",
    MsgDLQ = "dlq",
};

/**
 * MessageTrackItem holds message track information.
 */
export class MessageTrackItem {
    /**
     * Consumer group
     */
    "consumerGroup": string;

    /**
     * Track type: CONSUMED / NOT_CONSUME_YET / CONSUMED_BUT_FILTERED / UNKNOWN
     */
    "trackType": string;

    /**
     * Consume status description
     */
    "consumeStatus": string;

    /**
     * Exception description
     */
    "exceptionDesc": string;

    /** Creates a new MessageTrackItem instance. */
    constructor($$source: Partial<MessageTrackItem> = {}) {
        if (!("consumerGroup" in $$source)) {
            this["consumerGroup"] = "";
        }
        if (!("trackType" in $$source)) {
            this["trackType"] = "";
        }
        if (!("consumeStatus" in $$source)) {
            this["consumeStatus"] = "";
        }
        if (!("exceptionDesc" in $$source)) {
            this["exceptionDesc"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageTrackItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageTrackItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageTrackItem($$parsedSource as Partial<MessageTrackItem>);
    }
}

/**
 * Namespace is one isolated world inside a broker.
 * 
 * A RabbitMQ virtual host is not a label: queues, exchanges, bindings, policies
 * and permissions all live inside one and nothing crosses between them, so two
 * vhosts can hold a queue of the same name that have nothing to do with each
 * other. That is why it is a page rather than a filter.
 * 
 * The word is Namespace because the canonical vocabulary already uses it - a
 * destination's Ref carries one - and RabbitMQ is the only family so far whose
 * namespaces are objects you can create.
 */
export class Namespace {
    "name": string;
    "description": string;

    /**
     * Tags are free labels the operator sets, not the broker.
     */
    "tags": string[];

    /**
     * DefaultQueueType is what a queue declared here without a type becomes.
     * Setting it to quorum is how a cluster stops accumulating classic queues
     * by accident.
     */
    "defaultQueueType": string;

    /**
     * Tracing writes every message through this vhost to a log exchange. It is
     * expensive and is meant to be switched on for minutes, not left on.
     */
    "tracing": boolean;

    /**
     * Messages is what its queues are collectively holding, split the same way
     * a queue's depth is.
     */
    "messages": number;
    "ready": number;
    "unacknowledged": number;

    /**
     * Limits caps the vhost as a whole - max-connections, max-queues. Absent
     * means uncapped, which is the default and is worth distinguishing from a
     * limit of zero.
     */
    "limits": { [_ in string]?: number };

    /** Creates a new Namespace instance. */
    constructor($$source: Partial<Namespace> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("defaultQueueType" in $$source)) {
            this["defaultQueueType"] = "";
        }
        if (!("tracing" in $$source)) {
            this["tracing"] = false;
        }
        if (!("messages" in $$source)) {
            this["messages"] = 0;
        }
        if (!("ready" in $$source)) {
            this["ready"] = 0;
        }
        if (!("unacknowledged" in $$source)) {
            this["unacknowledged"] = 0;
        }
        if (!("limits" in $$source)) {
            this["limits"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Namespace instance from a string or object.
     */
    static createFrom($$source: any = {}): Namespace {
        const $$createField2_0 = $$createType0;
        const $$createField8_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        if ("limits" in $$parsedSource) {
            $$parsedSource["limits"] = $$createField8_0($$parsedSource["limits"]);
        }
        return new Namespace($$parsedSource as Partial<Namespace>);
    }
}

/**
 * Node is one broker, RabbitMQ node or Kafka broker as the canonical Cluster
 * page sees it.
 * 
 * It is deliberately thinner than BrokerNode: the TPS history arrays there are
 * filled by the cluster service from local samples, not by any broker, so they
 * stay out of what a driver has to produce.
 */
export class Node {
    /**
     * list key for the renderer, not broker data
     */
    "id": number;
    "name": string;
    "address": string;

    /**
     * grouping label; empty where the family has none
     */
    "cluster": string;
    "version": string;
    "status": NodeStatus;

    /**
     * messages per second in
     */
    "rateIn": number;

    /**
     * messages per second out
     */
    "rateOut": number;

    /**
     * percent; UnknownMetric when not reported
     */
    "diskUsage": number;
    "lastSeen": string;

    /**
     * TPS history is sampled locally by the collector, not reported by any
     * broker, which is why a driver never fills these.
     * Unix seconds
     */
    "tpsHistoryTimestamps": number[];
    "tpsInHistory": number[];
    "tpsOutHistory": number[];

    /**
     * Replicas is how far each follower of this node trails it, where the
     * family replicates. Empty on a follower, and on a leader with none.
     * 
     * Canonical rather than an attribute because every replicating family has
     * the question - RocketMQ slaves, Kafka ISR, RabbitMQ quorum members - and
     * "is a replica falling behind" is the one thing a cluster page is opened
     * to answer during an incident.
     * 
     * Filled only by NodeDetail: it costs a request per node, which a list
     * should not pay.
     */
    "replicas": ReplicaStatus[];

    /**
     * Attributes carries family-specific detail the canonical page renders
     * through the driver's own column set: RocketMQ master/slave role and
     * CommitLog usage, Kafka controller and ISR, RabbitMQ disc/ram node type.
     */
    "attributes": { [_ in string]?: string };

    /** Creates a new Node instance. */
    constructor($$source: Partial<Node> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = NodeStatus.$zero;
        }
        if (!("rateIn" in $$source)) {
            this["rateIn"] = 0;
        }
        if (!("rateOut" in $$source)) {
            this["rateOut"] = 0;
        }
        if (!("diskUsage" in $$source)) {
            this["diskUsage"] = 0;
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = "";
        }
        if (!("tpsHistoryTimestamps" in $$source)) {
            this["tpsHistoryTimestamps"] = [];
        }
        if (!("tpsInHistory" in $$source)) {
            this["tpsInHistory"] = [];
        }
        if (!("tpsOutHistory" in $$source)) {
            this["tpsOutHistory"] = [];
        }
        if (!("replicas" in $$source)) {
            this["replicas"] = [];
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     */
    static createFrom($$source: any = {}): Node {
        const $$createField10_0 = $$createType30;
        const $$createField11_0 = $$createType31;
        const $$createField12_0 = $$createType31;
        const $$createField13_0 = $$createType33;
        const $$createField14_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tpsHistoryTimestamps" in $$parsedSource) {
            $$parsedSource["tpsHistoryTimestamps"] = $$createField10_0($$parsedSource["tpsHistoryTimestamps"]);
        }
        if ("tpsInHistory" in $$parsedSource) {
            $$parsedSource["tpsInHistory"] = $$createField11_0($$parsedSource["tpsInHistory"]);
        }
        if ("tpsOutHistory" in $$parsedSource) {
            $$parsedSource["tpsOutHistory"] = $$createField12_0($$parsedSource["tpsOutHistory"]);
        }
        if ("replicas" in $$parsedSource) {
            $$parsedSource["replicas"] = $$createField13_0($$parsedSource["replicas"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField14_0($$parsedSource["attributes"]);
        }
        return new Node($$parsedSource as Partial<Node>);
    }
}

/**
 * NodeStatus is the node status.
 */
export enum NodeStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NodeOnline = "online",
    NodeWarning = "warning",
    NodeOffline = "offline",

    /**
     * NodeUnknown is a node whose health the family does not report. A
     * RocketMQ name server is one: the admin protocol names the addresses the
     * client dials and says nothing about whether each of them answers, and
     * calling that "online" would be inventing a check nobody ran.
     */
    NodeUnknown = "unknown",
};

/**
 * ProducerClient is one connected publisher.
 * 
 * There is no list of publishers the way there is of subscriptions: a broker
 * tracks connections per producer group and offers no way to enumerate the
 * groups, so a caller has to name one. That is why this is not a Producer
 * type with a Ref - there is nothing to list, only something to look up.
 */
export class ProducerClient {
    "clientId": string;
    "address": string;
    "language": string;
    "version": string;

    /** Creates a new ProducerClient instance. */
    constructor($$source: Partial<ProducerClient> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProducerClient instance from a string or object.
     */
    static createFrom($$source: any = {}): ProducerClient {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProducerClient($$parsedSource as Partial<ProducerClient>);
    }
}

/**
 * PublishResult is what the broker said about the send.
 * 
 * Confirmed and Routed are different facts and the difference is the whole
 * point of this type. A confirm means the broker took responsibility for the
 * message; routing means something was bound to receive it. An unroutable
 * publish is confirmed and then dropped, so a page reporting only the confirm
 * would call that a success.
 */
export class PublishResult {
    /**
     * Sent is how many the broker confirmed.
     */
    "sent": number;

    /**
     * Unroutable is how many it handed back because nothing was bound. They
     * were not delivered anywhere, and on a mandatory publish that is the only
     * way to find out.
     */
    "unroutable": number;

    /**
     * Reason is the broker's own words for the last message handed back.
     */
    "reason": string;

    /** Creates a new PublishResult instance. */
    constructor($$source: Partial<PublishResult> = {}) {
        if (!("sent" in $$source)) {
            this["sent"] = 0;
        }
        if (!("unroutable" in $$source)) {
            this["unroutable"] = 0;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublishResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PublishResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublishResult($$parsedSource as Partial<PublishResult>);
    }
}

/**
 * QueueAssignment is one queue a consumer holds, and how far behind it is.
 */
export class QueueAssignment {
    "destination": string;

    /**
     * the broker holding this queue
     */
    "node": string;
    "queueId": number;

    /**
     * Pending is what this client has buffered but not yet finished, which is
     * not the same as the group's backlog on the broker.
     */
    "pending": number;
    "pendingBytes": number;
    "lastPull": string;
    "lastConsume": string;

    /**
     * Locked matters only where a family locks a queue to one consumer for
     * ordered delivery; Dropped means the client is releasing it in a rebalance.
     */
    "locked": boolean;
    "dropped": boolean;

    /** Creates a new QueueAssignment instance. */
    constructor($$source: Partial<QueueAssignment> = {}) {
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("node" in $$source)) {
            this["node"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = 0;
        }
        if (!("pending" in $$source)) {
            this["pending"] = 0;
        }
        if (!("pendingBytes" in $$source)) {
            this["pendingBytes"] = 0;
        }
        if (!("lastPull" in $$source)) {
            this["lastPull"] = "";
        }
        if (!("lastConsume" in $$source)) {
            this["lastConsume"] = "";
        }
        if (!("locked" in $$source)) {
            this["locked"] = false;
        }
        if (!("dropped" in $$source)) {
            this["dropped"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueAssignment instance from a string or object.
     */
    static createFrom($$source: any = {}): QueueAssignment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueAssignment($$parsedSource as Partial<QueueAssignment>);
    }
}

/**
 * QueuePosition is one partition's place in a tail.
 */
export class QueuePosition {
    /**
     * the broker holding it
     */
    "node": string;
    "queueId": number;
    "offset": number;

    /** Creates a new QueuePosition instance. */
    constructor($$source: Partial<QueuePosition> = {}) {
        if (!("node" in $$source)) {
            this["node"] = "";
        }
        if (!("queueId" in $$source)) {
            this["queueId"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueuePosition instance from a string or object.
     */
    static createFrom($$source: any = {}): QueuePosition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueuePosition($$parsedSource as Partial<QueuePosition>);
    }
}

/**
 * ReplayResult is what that consumer's own handler returned.
 * 
 * This is not a delivery receipt: the broker forwarded the message and the
 * client ran its listener, so a failure here is the application's, reported
 * back verbatim in Remark.
 */
export class ReplayResult {
    "result": string;
    "remark": string;
    "spentMs": number;

    /**
     * Ordered and AutoCommit describe how the client was configured to consume,
     * which changes what a failure means: an ordered consumer blocks its queue
     * on one it cannot handle.
     */
    "ordered": boolean;
    "autoCommit": boolean;

    /** Creates a new ReplayResult instance. */
    constructor($$source: Partial<ReplayResult> = {}) {
        if (!("result" in $$source)) {
            this["result"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("spentMs" in $$source)) {
            this["spentMs"] = 0;
        }
        if (!("ordered" in $$source)) {
            this["ordered"] = false;
        }
        if (!("autoCommit" in $$source)) {
            this["autoCommit"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplayResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplayResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplayResult($$parsedSource as Partial<ReplayResult>);
    }
}

/**
 * ReplicaStatus is one follower's replication state.
 */
export class ReplicaStatus {
    "address": string;

    /**
     * BehindBytes is how far this replica trails the leader's log. Zero means
     * caught up; UnknownMetric means the family reports no such figure.
     */
    "behindBytes": number;

    /**
     * InSync is the family's own verdict, which is not simply BehindBytes == 0:
     * a replica can be a little behind and still count as in sync.
     */
    "inSync": boolean;

    /** Creates a new ReplicaStatus instance. */
    constructor($$source: Partial<ReplicaStatus> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("behindBytes" in $$source)) {
            this["behindBytes"] = 0;
        }
        if (!("inSync" in $$source)) {
            this["inSync"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplicaStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplicaStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplicaStatus($$parsedSource as Partial<ReplicaStatus>);
    }
}

/**
 * ResetOffsetRequest is a request to reset offsets.
 */
export class ResetOffsetRequest {
    /**
     * Consumer group name
     */
    "group": string;

    /**
     * Topic name
     */
    "topic": string;

    /**
     * Timestamp (milliseconds)
     */
    "timestamp": number;

    /**
     * Whether to force reset
     */
    "force": boolean;

    /** Creates a new ResetOffsetRequest instance. */
    constructor($$source: Partial<ResetOffsetRequest> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("force" in $$source)) {
            this["force"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetOffsetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetOffsetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetOffsetRequest($$parsedSource as Partial<ResetOffsetRequest>);
    }
}

/**
 * ResourceAlarm is a node that has crossed a memory or disk watermark.
 * 
 * While one is in effect the broker refuses publishes from every connection,
 * which makes it the first thing worth showing on a cluster page.
 */
export class ResourceAlarm {
    "node": string;
    "resource": string;

    /** Creates a new ResourceAlarm instance. */
    constructor($$source: Partial<ResourceAlarm> = {}) {
        if (!("node" in $$source)) {
            this["node"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceAlarm instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceAlarm {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceAlarm($$parsedSource as Partial<ResourceAlarm>);
    }
}

/**
 * Subscription is a consumer group, a Pulsar subscription or a RabbitMQ queue
 * consumer, as the canonical pages see it.
 * 
 * Backlog is deliberately not called lag: RocketMQ and Kafka compute it from
 * offsets, RabbitMQ reads ready plus unacknowledged, and Redis Stream reads
 * XPENDING. The number means "messages still owed to this subscriber" in all
 * three, but only the first two have an offset behind it — which is why
 * resetting position is a separate capability.
 */
export class Subscription {
    /**
     * list key for the renderer, not broker data
     */
    "id": number;
    "ref": SubscriptionRef;
    "status": SubscriptionStatus;

    /**
     * connected consumers
     */
    "members": number;

    /**
     * how many it reads from
     */
    "destinations": number;

    /**
     * UnknownMetric when not reported
     */
    "backlog": number;

    /**
     * messages per second consumed
     */
    "rateOut": number;
    "lastUpdated": string;
    "attributes": { [_ in string]?: string };

    /** Creates a new Subscription instance. */
    constructor($$source: Partial<Subscription> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("ref" in $$source)) {
            this["ref"] = (new SubscriptionRef());
        }
        if (!("status" in $$source)) {
            this["status"] = SubscriptionStatus.$zero;
        }
        if (!("members" in $$source)) {
            this["members"] = 0;
        }
        if (!("destinations" in $$source)) {
            this["destinations"] = 0;
        }
        if (!("backlog" in $$source)) {
            this["backlog"] = 0;
        }
        if (!("rateOut" in $$source)) {
            this["rateOut"] = 0;
        }
        if (!("lastUpdated" in $$source)) {
            this["lastUpdated"] = "";
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Subscription instance from a string or object.
     */
    static createFrom($$source: any = {}): Subscription {
        const $$createField1_0 = $$createType34;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ref" in $$parsedSource) {
            $$parsedSource["ref"] = $$createField1_0($$parsedSource["ref"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField8_0($$parsedSource["attributes"]);
        }
        return new Subscription($$parsedSource as Partial<Subscription>);
    }
}

/**
 * SubscriptionClient is what one connected consumer is actually doing.
 * 
 * It is separate from the client list a Subscription carries because the two
 * answer different questions and cost different things. The list says who is
 * connected, and comes back with the group. This is a round trip to that one
 * client, so it is fetched when someone asks about it.
 */
export class SubscriptionClient {
    "clientId": string;

    /**
     * Assignments is which queues this client currently holds. It is the
     * answer to "why is one consumer behind and the others idle", which a
     * group-level backlog cannot give.
     */
    "assignments": QueueAssignment[];

    /**
     * Throughput is per destination, because a client reading two topics can
     * be healthy on one and stalled on the other.
     */
    "throughput": ConsumeThroughput[];

    /**
     * Properties is what the client reports about itself - version, consume
     * mode, thread counts. Free-form because every family names them
     * differently and none of it is worth a canonical field.
     */
    "properties": { [_ in string]?: string };

    /** Creates a new SubscriptionClient instance. */
    constructor($$source: Partial<SubscriptionClient> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("assignments" in $$source)) {
            this["assignments"] = [];
        }
        if (!("throughput" in $$source)) {
            this["throughput"] = [];
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubscriptionClient instance from a string or object.
     */
    static createFrom($$source: any = {}): SubscriptionClient {
        const $$createField1_0 = $$createType36;
        const $$createField2_0 = $$createType38;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assignments" in $$parsedSource) {
            $$parsedSource["assignments"] = $$createField1_0($$parsedSource["assignments"]);
        }
        if ("throughput" in $$parsedSource) {
            $$parsedSource["throughput"] = $$createField2_0($$parsedSource["throughput"]);
        }
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField3_0($$parsedSource["properties"]);
        }
        return new SubscriptionClient($$parsedSource as Partial<SubscriptionClient>);
    }
}

/**
 * SubscriptionRef identifies a consumer group, subscription or queue consumer.
 */
export class SubscriptionRef {
    "namespace": string;
    "name": string;

    /** Creates a new SubscriptionRef instance. */
    constructor($$source: Partial<SubscriptionRef> = {}) {
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubscriptionRef instance from a string or object.
     */
    static createFrom($$source: any = {}): SubscriptionRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubscriptionRef($$parsedSource as Partial<SubscriptionRef>);
    }
}

/**
 * SubscriptionStatus is the health of a subscription.
 */
export enum SubscriptionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SubscriptionOnline = "online",
    SubscriptionWarning = "warning",
    SubscriptionOffline = "offline",
};

/**
 * TailBatch is one poll's worth of a tail.
 */
export class TailBatch {
    /**
     * Messages are oldest first, which is the order a tail appends in.
     */
    "messages": (MessageItem | null)[];

    /**
     * Cursor is what to pass next time. It advances even when no message came
     * back, because a partition can move on without this tail matching any.
     */
    "cursor": TailCursor;

    /**
     * Dropped counts messages that aged out of the log between two polls -
     * a tail slower than the retention it is watching. Reporting it is the
     * difference between a quiet tail and one that is silently losing.
     */
    "dropped": number;

    /** Creates a new TailBatch instance. */
    constructor($$source: Partial<TailBatch> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("cursor" in $$source)) {
            this["cursor"] = (new TailCursor());
        }
        if (!("dropped" in $$source)) {
            this["dropped"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TailBatch instance from a string or object.
     */
    static createFrom($$source: any = {}): TailBatch {
        const $$createField0_0 = $$createType41;
        const $$createField1_0 = $$createType42;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        if ("cursor" in $$parsedSource) {
            $$parsedSource["cursor"] = $$createField1_0($$parsedSource["cursor"]);
        }
        return new TailBatch($$parsedSource as Partial<TailBatch>);
    }
}

/**
 * TailCursor is where a tail has read to, per partition.
 * 
 * An empty cursor means "start at the end": a tail opens on what arrives next
 * rather than replaying what is already stored, which is what the message
 * query is for.
 */
export class TailCursor {
    "positions": QueuePosition[];

    /** Creates a new TailCursor instance. */
    constructor($$source: Partial<TailCursor> = {}) {
        if (!("positions" in $$source)) {
            this["positions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TailCursor instance from a string or object.
     */
    static createFrom($$source: any = {}): TailCursor {
        const $$createField0_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("positions" in $$parsedSource) {
            $$parsedSource["positions"] = $$createField0_0($$parsedSource["positions"]);
        }
        return new TailCursor($$parsedSource as Partial<TailCursor>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AccessPolicy.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = BrokerRates.createFrom;
const $$createType5 = HealthCheck.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ResourceAlarm.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = FeatureFlag.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = DeprecatedFeature.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $Create.Array($Create.Any);
const $$createType18 = $Create.Map($Create.Any, $Create.Any);
const $$createType19 = DeadLetterSource.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = DestinationRef.createFrom;
const $$createType23 = FormField.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = FieldCond.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = FormOption.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $Create.Map($Create.Any, $Create.Any);
const $$createType30 = $Create.Array($Create.Any);
const $$createType31 = $Create.Array($Create.Any);
const $$createType32 = ReplicaStatus.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = SubscriptionRef.createFrom;
const $$createType35 = QueueAssignment.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = ConsumeThroughput.createFrom;
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = MessageItem.createFrom;
const $$createType40 = $Create.Nullable($$createType39);
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = TailCursor.createFrom;
const $$createType43 = QueuePosition.createFrom;
const $$createType44 = $Create.Array($$createType43);
