// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as audit$0 from "../audit/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../provider/models.js";

/**
 * Ask is a question waiting on a person, or one they answered.
 */
export class Ask {
    "id": string;
    "kind": string;

    /**
     * Question is a confirmation's text, word for word what the audit log
     * keeps.
     */
    "question"?: string;

    /**
     * Caveat is what the connection says survives a write succeeding, for an
     * approval, in the application's language.
     */
    "caveat"?: string;

    /** Creates a new Ask instance. */
    constructor($$source: Partial<Ask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Ask instance from a string or object.
     */
    static createFrom($$source: any = {}): Ask {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Ask($$parsedSource as Partial<Ask>);
    }
}

/**
 * Context is what the window knew about where the person was when they asked.
 */
export class Context {
    "connection"?: number;
    "page"?: string;
    "namespace"?: string;

    /**
     * Selected is what was open in a detail panel, if anything.
     */
    "selected"?: Selection | null;

    /** Creates a new Context instance. */
    constructor($$source: Partial<Context> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Context instance from a string or object.
     */
    static createFrom($$source: any = {}): Context {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("selected" in $$parsedSource) {
            $$parsedSource["selected"] = $$createField3_0($$parsedSource["selected"]);
        }
        return new Context($$parsedSource as Partial<Context>);
    }
}

/**
 * Event is one change to a conversation.
 */
export class Event {
    "session": string;
    "seq": number;
    "kind": string;
    "item"?: Item | null;
    "itemId"?: string;
    "text"?: string;

    /**
     * Running is whether a run is going, on a run event.
     */
    "running": boolean;

    /**
     * Model is the model the conversation runs on, on a run event. It follows
     * the settings until the model has answered once.
     */
    "model"?: string;

    /**
     * Usage is what the conversation has spent, on the event that ends a run.
     */
    "usage"?: provider$0.Usage | null;

    /** Creates a new Event instance. */
    constructor($$source: Partial<Event> = {}) {
        if (!("session" in $$source)) {
            this["session"] = "";
        }
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     */
    static createFrom($$source: any = {}): Event {
        const $$createField3_0 = $$createType3;
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField3_0($$parsedSource["item"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField8_0($$parsedSource["usage"]);
        }
        return new Event($$parsedSource as Partial<Event>);
    }
}

/**
 * Item is one entry in a conversation.
 */
export class Item {
    "id": string;
    "kind": string;
    "text"?: string;

    /**
     * Context is what came with a person's message.
     */
    "context"?: Context | null;
    "tool"?: ToolItem | null;

    /**
     * Notice is which notice this is; Text says more where there is more.
     */
    "notice"?: string;

    /**
     * Reason is why a model service failed, for a failed notice: the reasons
     * a settings test reports.
     */
    "reason"?: string;

    /** Creates a new Item instance. */
    constructor($$source: Partial<Item> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     */
    static createFrom($$source: any = {}): Item {
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField3_0($$parsedSource["context"]);
        }
        if ("tool" in $$parsedSource) {
            $$parsedSource["tool"] = $$createField4_0($$parsedSource["tool"]);
        }
        return new Item($$parsedSource as Partial<Item>);
    }
}

/**
 * Selection is one object a person had open.
 */
export class Selection {
    "kind": string;
    "name": string;

    /** Creates a new Selection instance. */
    constructor($$source: Partial<Selection> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Selection instance from a string or object.
     */
    static createFrom($$source: any = {}): Selection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Selection($$parsedSource as Partial<Selection>);
    }
}

/**
 * Snapshot is a whole conversation as of one event.
 */
export class Snapshot {
    "session": string;
    "seq": number;
    "title": string;
    "running": boolean;
    "model": string;
    "items": Item[];
    "usage": provider$0.Usage;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("session" in $$source)) {
            this["session"] = "";
        }
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("usage" in $$source)) {
            this["usage"] = (new provider$0.Usage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField5_0($$parsedSource["items"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField6_0($$parsedSource["usage"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

/**
 * Summary is a conversation as a list of them shows it.
 */
export class Summary {
    "id": string;
    "title": string;

    /**
     * Provider is the model service it runs on.
     */
    "provider": string;
    "model": string;

    /**
     * Connection is the one its first question was about, named as it was.
     */
    "connection"?: audit$0.Connection | null;
    "created": string;

    /**
     * Updated is when the conversation last answered or changed.
     */
    "updated": string;
    "running": boolean;

    /**
     * Open is a conversation this run of the application holds, as against
     * one only on disk.
     */
    "open": boolean;

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated" in $$source)) {
            this["updated"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("open" in $$source)) {
            this["open"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField4_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connection" in $$parsedSource) {
            $$parsedSource["connection"] = $$createField4_0($$parsedSource["connection"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

/**
 * ToolItem is one tool call, from the model asking to the result.
 */
export class ToolItem {
    "call": string;
    "name": string;
    "title": string;
    "blast"?: string;
    "input": json$0.RawMessage;

    /**
     * Connection is the connection a write reaches, named as it was then.
     */
    "connection"?: audit$0.Connection | null;
    "state": string;
    "ask"?: Ask | null;

    /**
     * Approved is how a write was let through: once, session or confirmed.
     */
    "approved"?: string;

    /**
     * Result is what came of it in a line: what a write changed, or why the
     * call failed or did not happen.
     */
    "result"?: string;

    /**
     * Output is the answer for the window to show. What the model is handed
     * is cut shorter.
     */
    "output"?: json$0.RawMessage;
    "ms"?: number;

    /** Creates a new ToolItem instance. */
    constructor($$source: Partial<ToolItem> = {}) {
        if (!("call" in $$source)) {
            this["call"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("input" in $$source)) {
            this["input"] = null;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolItem {
        const $$createField5_0 = $$createType12;
        const $$createField7_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connection" in $$parsedSource) {
            $$parsedSource["connection"] = $$createField5_0($$parsedSource["connection"]);
        }
        if ("ask" in $$parsedSource) {
            $$parsedSource["ask"] = $$createField7_0($$parsedSource["ask"]);
        }
        return new ToolItem($$parsedSource as Partial<ToolItem>);
    }
}

// Private type creation functions
const $$createType0 = Selection.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Item.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = provider$0.Usage.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = Context.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = ToolItem.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType2);
const $$createType11 = audit$0.Connection.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = Ask.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
