// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ACLService exposes access-control administration to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteAccess removes an ACL access config entry.
 */
export function DeleteAccess(connID: number, accessKey: string): $CancellablePromise<void> {
    return $Call.ByID(3342919822, connID, accessKey);
}

/**
 * Enabled reports whether the broker has ACL turned on.
 */
export function Enabled(connID: number): $CancellablePromise<boolean> {
    return $Call.ByID(568290460, connID);
}

/**
 * UpdateAccess creates or replaces an ACL access config entry.
 */
export function UpdateAccess(connID: number, input: $models.AccessConfigInput): $CancellablePromise<void> {
    return $Call.ByID(4030612624, connID, input);
}

/**
 * UpdateWhiteAddrs replaces the broker global IP white list.
 */
export function UpdateWhiteAddrs(connID: number, addrs: string[]): $CancellablePromise<void> {
    return $Call.ByID(2512924429, connID, addrs);
}

/**
 * Version returns the broker ACL config version and its entries.
 */
export function Version(connID: number): $CancellablePromise<model$0.AclVersionInfo | null> {
    return $Call.ByID(2629139113, connID).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.AclVersionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
