// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ACLService exposes broker ACL administration to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteAccess removes an ACL access config entry.
 */
export function DeleteAccess(accessKey: string): $CancellablePromise<void> {
    return $Call.ByID(3342919822, accessKey);
}

/**
 * Enabled reports whether the broker has ACL turned on.
 */
export function Enabled(): $CancellablePromise<boolean> {
    return $Call.ByID(568290460);
}

/**
 * UpdateAccess creates or replaces an ACL access config entry.
 */
export function UpdateAccess(input: $models.AccessConfigInput): $CancellablePromise<void> {
    return $Call.ByID(4030612624, input);
}

/**
 * UpdateWhiteAddrs replaces the broker global IP white list.
 */
export function UpdateWhiteAddrs(addrs: string[]): $CancellablePromise<void> {
    return $Call.ByID(2512924429, addrs);
}

/**
 * Version returns the broker ACL config version and its entries.
 */
export function Version(): $CancellablePromise<model$0.AclVersionInfo | null> {
    return $Call.ByID(2629139113).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.AclVersionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
