// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ACLService exposes access-control administration to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteAccess removes an ACL access config entry.
 */
export function DeleteAccess(connID: number, accessKey: string): $CancellablePromise<void> {
    return $Call.ByID(3342919822, connID, accessKey);
}

/**
 * DeletePrincipal removes a principal.
 */
export function DeletePrincipal(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3815334526, connID, name);
}

/**
 * DeleteRule drops every policy attached to a subject.
 */
export function DeleteRule(connID: number, subject: string): $CancellablePromise<void> {
    return $Call.ByID(3982915882, connID, subject);
}

/**
 * DirectoryEnabled reports whether the broker runs identity-based access
 * control, which is what decides which of the two ACL systems the page shows.
 */
export function DirectoryEnabled(connID: number): $CancellablePromise<boolean> {
    return $Call.ByID(2276842395, connID);
}

/**
 * Enabled reports whether the broker has ACL turned on.
 */
export function Enabled(connID: number): $CancellablePromise<boolean> {
    return $Call.ByID(568290460, connID);
}

/**
 * Principals returns the identities the broker authenticates.
 */
export function Principals(connID: number): $CancellablePromise<(model$0.AccessPrincipal | null)[]> {
    return $Call.ByID(565209008, connID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Rules returns every subject's policies.
 */
export function Rules(connID: number): $CancellablePromise<(model$0.AccessRule | null)[]> {
    return $Call.ByID(2034516958, connID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * UpdateAccess creates or replaces an ACL access config entry.
 */
export function UpdateAccess(connID: number, input: $models.AccessConfigInput): $CancellablePromise<void> {
    return $Call.ByID(4030612624, connID, input);
}

/**
 * UpdatePrincipal creates a principal, or updates one that already exists.
 */
export function UpdatePrincipal(connID: number, input: $models.PrincipalInput): $CancellablePromise<void> {
    return $Call.ByID(1019927728, connID, input);
}

/**
 * UpdateRule replaces one subject's policies. It replaces rather than merges,
 * which is what the broker does with the set it is handed.
 */
export function UpdateRule(connID: number, input: $models.AccessRuleInput): $CancellablePromise<void> {
    return $Call.ByID(3524370640, connID, input);
}

/**
 * UpdateWhiteAddrs replaces the broker global IP white list.
 */
export function UpdateWhiteAddrs(connID: number, addrs: string[]): $CancellablePromise<void> {
    return $Call.ByID(2512924429, connID, addrs);
}

/**
 * Version returns the broker ACL config version and its entries.
 */
export function Version(connID: number): $CancellablePromise<model$0.AclVersionInfo | null> {
    return $Call.ByID(2629139113, connID).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.AccessPrincipal.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.AccessRule.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.AclVersionInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
