// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService runs the window's assistant: its conversations, the runs that
 * answer them, and the questions a run puts to the person.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as assistant$0 from "../agent/assistant/models.js";

/**
 * Decide answers a question a run is waiting on.
 */
export function Decide(session: string, ask: string, approve: boolean, remember: boolean): $CancellablePromise<void> {
    return $Call.ByID(2915440794, session, ask, approve, remember);
}

/**
 * Send adds what the person said, and where they were, and starts the run
 * that answers it. What the run does arrives as events.
 */
export function Send(session: string, text: string, where: assistant$0.Context): $CancellablePromise<void> {
    return $Call.ByID(2472977012, session, text, where);
}

/**
 * Sessions lists the conversations, the newest first.
 */
export function Sessions(): $CancellablePromise<assistant$0.Summary[]> {
    return $Call.ByID(3277491683).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Snapshot is a conversation as it stands, for a renderer that missed an
 * event or opened late.
 */
export function Snapshot(session: string): $CancellablePromise<assistant$0.Snapshot> {
    return $Call.ByID(2561404402, session).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Start opens a conversation on a model service; empty is the default one.
 */
export function Start(provider: string): $CancellablePromise<assistant$0.Summary> {
    return $Call.ByID(3263460510, provider).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Stop ends a conversation's run.
 */
export function Stop(session: string): $CancellablePromise<void> {
    return $Call.ByID(2909695398, session);
}

// Private type creation functions
const $$createType0 = assistant$0.Summary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = assistant$0.Snapshot.createFrom;
