// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentSettingsService sets up the window's assistant: the model services it
 * runs on and how it treats writes. A key goes in and never comes back out.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Consent records that the person agreed to what is sent to a model service,
 * which the assistant waits for before it sends anything there.
 */
export function Consent(id: string): $CancellablePromise<$models.AgentSettingsView | null> {
    return $Call.ByID(275671911, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteProvider removes a model service and its key.
 */
export function DeleteProvider(id: string): $CancellablePromise<$models.AgentSettingsView | null> {
    return $Call.ByID(1929868937, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Get returns the assistant's set-up, keys redacted.
 */
export function Get(): $CancellablePromise<$models.AgentSettingsView | null> {
    return $Call.ByID(1158513849).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListModels asks the service which models it offers, with the form as it
 * stands.
 */
export function ListModels(input: $models.AgentProviderInput): $CancellablePromise<$models.AgentModels> {
    return $Call.ByID(980719861, input).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SavePreferences replaces everything on the page that is not a provider.
 */
export function SavePreferences(input: $models.AgentPreferencesInput): $CancellablePromise<$models.AgentSettingsView | null> {
    return $Call.ByID(2189203800, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveProvider adds a model service, or changes the one input.ID names.
 */
export function SaveProvider(input: $models.AgentProviderInput): $CancellablePromise<$models.AgentSettingsView | null> {
    return $Call.ByID(3341826215, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * TestProvider sends the service one small request carrying a tool, with the
 * form as it stands. Nothing is saved.
 */
export function TestProvider(input: $models.AgentProviderInput): $CancellablePromise<$models.AgentProbe> {
    return $Call.ByID(3214942874, input).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AgentSettingsView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.AgentModels.createFrom;
const $$createType3 = $models.AgentProbe.createFrom;
