// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService exposes connection management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add stores a new connection and returns it with credentials redacted.
 */
export function Add(input: $models.ConnectionInput): $CancellablePromise<$models.ConnectionView | null> {
    return $Call.ByID(3257557894, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Connect opens the client for a connection.
 */
export function Connect(id: number): $CancellablePromise<void> {
    return $Call.ByID(597177111, id);
}

/**
 * ConnectDefault opens the client for the default connection.
 */
export function ConnectDefault(): $CancellablePromise<void> {
    return $Call.ByID(1684387968);
}

/**
 * Disconnect closes the client for a connection.
 */
export function Disconnect(id: number): $CancellablePromise<void> {
    return $Call.ByID(2955890537, id);
}

/**
 * List returns every configured connection with credentials redacted.
 */
export function List(): $CancellablePromise<($models.ConnectionView | null)[]> {
    return $Call.ByID(1321039563).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Probe tests a form submission without storing it.
 * 
 * The id is the connection being edited, or zero for a new one; it exists only
 * so a form whose password field shows "already set" can be tested with the
 * stored credential rather than an empty one.
 */
export function Probe(id: number, input: $models.ConnectionInput): $CancellablePromise<void> {
    return $Call.ByID(2385811175, id, input);
}

/**
 * Remove deletes a connection.
 */
export function Remove(id: number): $CancellablePromise<void> {
    return $Call.ByID(3549691311, id);
}

/**
 * SetDefault marks a connection as the default one.
 */
export function SetDefault(id: number): $CancellablePromise<void> {
    return $Call.ByID(3271949170, id);
}

/**
 * Test probes a connection and reports the resulting status.
 */
export function Test(id: number): $CancellablePromise<string> {
    return $Call.ByID(2170510231, id);
}

/**
 * Update applies a connection form submission, resolving the credentials mode
 * against the currently stored secrets.
 */
export function Update(id: number, input: $models.ConnectionInput): $CancellablePromise<$models.ConnectionView | null> {
    return $Call.ByID(1659627746, id, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConnectionView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
