// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService exposes connection management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add stores a new connection and returns it with credentials redacted.
 */
export function Add(input: $models.ConnectionInput): $CancellablePromise<$models.ConnectionView | null> {
    return $Call.ByID(3257557894, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Connect opens the client for a connection.
 */
export function Connect(id: number): $CancellablePromise<void> {
    return $Call.ByID(597177111, id);
}

/**
 * ConnectDefault opens the client for the default connection.
 */
export function ConnectDefault(): $CancellablePromise<void> {
    return $Call.ByID(1684387968);
}

/**
 * Disconnect closes the client for a connection.
 */
export function Disconnect(id: number): $CancellablePromise<void> {
    return $Call.ByID(2955890537, id);
}

/**
 * List returns every configured connection with credentials redacted.
 */
export function List(): $CancellablePromise<($models.ConnectionView | null)[]> {
    return $Call.ByID(1321039563).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Probe tests a form submission without storing it.
 * 
 * The id is the connection being edited, or zero for a new one; it exists only
 * so a form whose password field shows "already set" can be tested with the
 * stored credential rather than an empty one.
 */
export function Probe(id: number, input: $models.ConnectionInput): $CancellablePromise<void> {
    return $Call.ByID(2385811175, id, input);
}

/**
 * Remove deletes a connection.
 */
export function Remove(id: number): $CancellablePromise<void> {
    return $Call.ByID(3549691311, id);
}

/**
 * Scopes lists what this connection could be re-pointed at, for a family whose
 * scope is a naming convention rather than a broker object.
 */
export function Scopes(connID: number): $CancellablePromise<(model$0.Scope | null)[]> {
    return $Call.ByID(1287254622, connID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SetDefault marks a connection as the default one.
 */
export function SetDefault(id: number): $CancellablePromise<void> {
    return $Call.ByID(3271949170, id);
}

/**
 *  * SetScope re-points a connection at another scope and redials it.
 *  *
 *  * The option key comes from the driver descriptor rather than from the
 *  * renderer, so the shell asks for "this scope" and never has to know that
 *  * RocketMQ spells it `namespace`.
 *  *
 *  * Validated before it is stored, against the live connection. Storing a name
 *  * the driver would refuse leaves a profile that no longer opens at all, and
 *  * the switcher is gated on being connected - so the user would have no way
 *  * back to a working one.
 */
export function SetScope(connID: number, name: string): $CancellablePromise<$models.ConnectionView | null> {
    return $Call.ByID(4146218863, connID, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Test probes a connection and reports the resulting status.
 */
export function Test(id: number): $CancellablePromise<string> {
    return $Call.ByID(2170510231, id);
}

/**
 * Update applies a connection form submission, resolving the credentials mode
 * against the currently stored secrets.
 */
export function Update(id: number, input: $models.ConnectionInput): $CancellablePromise<$models.ConnectionView | null> {
    return $Call.ByID(1659627746, id, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConnectionView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.Scope.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
