// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConsumerService exposes subscription operations to the frontend.
 * 
 * It speaks the canonical model. Consume mode, retry limits and the
 * subscription and client lists travel in the attribute map, whose keys the
 * frontend's rocketmq module reads.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create adds a consumer group on the target broker.
 */
export function Create(connID: number, input: $models.ConsumerInput): $CancellablePromise<void> {
    return $Call.ByID(3797574047, connID, input);
}

/**
 * Detail returns a consumer group with its clients and subscriptions.
 */
export function Detail(connID: number, group: string): $CancellablePromise<model$0.Subscription | null> {
    return $Call.ByID(2168000630, connID, group).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * List returns every consumer group.
 */
export function List(connID: number): $CancellablePromise<(model$0.Subscription | null)[]> {
    return $Call.ByID(699201983, connID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Remove deletes a consumer group.
 */
export function Remove(connID: number, group: string, brokerAddr: string): $CancellablePromise<void> {
    return $Call.ByID(1788729339, connID, group, brokerAddr);
}

/**
 * ResetOffset moves a consumer group's read position.
 */
export function ResetOffset(connID: number, request: model$0.ResetOffsetRequest): $CancellablePromise<void> {
    return $Call.ByID(1260330865, connID, request);
}

/**
 * Stats returns the per-queue consume progress of a group.
 */
export function Stats(connID: number, group: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3402555482, connID, group).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Update changes an existing consumer group.
 */
export function Update(connID: number, input: $models.ConsumerInput): $CancellablePromise<void> {
    return $Call.ByID(2853418918, connID, input);
}

// Private type creation functions
const $$createType0 = model$0.Subscription.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
