// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConsumerService exposes subscription operations to the frontend.
 * 
 * It speaks the canonical model. Consume mode, retry limits and the
 * subscription and client lists travel in the attribute map, whose keys the
 * frontend's rocketmq module reads.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Clients reports what each connected consumer in a group is doing: the queues
 * it holds and how fast it is getting through them.
 * 
 * It is a separate call rather than part of Detail because it costs one round
 * trip per connected client, and a group list should not pay that.
 */
export function Clients(connID: number, group: string): $CancellablePromise<(model$0.SubscriptionClient | null)[]> {
    return $Call.ByID(4135460369, connID, group).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CloneOffset copies one consumer group's read position onto another, which is
 * how a replacement group starts where the old one is instead of replaying
 * everything it already handled.
 */
export function CloneOffset(connID: number, request: model$0.CloneOffsetRequest): $CancellablePromise<void> {
    return $Call.ByID(3606627855, connID, request);
}

/**
 * Create adds a consumer group on the target broker.
 */
export function Create(connID: number, input: $models.ConsumerInput): $CancellablePromise<void> {
    return $Call.ByID(3797574047, connID, input);
}

/**
 * List returns every consumer group.
 */
export function List(connID: number): $CancellablePromise<(model$0.Subscription | null)[]> {
    return $Call.ByID(699201983, connID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Remove deletes a consumer group.
 */
export function Remove(connID: number, group: string, brokerAddr: string): $CancellablePromise<void> {
    return $Call.ByID(1788729339, connID, group, brokerAddr);
}

/**
 * ResetOffset moves a consumer group's read position.
 */
export function ResetOffset(connID: number, request: model$0.ResetOffsetRequest): $CancellablePromise<void> {
    return $Call.ByID(1260330865, connID, request);
}

/**
 * Stats returns the per-queue consume progress of a group.
 */
export function Stats(connID: number, group: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3402555482, connID, group).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Update changes an existing consumer group.
 */
export function Update(connID: number, input: $models.ConsumerInput): $CancellablePromise<void> {
    return $Call.ByID(2853418918, connID, input);
}

// Private type creation functions
const $$createType0 = model$0.SubscriptionClient.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.Subscription.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
