// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DriverService tells the frontend which broker families exist, what their
 * connection forms look like, and what a live connection can actually do.
 * 
 * It is what the renderer boots from: the navigation, the connection form and
 * every gated control are derived from these three answers rather than
 * hardcoded for one family.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Capabilities returns what one live connection can do.
 * 
 * An unopened connection reports nothing supported rather than an error: the
 * renderer asks on every page load, including before anything is connected,
 * and an error there would be noise rather than information.
 */
export function Capabilities(connID: number): $CancellablePromise<model$0.Capabilities | null> {
    return $Call.ByID(3284513215, connID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Descriptor returns a family's connection form and best-case capabilities.
 * It answers without a connection, because the form is drawn before anything
 * is dialled.
 */
export function Descriptor(kind: model$0.MQKind): $CancellablePromise<model$0.DriverDescriptor | null> {
    return $Call.ByID(3669721920, kind).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * List returns every family a driver is compiled in for.
 */
export function List(): $CancellablePromise<$models.DriverInfo[]> {
    return $Call.ByID(2168678273).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Capabilities.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.DriverDescriptor.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.DriverInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
