// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KafkaService exposes what only Kafka has.
 * 
 * It is one service rather than several because it is one family's surface:
 * splitting topic administration, quotas and reassignment into three would put
 * three names in the bindings for what a reader thinks of as "the Kafka pages".
 * 
 * Reading topics, groups and brokers is not here. Those are destinations,
 * subscriptions and nodes, and the canonical services already answer them; a
 * second read path would be two sources for one number.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AlterTopicConfigs changes only the settings it is given. An empty value puts
 * a setting back to the cluster default rather than setting it to nothing.
 */
export function AlterTopicConfigs(connID: number, name: string, configs: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(60882305, connID, name, configs);
}

/**
 * CreateTopic declares a topic.
 */
export function CreateTopic(connID: number, input: $models.KafkaTopicInput): $CancellablePromise<void> {
    return $Call.ByID(77144948, connID, input);
}

/**
 * DeleteTopic removes a topic and everything in it.
 * 
 * It returns once the cluster agrees the topic is gone rather than once the
 * delete is accepted, so a board that re-reads on success does not list what
 * was just deleted.
 */
export function DeleteTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2393614773, connID, name);
}
