// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KafkaService exposes what only Kafka has.
 * 
 * It is one service rather than several because it is one family's surface:
 * splitting topic administration, quotas and reassignment into three would put
 * three names in the bindings for what a reader thinks of as "the Kafka pages".
 * 
 * Reading topics, groups and brokers is not here. Those are destinations,
 * subscriptions and nodes, and the canonical services already answer them; a
 * second read path would be two sources for one number.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as kafka$0 from "../driver/kafka/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AccessControl reports the cluster's ACLs and the users it stores.
 */
export function AccessControl(connID: number): $CancellablePromise<$models.AccessView | null> {
    return $Call.ByID(3580281988, connID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AlterTopicConfigs changes only the settings it is given. An empty value puts
 * a setting back to the cluster default rather than setting it to nothing.
 */
export function AlterTopicConfigs(connID: number, name: string, configs: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(60882305, connID, name, configs);
}

/**
 * CloneGroupOffsets copies one group's positions onto another, which is how a
 * replacement consumer group starts where the old one is instead of replaying
 * everything it already handled.
 */
export function CloneGroupOffsets(connID: number, $from: string, to: string, topic: string): $CancellablePromise<void> {
    return $Call.ByID(315480963, connID, $from, to, topic);
}

/**
 * CreateTopic declares a topic.
 */
export function CreateTopic(connID: number, input: $models.KafkaTopicInput): $CancellablePromise<void> {
    return $Call.ByID(77144948, connID, input);
}

/**
 * DeleteGroup removes a consumer group and the offsets it holds.
 */
export function DeleteGroup(connID: number, group: string): $CancellablePromise<void> {
    return $Call.ByID(2945461861, connID, group);
}

/**
 * DeleteGroupOffsets forgets a group's position on some topics without
 * deleting the group.
 */
export function DeleteGroupOffsets(connID: number, group: string, topics: string[]): $CancellablePromise<void> {
    return $Call.ByID(2128738747, connID, group, topics);
}

/**
 * DeleteTopic removes a topic and everything in it.
 * 
 * It returns once the cluster agrees the topic is gone rather than once the
 * delete is accepted, so a board that re-reads on success does not list what
 * was just deleted.
 */
export function DeleteTopic(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2393614773, connID, name);
}

/**
 * LogDirs reports where a cluster's disk has gone.
 */
export function LogDirs(connID: number): $CancellablePromise<$models.LogDirView | null> {
    return $Call.ByID(990165473, connID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PutAccessRule writes every policy a subject should have.
 */
export function PutAccessRule(connID: number, rule: model$0.AccessRule): $CancellablePromise<void> {
    return $Call.ByID(1337322702, connID, rule);
}

/**
 * PutPrincipal creates or updates a SCRAM user. The password is write-only:
 * Kafka stores it salted and cannot be asked for it again.
 */
export function PutPrincipal(connID: number, spec: model$0.AccessPrincipalSpec): $CancellablePromise<void> {
    return $Call.ByID(3465574448, connID, spec);
}

/**
 * RemoveAccessRule deletes every rule belonging to a principal.
 */
export function RemoveAccessRule(connID: number, subject: string): $CancellablePromise<void> {
    return $Call.ByID(3569953445, connID, subject);
}

/**
 * RemovePrincipal deletes a user's password for every mechanism it has.
 */
export function RemovePrincipal(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3436133945, connID, name);
}

/**
 * ResetGroupOffsets writes a consumer group's committed offsets.
 * 
 * Kafka refuses this while the group has live members. That refusal reaches
 * the user as-is: the fix is to stop the consumers, and saying so is more use
 * than a reset a running consumer would overwrite moments later.
 */
export function ResetGroupOffsets(connID: number, input: $models.OffsetResetInput): $CancellablePromise<void> {
    return $Call.ByID(2590147649, connID, input);
}

/**
 * SendRecord publishes and reports the partition and offset it landed on.
 */
export function SendRecord(connID: number, input: $models.RecordInput): $CancellablePromise<kafka$0.RecordResult | null> {
    return $Call.ByID(2137680894, connID, input).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AccessView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.LogDirView.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = kafka$0.RecordResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
