// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MessageService exposes RocketMQ message query and production to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ByID returns a single message by its ID.
 */
export function ByID(topic: string, messageID: string): $CancellablePromise<model$0.MessageItem | null> {
    return $Call.ByID(3857162568, topic, messageID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DLQ returns the dead letter messages of a consumer group.
 */
export function DLQ(group: string, maxResults: number): $CancellablePromise<(model$0.MessageItem | null)[]> {
    return $Call.ByID(1667775571, group, maxResults).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Query searches a topic by key, tag and time range.
 */
export function Query(query: $models.MessageQuery): $CancellablePromise<(model$0.MessageItem | null)[]> {
    return $Call.ByID(1939938708, query).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Resend pushes a message back to a consumer client and returns the new ID.
 */
export function Resend(input: $models.ResendInput): $CancellablePromise<string> {
    return $Call.ByID(2133352667, input);
}

/**
 * Retry returns the retry messages of a consumer group.
 */
export function Retry(group: string, maxResults: number): $CancellablePromise<(model$0.MessageItem | null)[]> {
    return $Call.ByID(1844595922, group, maxResults).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Send produces a message and returns its ID.
 */
export function Send(input: $models.SendInput): $CancellablePromise<string> {
    return $Call.ByID(2088005278, input);
}

/**
 * Track returns the per-group consume status of a message.
 */
export function Track(topic: string, messageID: string): $CancellablePromise<(model$0.MessageTrackItem | null)[]> {
    return $Call.ByID(2516316023, topic, messageID).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.MessageItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.MessageTrackItem.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
