// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MessageService exposes message browse and publish to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ByID returns a single message by its ID.
 */
export function ByID(connID: number, topic: string, messageID: string): $CancellablePromise<model$0.MessageItem | null> {
    return $Call.ByID(3857162568, connID, topic, messageID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DLQ returns the dead letter messages of a consumer group.
 */
export function DLQ(connID: number, group: string, maxResults: number): $CancellablePromise<(model$0.MessageItem | null)[]> {
    return $Call.ByID(1667775571, connID, group, maxResults).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Producers lists the publishers connected under a producer group.
 */
export function Producers(connID: number, group: string, topic: string): $CancellablePromise<(model$0.ProducerClient | null)[]> {
    return $Call.ByID(827390843, connID, group, topic).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Query searches a topic by key, tag and time range.
 */
export function Query(connID: number, query: $models.MessageQuery): $CancellablePromise<(model$0.MessageItem | null)[]> {
    return $Call.ByID(1939938708, connID, query).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Resend pushes a message back to a consumer client and returns the new ID.
 */
export function Resend(connID: number, input: $models.ResendInput): $CancellablePromise<string> {
    return $Call.ByID(2133352667, connID, input);
}

/**
 * Retry returns the retry messages of a consumer group.
 */
export function Retry(connID: number, group: string, maxResults: number): $CancellablePromise<(model$0.MessageItem | null)[]> {
    return $Call.ByID(1844595922, connID, group, maxResults).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Send produces a message and returns its ID.
 */
export function Send(connID: number, input: $models.SendInput): $CancellablePromise<string> {
    return $Call.ByID(2088005278, connID, input);
}

/**
 * Tail returns what a topic has received since the cursor, and the cursor to
 * pass next time. The renderer drives the interval; Go holds nothing open.
 */
export function Tail(connID: number, topic: string, cursor: model$0.TailCursor, limit: number): $CancellablePromise<model$0.TailBatch | null> {
    return $Call.ByID(992589890, connID, topic, cursor, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Track returns the per-group consume status of a message.
 */
export function Track(connID: number, topic: string, messageID: string): $CancellablePromise<(model$0.MessageTrackItem | null)[]> {
    return $Call.ByID(2516316023, connID, topic, messageID).then(($result: any) => {
        return $$createType10($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.MessageItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.ProducerClient.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.TailBatch.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.MessageTrackItem.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
