// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * AccessConfigInput carries an ACL access config form submission.
 */
export class AccessConfigInput {
    "accessKey": string;
    "secretKey": string;
    "whiteRemoteAddress": string;
    "isAdmin": boolean;
    "defaultTopicPerm": string;
    "defaultGroupPerm": string;
    "topicPerms": string[];
    "groupPerms": string[];

    /** Creates a new AccessConfigInput instance. */
    constructor($$source: Partial<AccessConfigInput> = {}) {
        if (!("accessKey" in $$source)) {
            this["accessKey"] = "";
        }
        if (!("secretKey" in $$source)) {
            this["secretKey"] = "";
        }
        if (!("whiteRemoteAddress" in $$source)) {
            this["whiteRemoteAddress"] = "";
        }
        if (!("isAdmin" in $$source)) {
            this["isAdmin"] = false;
        }
        if (!("defaultTopicPerm" in $$source)) {
            this["defaultTopicPerm"] = "";
        }
        if (!("defaultGroupPerm" in $$source)) {
            this["defaultGroupPerm"] = "";
        }
        if (!("topicPerms" in $$source)) {
            this["topicPerms"] = [];
        }
        if (!("groupPerms" in $$source)) {
            this["groupPerms"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessConfigInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessConfigInput {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("topicPerms" in $$parsedSource) {
            $$parsedSource["topicPerms"] = $$createField6_0($$parsedSource["topicPerms"]);
        }
        if ("groupPerms" in $$parsedSource) {
            $$parsedSource["groupPerms"] = $$createField7_0($$parsedSource["groupPerms"]);
        }
        return new AccessConfigInput($$parsedSource as Partial<AccessConfigInput>);
    }
}

/**
 * AccessRuleInput carries an access-rule form submission.
 */
export class AccessRuleInput {
    "subject": string;
    "description": string;
    "policies": PolicyInput[];

    /** Creates a new AccessRuleInput instance. */
    constructor($$source: Partial<AccessRuleInput> = {}) {
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("policies" in $$source)) {
            this["policies"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessRuleInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessRuleInput {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("policies" in $$parsedSource) {
            $$parsedSource["policies"] = $$createField2_0($$parsedSource["policies"]);
        }
        return new AccessRuleInput($$parsedSource as Partial<AccessRuleInput>);
    }
}

/**
 * ClusterView is the cluster page's snapshot: the header counters and the
 * nodes behind them, in one round trip.
 */
export class ClusterView {
    "overview": model$0.ClusterOverview;
    "nodes": (model$0.Node | null)[];

    /**
     * Directory is the tier the cluster is reached through - RocketMQ name
     * servers. Empty for a family that has none, which the page reads as
     * "there is no such tier" rather than as "none are up".
     */
    "directory": (model$0.Node | null)[];

    /** Creates a new ClusterView instance. */
    constructor($$source: Partial<ClusterView> = {}) {
        if (!("overview" in $$source)) {
            this["overview"] = (new model$0.ClusterOverview());
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("directory" in $$source)) {
            this["directory"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterView instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterView {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("overview" in $$parsedSource) {
            $$parsedSource["overview"] = $$createField0_0($$parsedSource["overview"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField1_0($$parsedSource["nodes"]);
        }
        if ("directory" in $$parsedSource) {
            $$parsedSource["directory"] = $$createField2_0($$parsedSource["directory"]);
        }
        return new ClusterView($$parsedSource as Partial<ClusterView>);
    }
}

/**
 * ConnectionInput carries a connection form submission.
 * 
 * Secrets is write-only: it carries what the user just typed, and nothing ever
 * sends one back.
 */
export class ConnectionInput {
    "name": string;
    "group": string;
    "kind": model$0.MQKind;
    "endpoints": string;
    "timeoutSec": number;
    "authMechanism": model$0.AuthMechanism;
    "options": { [_ in string]?: string };
    "secrets": { [_ in string]?: string };
    "remark": string;

    /**
     * CredentialsMode says what to do with secrets the form left blank:
     * preserve what is stored, replace it with what was typed, or clear it.
     */
    "credentialsMode": string;

    /** Creates a new ConnectionInput instance. */
    constructor($$source: Partial<ConnectionInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.MQKind.$zero;
        }
        if (!("endpoints" in $$source)) {
            this["endpoints"] = "";
        }
        if (!("timeoutSec" in $$source)) {
            this["timeoutSec"] = 0;
        }
        if (!("authMechanism" in $$source)) {
            this["authMechanism"] = model$0.AuthMechanism.$zero;
        }
        if (!("options" in $$source)) {
            this["options"] = {};
        }
        if (!("secrets" in $$source)) {
            this["secrets"] = {};
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("credentialsMode" in $$source)) {
            this["credentialsMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionInput {
        const $$createField6_0 = $$createType7;
        const $$createField7_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        if ("secrets" in $$parsedSource) {
            $$parsedSource["secrets"] = $$createField7_0($$parsedSource["secrets"]);
        }
        return new ConnectionInput($$parsedSource as Partial<ConnectionInput>);
    }
}

/**
 * ConnectionView is the connection shape sent to the frontend.
 * 
 * Stored credentials never leave the Go process. The renderer decides what to
 * render from SecretsConfigured, which lists the keys that hold a value - a
 * list rather than a pair of booleans, because how many credentials a
 * connection has is the driver's business, not this struct's.
 */
export class ConnectionView {
    "id": number;
    "name": string;
    "group": string;
    "kind": model$0.MQKind;
    "endpoints": string;
    "timeoutSec": number;
    "authMechanism": model$0.AuthMechanism;
    "options": { [_ in string]?: string };
    "secretsConfigured": string[];
    "status": model$0.ConnectionStatus;
    "lastCheck": string;
    "isDefault": boolean;
    "remark": string;

    /** Creates a new ConnectionView instance. */
    constructor($$source: Partial<ConnectionView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = model$0.MQKind.$zero;
        }
        if (!("endpoints" in $$source)) {
            this["endpoints"] = "";
        }
        if (!("timeoutSec" in $$source)) {
            this["timeoutSec"] = 0;
        }
        if (!("authMechanism" in $$source)) {
            this["authMechanism"] = model$0.AuthMechanism.$zero;
        }
        if (!("options" in $$source)) {
            this["options"] = {};
        }
        if (!("secretsConfigured" in $$source)) {
            this["secretsConfigured"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = model$0.ConnectionStatus.$zero;
        }
        if (!("lastCheck" in $$source)) {
            this["lastCheck"] = "";
        }
        if (!("isDefault" in $$source)) {
            this["isDefault"] = false;
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionView instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionView {
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField7_0($$parsedSource["options"]);
        }
        if ("secretsConfigured" in $$parsedSource) {
            $$parsedSource["secretsConfigured"] = $$createField8_0($$parsedSource["secretsConfigured"]);
        }
        return new ConnectionView($$parsedSource as Partial<ConnectionView>);
    }
}

/**
 * ConsumerInput carries a consumer group form submission.
 */
export class ConsumerInput {
    "group": string;
    "brokerAddr": string;
    "consumeMode": string;
    "maxRetry": number;

    /** Creates a new ConsumerInput instance. */
    constructor($$source: Partial<ConsumerInput> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("brokerAddr" in $$source)) {
            this["brokerAddr"] = "";
        }
        if (!("consumeMode" in $$source)) {
            this["consumeMode"] = "";
        }
        if (!("maxRetry" in $$source)) {
            this["maxRetry"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsumerInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsumerInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConsumerInput($$parsedSource as Partial<ConsumerInput>);
    }
}

/**
 * DriverInfo is one registered family.
 */
export class DriverInfo {
    "kind": model$0.MQKind;
    "defaultPort": string;

    /** Creates a new DriverInfo instance. */
    constructor($$source: Partial<DriverInfo> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = model$0.MQKind.$zero;
        }
        if (!("defaultPort" in $$source)) {
            this["defaultPort"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DriverInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DriverInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DriverInfo($$parsedSource as Partial<DriverInfo>);
    }
}

/**
 * MaintenanceTaskView is one offerable housekeeping job.
 */
export class MaintenanceTaskView {
    "task": string;

    /**
     * Destructive marks a task that removes message data rather than only
     * reclaiming what is already unreachable, so the UI can confirm it harder.
     */
    "destructive": boolean;

    /** Creates a new MaintenanceTaskView instance. */
    constructor($$source: Partial<MaintenanceTaskView> = {}) {
        if (!("task" in $$source)) {
            this["task"] = "";
        }
        if (!("destructive" in $$source)) {
            this["destructive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MaintenanceTaskView instance from a string or object.
     */
    static createFrom($$source: any = {}): MaintenanceTaskView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MaintenanceTaskView($$parsedSource as Partial<MaintenanceTaskView>);
    }
}

/**
 * MessageQuery carries the message search form.
 */
export class MessageQuery {
    "topic": string;
    "key": string;
    "tag": string;
    "maxResults": number;
    "startTime": number;
    "endTime": number;

    /** Creates a new MessageQuery instance. */
    constructor($$source: Partial<MessageQuery> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("maxResults" in $$source)) {
            this["maxResults"] = 0;
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = 0;
        }
        if (!("endTime" in $$source)) {
            this["endTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageQuery($$parsedSource as Partial<MessageQuery>);
    }
}

/**
 * PolicyInput is one rule row of an access-rule form.
 */
export class PolicyInput {
    "resource": string;
    "actions": string[];
    "effect": string;
    "sourceIps": string[];

    /** Creates a new PolicyInput instance. */
    constructor($$source: Partial<PolicyInput> = {}) {
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("actions" in $$source)) {
            this["actions"] = [];
        }
        if (!("effect" in $$source)) {
            this["effect"] = "";
        }
        if (!("sourceIps" in $$source)) {
            this["sourceIps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PolicyInput instance from a string or object.
     */
    static createFrom($$source: any = {}): PolicyInput {
        const $$createField1_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField1_0($$parsedSource["actions"]);
        }
        if ("sourceIps" in $$parsedSource) {
            $$parsedSource["sourceIps"] = $$createField3_0($$parsedSource["sourceIps"]);
        }
        return new PolicyInput($$parsedSource as Partial<PolicyInput>);
    }
}

/**
 * PrincipalInput carries a principal form submission. The secret is
 * write-only: the broker stores it hashed and nothing sends it back.
 */
export class PrincipalInput {
    "name": string;
    "secret": string;
    "type": string;
    "status": string;

    /** Creates a new PrincipalInput instance. */
    constructor($$source: Partial<PrincipalInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("secret" in $$source)) {
            this["secret"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrincipalInput instance from a string or object.
     */
    static createFrom($$source: any = {}): PrincipalInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrincipalInput($$parsedSource as Partial<PrincipalInput>);
    }
}

/**
 * ReplayInput carries a replay-to-one-consumer request.
 */
export class ReplayInput {
    "consumerGroup": string;
    "clientId": string;
    "topic": string;
    "messageId": string;

    /** Creates a new ReplayInput instance. */
    constructor($$source: Partial<ReplayInput> = {}) {
        if (!("consumerGroup" in $$source)) {
            this["consumerGroup"] = "";
        }
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReplayInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ReplayInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReplayInput($$parsedSource as Partial<ReplayInput>);
    }
}

/**
 * ResendInput identifies a message to push back to a consumer group.
 */
export class ResendInput {
    "consumerGroup": string;
    "clientId": string;
    "topic": string;
    "messageId": string;

    /** Creates a new ResendInput instance. */
    constructor($$source: Partial<ResendInput> = {}) {
        if (!("consumerGroup" in $$source)) {
            this["consumerGroup"] = "";
        }
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("messageId" in $$source)) {
            this["messageId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResendInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResendInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResendInput($$parsedSource as Partial<ResendInput>);
    }
}

/**
 * SendInput carries a produced message.
 */
export class SendInput {
    "topic": string;
    "tags": string;
    "keys": string;
    "body": string;
    "delayLevel": number;

    /** Creates a new SendInput instance. */
    constructor($$source: Partial<SendInput> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = "";
        }
        if (!("keys" in $$source)) {
            this["keys"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("delayLevel" in $$source)) {
            this["delayLevel"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SendInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendInput($$parsedSource as Partial<SendInput>);
    }
}

/**
 * SettingsInput carries a settings form submission.
 */
export class SettingsInput {
    /**
     * General
     * Theme: "system" | "light" | "dark"
     */
    "theme": string;

    /**
     * Language: "en" | "zh"
     */
    "language": string;

    /**
     * Interface size: "auto" or a px step
     */
    "uiScale": string;

    /**
     * UI font
     */
    "uiFont": string;

    /**
     * Monospace font
     */
    "monospaceFont": string;

    /**
     * Auto-connect to last cluster on startup
     */
    "autoConnectLast": boolean;

    /**
     * How far updates go on their own: "off" | "notify" | "download" | "auto"
     */
    "updatePolicy": string;

    /**
     * Close behaviour: "minimizeToTray" | "quit"
     */
    "closeBehavior": string;

    /**
     * Connection and network
     * Connect timeout (ms)
     */
    "connectTimeoutMs": number;

    /**
     * Request timeout (ms)
     */
    "requestTimeoutMs": number;

    /**
     * Default AccessKey
     */
    "globalAccessKey": string;

    /**
     * Default SecretKey
     */
    "globalSecretKey": string;

    /**
     * Monitoring and alerts
     * Consumer lag alert threshold (0=disabled)
     */
    "lagAlertThreshold": number;

    /**
     * CommitLog disk alert threshold percent (0=disabled)
     */
    "diskAlertThreshold": number;

    /**
     * System notification on new alerts
     */
    "desktopNotifications": boolean;

    /**
     * Messages and display
     * Timezone: "local" | "utc"
     */
    "timezone": string;

    /**
     * Timestamp format: "datetime" | "ms"
     */
    "timestampFormat": string;

    /**
     * Auto-format JSON
     */
    "autoFormatJson": boolean;

    /**
     * Message truncation threshold (bytes)
     */
    "maxPayloadRenderBytes": number;

    /**
     * Page fetch size
     */
    "fetchLimit": number;
    "globalCredentialsMode": string;

    /** Creates a new SettingsInput instance. */
    constructor($$source: Partial<SettingsInput> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("uiScale" in $$source)) {
            this["uiScale"] = "";
        }
        if (!("uiFont" in $$source)) {
            this["uiFont"] = "";
        }
        if (!("monospaceFont" in $$source)) {
            this["monospaceFont"] = "";
        }
        if (!("autoConnectLast" in $$source)) {
            this["autoConnectLast"] = false;
        }
        if (!("updatePolicy" in $$source)) {
            this["updatePolicy"] = "";
        }
        if (!("closeBehavior" in $$source)) {
            this["closeBehavior"] = "";
        }
        if (!("connectTimeoutMs" in $$source)) {
            this["connectTimeoutMs"] = 0;
        }
        if (!("requestTimeoutMs" in $$source)) {
            this["requestTimeoutMs"] = 0;
        }
        if (!("globalAccessKey" in $$source)) {
            this["globalAccessKey"] = "";
        }
        if (!("globalSecretKey" in $$source)) {
            this["globalSecretKey"] = "";
        }
        if (!("lagAlertThreshold" in $$source)) {
            this["lagAlertThreshold"] = 0;
        }
        if (!("diskAlertThreshold" in $$source)) {
            this["diskAlertThreshold"] = 0;
        }
        if (!("desktopNotifications" in $$source)) {
            this["desktopNotifications"] = false;
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }
        if (!("timestampFormat" in $$source)) {
            this["timestampFormat"] = "";
        }
        if (!("autoFormatJson" in $$source)) {
            this["autoFormatJson"] = false;
        }
        if (!("maxPayloadRenderBytes" in $$source)) {
            this["maxPayloadRenderBytes"] = 0;
        }
        if (!("fetchLimit" in $$source)) {
            this["fetchLimit"] = 0;
        }
        if (!("globalCredentialsMode" in $$source)) {
            this["globalCredentialsMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsInput($$parsedSource as Partial<SettingsInput>);
    }
}

/**
 * SettingsView is the settings shape sent to the frontend, with the global ACL
 * credentials replaced by whether they are configured.
 */
export class SettingsView {
    /**
     * General
     * Theme: "system" | "light" | "dark"
     */
    "theme": string;

    /**
     * Language: "en" | "zh"
     */
    "language": string;

    /**
     * Interface size: "auto" or a px step
     */
    "uiScale": string;

    /**
     * UI font
     */
    "uiFont": string;

    /**
     * Monospace font
     */
    "monospaceFont": string;

    /**
     * Auto-connect to last cluster on startup
     */
    "autoConnectLast": boolean;

    /**
     * How far updates go on their own: "off" | "notify" | "download" | "auto"
     */
    "updatePolicy": string;

    /**
     * Close behaviour: "minimizeToTray" | "quit"
     */
    "closeBehavior": string;

    /**
     * Connection and network
     * Connect timeout (ms)
     */
    "connectTimeoutMs": number;

    /**
     * Request timeout (ms)
     */
    "requestTimeoutMs": number;

    /**
     * Default AccessKey
     */
    "globalAccessKey": string;

    /**
     * Default SecretKey
     */
    "globalSecretKey": string;

    /**
     * Monitoring and alerts
     * Consumer lag alert threshold (0=disabled)
     */
    "lagAlertThreshold": number;

    /**
     * CommitLog disk alert threshold percent (0=disabled)
     */
    "diskAlertThreshold": number;

    /**
     * System notification on new alerts
     */
    "desktopNotifications": boolean;

    /**
     * Messages and display
     * Timezone: "local" | "utc"
     */
    "timezone": string;

    /**
     * Timestamp format: "datetime" | "ms"
     */
    "timestampFormat": string;

    /**
     * Auto-format JSON
     */
    "autoFormatJson": boolean;

    /**
     * Message truncation threshold (bytes)
     */
    "maxPayloadRenderBytes": number;

    /**
     * Page fetch size
     */
    "fetchLimit": number;
    "globalAccessKeyConfigured": boolean;
    "globalSecretKeyConfigured": boolean;

    /** Creates a new SettingsView instance. */
    constructor($$source: Partial<SettingsView> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("uiScale" in $$source)) {
            this["uiScale"] = "";
        }
        if (!("uiFont" in $$source)) {
            this["uiFont"] = "";
        }
        if (!("monospaceFont" in $$source)) {
            this["monospaceFont"] = "";
        }
        if (!("autoConnectLast" in $$source)) {
            this["autoConnectLast"] = false;
        }
        if (!("updatePolicy" in $$source)) {
            this["updatePolicy"] = "";
        }
        if (!("closeBehavior" in $$source)) {
            this["closeBehavior"] = "";
        }
        if (!("connectTimeoutMs" in $$source)) {
            this["connectTimeoutMs"] = 0;
        }
        if (!("requestTimeoutMs" in $$source)) {
            this["requestTimeoutMs"] = 0;
        }
        if (!("globalAccessKey" in $$source)) {
            this["globalAccessKey"] = "";
        }
        if (!("globalSecretKey" in $$source)) {
            this["globalSecretKey"] = "";
        }
        if (!("lagAlertThreshold" in $$source)) {
            this["lagAlertThreshold"] = 0;
        }
        if (!("diskAlertThreshold" in $$source)) {
            this["diskAlertThreshold"] = 0;
        }
        if (!("desktopNotifications" in $$source)) {
            this["desktopNotifications"] = false;
        }
        if (!("timezone" in $$source)) {
            this["timezone"] = "";
        }
        if (!("timestampFormat" in $$source)) {
            this["timestampFormat"] = "";
        }
        if (!("autoFormatJson" in $$source)) {
            this["autoFormatJson"] = false;
        }
        if (!("maxPayloadRenderBytes" in $$source)) {
            this["maxPayloadRenderBytes"] = 0;
        }
        if (!("fetchLimit" in $$source)) {
            this["fetchLimit"] = 0;
        }
        if (!("globalAccessKeyConfigured" in $$source)) {
            this["globalAccessKeyConfigured"] = false;
        }
        if (!("globalSecretKeyConfigured" in $$source)) {
            this["globalSecretKeyConfigured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsView instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsView($$parsedSource as Partial<SettingsView>);
    }
}

/**
 * ShellPage is one destination in the active tab's sidebar.
 */
export class ShellPage {
    "id": string;
    "label": string;

    /** Creates a new ShellPage instance. */
    constructor($$source: Partial<ShellPage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShellPage instance from a string or object.
     */
    static createFrom($$source: any = {}): ShellPage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShellPage($$parsedSource as Partial<ShellPage>);
    }
}

/**
 * TopicInput carries a topic form submission.
 */
export class TopicInput {
    "topic": string;
    "brokerAddr": string;
    "readQueue": number;
    "writeQueue": number;
    "perm": string;

    /** Creates a new TopicInput instance. */
    constructor($$source: Partial<TopicInput> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("brokerAddr" in $$source)) {
            this["brokerAddr"] = "";
        }
        if (!("readQueue" in $$source)) {
            this["readQueue"] = 0;
        }
        if (!("writeQueue" in $$source)) {
            this["writeQueue"] = 0;
        }
        if (!("perm" in $$source)) {
            this["perm"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicInput instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopicInput($$parsedSource as Partial<TopicInput>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = PolicyInput.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.ClusterOverview.createFrom;
const $$createType4 = model$0.Node.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
