// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MQTTService exposes what only MQTT has.
 * 
 * It is one service rather than several because it is one family's surface,
 * the same reason KafkaService is one.
 * 
 * Reading retained topics and the broker's nodes is not here. Those are
 * destinations and nodes, and the canonical services already answer them; a
 * second read path would be two sources for one number.
 * 
 * Connected clients are here despite being a canonical model, because there
 * is no canonical service to put them on: client inspection has never had one,
 * and RabbitMQ exposes its own the same way. Adding a shared service for two
 * families to use would be inventing a seam neither asked for.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mqtt$0 from "../driver/mqtt/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BrokerSubscriptions is every filter the broker is holding, across clients.
 */
export function BrokerSubscriptions(connID: number): $CancellablePromise<(mqtt$0.ClientSubscription | null)[]> {
    return $Call.ByID(537826646, connID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ClientSubscriptions is the topic filters one client holds.
 */
export function ClientSubscriptions(connID: number, clientID: string): $CancellablePromise<(mqtt$0.ClientSubscription | null)[]> {
    return $Call.ByID(3289583324, connID, clientID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Clients is who the broker is holding a session for.
 */
export function Clients(connID: number): $CancellablePromise<(model$0.ClientConnection | null)[]> {
    return $Call.ByID(2283137491, connID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * KickClient ends one client's session. MQTT carries no reason on a
 * disconnect, so there is none to pass.
 */
export function KickClient(connID: number, clientID: string): $CancellablePromise<void> {
    return $Call.ByID(3418429124, connID, clientID);
}

/**
 * KickUser ends every session a username holds.
 */
export function KickUser(connID: number, username: string): $CancellablePromise<void> {
    return $Call.ByID(868684656, connID, username);
}

/**
 * PollSubscription drains what arrived after the caller's last sequence.
 */
export function PollSubscription(connID: number, id: string, after: number, limit: number): $CancellablePromise<model$0.LiveBatch | null> {
    return $Call.ByID(3762917869, connID, id, after, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Publish sends a message with everything MQTT can carry.
 */
export function Publish(connID: number, input: $models.MQTTPublishInput): $CancellablePromise<mqtt$0.PublishResult | null> {
    return $Call.ByID(1345607172, connID, input).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * StartSubscription opens a live stream and starts buffering it.
 * 
 * The stream lives on the connection, not on this call: the renderer polls it
 * afterwards and has to stop it when its panel closes, because the
 * subscription is real on the broker until it does.
 */
export function StartSubscription(connID: number, input: $models.MQTTSubscribeInput): $CancellablePromise<model$0.LiveSubscription | null> {
    return $Call.ByID(504085566, connID, input).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * StopSubscription ends a stream and unsubscribes on the broker.
 */
export function StopSubscription(connID: number, id: string): $CancellablePromise<void> {
    return $Call.ByID(547612632, connID, id);
}

/**
 * Subscriptions is what this connection is currently streaming.
 */
export function Subscriptions(connID: number): $CancellablePromise<(model$0.LiveSubscription | null)[]> {
    return $Call.ByID(1067240129, connID).then(($result: any) => {
        return $$createType12($result);
    });
}

// Private type creation functions
const $$createType0 = mqtt$0.ClientSubscription.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.ClientConnection.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.LiveBatch.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = mqtt$0.PublishResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = model$0.LiveSubscription.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
