// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NATSService exposes what only NATS has.
 * 
 * It is one service rather than several because it is one family's surface,
 * the same reason MQTTService and KafkaService are one each.
 * 
 * Reading streams is not here. A stream is a destination and TopicService
 * already answers the whole read side; a second read path would be two sources
 * for one number. What is here is the writing, which the canonical service
 * cannot express: its create collects a broker address, a read queue, a write
 * queue and a permission mask, and a JetStream stream has none of those.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateStream declares a stream that does not exist yet.
 * 
 * Separate from UpdateStream rather than one idempotent call, because the two
 * mistakes they prevent are different: a create that quietly became an update
 * would rewrite another application's subjects, and an update that quietly
 * became a create would hide a stream somebody had deleted underneath the
 * page.
 */
export function CreateStream(connID: number, input: $models.StreamInput): $CancellablePromise<void> {
    return $Call.ByID(4242838671, connID, input);
}

/**
 * DeleteMessages removes messages by sequence.
 */
export function DeleteMessages(connID: number, stream: string, sequences: string[]): $CancellablePromise<model$0.TrimResult | null> {
    return $Call.ByID(1024039200, connID, stream, sequences).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteStream removes a stream and every message in it.
 */
export function DeleteStream(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(866834476, connID, name);
}

/**
 * PurgeStream discards messages from a stream and reports how many went.
 * 
 * The count is the report rather than a formality: it is the only way to tell
 * a bound that already held from one that matched nothing at all, and those
 * look identical on the page.
 */
export function PurgeStream(connID: number, input: $models.PurgeInput): $CancellablePromise<model$0.TrimResult | null> {
    return $Call.ByID(816427434, connID, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateStream rewrites an existing stream's configuration.
 * 
 * Some fields cannot change - storage, and the retention policy of a stream
 * that already holds messages. The server refuses those itself and says which,
 * which is why nothing here pre-empts it: a rule copied into the client is a
 * rule that goes stale a release later.
 */
export function UpdateStream(connID: number, input: $models.StreamInput): $CancellablePromise<void> {
    return $Call.ByID(2515295686, connID, input);
}

// Private type creation functions
const $$createType0 = model$0.TrimResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
