// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NATSService exposes what only NATS has.
 * 
 * It is one service rather than several because it is one family's surface,
 * the same reason MQTTService and KafkaService are one each.
 * 
 * Reading streams is not here. A stream is a destination and TopicService
 * already answers the whole read side; a second read path would be two sources
 * for one number. What is here is the writing, which the canonical service
 * cannot express: its create collects a broker address, a read queue, a write
 * queue and a permission mask, and a JetStream stream has none of those.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as nats$0 from "../driver/nats/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Census counts what the account holds.
 */
export function Census(connID: number): $CancellablePromise<model$0.BrokerCensus | null> {
    return $Call.ByID(2922778064, connID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CloseConnection disconnects one client.
 * 
 * The name is the server holding it and its client id, joined - neither half
 * addresses a connection on its own, because a client id counts within one
 * server and two servers in a cluster each have a client 7.
 */
export function CloseConnection(connID: number, name: string, reason: string): $CancellablePromise<void> {
    return $Call.ByID(4196798545, connID, name, reason);
}

/**
 * CloseUserConnections closes every connection one identity holds, which is
 * how an application with several instances is actually evicted.
 */
export function CloseUserConnections(connID: number, user: string, reason: string): $CancellablePromise<void> {
    return $Call.ByID(2810335975, connID, user, reason);
}

/**
 * Connections lists the sockets open against the cluster.
 * 
 * Here rather than on a canonical service because there is none: client
 * inspection has never had one, and MQTT and RabbitMQ each expose their own
 * for the same reason. Adding a shared service for three families to use would
 * be inventing a seam none of them asked for.
 */
export function Connections(connID: number, account: string): $CancellablePromise<(model$0.ClientConnection | null)[]> {
    return $Call.ByID(1158508356, connID, account).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * CreateConsumer declares a consumer that does not exist yet.
 */
export function CreateConsumer(connID: number, input: $models.NATSConsumerInput): $CancellablePromise<void> {
    return $Call.ByID(1430825063, connID, input);
}

/**
 * CreateStream declares a stream that does not exist yet.
 * 
 * Separate from UpdateStream rather than one idempotent call, because the two
 * mistakes they prevent are different: a create that quietly became an update
 * would rewrite another application's subjects, and an update that quietly
 * became a create would hide a stream somebody had deleted underneath the
 * page.
 */
export function CreateStream(connID: number, input: $models.StreamInput): $CancellablePromise<void> {
    return $Call.ByID(4242838671, connID, input);
}

/**
 * DeleteConsumer removes a consumer and the position it held.
 */
export function DeleteConsumer(connID: number, stream: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2165136952, connID, stream, name);
}

/**
 * DeleteMessages removes messages by sequence.
 */
export function DeleteMessages(connID: number, stream: string, sequences: string[]): $CancellablePromise<model$0.TrimResult | null> {
    return $Call.ByID(1024039200, connID, stream, sequences).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * DeleteStream removes a stream and every message in it.
 */
export function DeleteStream(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(866834476, connID, name);
}

/**
 * Health runs the server's own checks.
 * 
 * Three of them rather than one, because /healthz answers a different question
 * per set of parameters: a server can be up and serving core NATS perfectly
 * while its JetStream assets are still being recovered, and an operator needs
 * to know which part is unhealthy.
 */
export function Health(connID: number): $CancellablePromise<model$0.BrokerHealth | null> {
    return $Call.ByID(3003156433, connID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * PollSubscription drains what has arrived since the caller's cursor.
 */
export function PollSubscription(connID: number, id: string, after: number, limit: number): $CancellablePromise<model$0.LiveBatch | null> {
    return $Call.ByID(2853870003, connID, id, after, limit).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Publish sends a message and reports what the server said, which depends on
 * how much was asked of it.
 */
export function Publish(connID: number, input: $models.NATSPublishInput): $CancellablePromise<nats$0.PublishResult | null> {
    return $Call.ByID(852775886, connID, input).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * PurgeStream discards messages from a stream and reports how many went.
 * 
 * The count is the report rather than a formality: it is the only way to tell
 * a bound that already held from one that matched nothing at all, and those
 * look identical on the page.
 */
export function PurgeStream(connID: number, input: $models.PurgeInput): $CancellablePromise<model$0.TrimResult | null> {
    return $Call.ByID(816427434, connID, input).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * StartSubscription begins following one or more subjects.
 */
export function StartSubscription(connID: number, input: $models.NATSSubscribeInput): $CancellablePromise<model$0.LiveSubscription | null> {
    return $Call.ByID(1106287356, connID, input).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * StopSubscription ends one. Not optional: it lives on the server until it is
 * stopped.
 */
export function StopSubscription(connID: number, id: string): $CancellablePromise<void> {
    return $Call.ByID(2584103042, connID, id);
}

/**
 * Subscriptions is what is running.
 */
export function Subscriptions(connID: number): $CancellablePromise<(model$0.LiveSubscription | null)[]> {
    return $Call.ByID(3948587227, connID).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * UpdateConsumer rewrites an existing consumer's configuration.
 * 
 * Not its position: the server refuses to change where a consumer starts once
 * it exists, and the only way to move one is to delete it and make another -
 * which changes its identity and drops what it had acknowledged.
 */
export function UpdateConsumer(connID: number, input: $models.NATSConsumerInput): $CancellablePromise<void> {
    return $Call.ByID(873423062, connID, input);
}

/**
 * UpdateStream rewrites an existing stream's configuration.
 * 
 * Some fields cannot change - storage, and the retention policy of a stream
 * that already holds messages. The server refuses those itself and says which,
 * which is why nothing here pre-empts it: a rule copied into the client is a
 * rule that goes stale a release later.
 */
export function UpdateStream(connID: number, input: $models.StreamInput): $CancellablePromise<void> {
    return $Call.ByID(2515295686, connID, input);
}

/**
 * Usage reads the account's JetStream meters, limits included.
 * 
 * The limits travel with the usage because a meter needs both, and -1 is how
 * the server spells "no cap" - a bar drawn against -1 can never move, so the
 * page has to be able to tell that from a limit of zero.
 */
export function Usage(connID: number): $CancellablePromise<nats$0.AccountUsage | null> {
    return $Call.ByID(4276773670, connID).then(($result: any) => {
        return $$createType17($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.BrokerCensus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ClientConnection.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = model$0.TrimResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = model$0.BrokerHealth.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = model$0.LiveBatch.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = nats$0.PublishResult.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = model$0.LiveSubscription.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = nats$0.AccountUsage.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
