// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PulsarService exposes what only Pulsar has.
 * 
 * It is one service rather than several because it is one family's surface:
 * splitting tenants, the send console and schema into three would put three
 * names in the bindings for what a reader thinks of as "the Pulsar pages".
 * 
 * Reading topics, subscriptions, namespaces and brokers is not here. Those are
 * destinations, subscriptions, namespaces and nodes, and the canonical
 * services already answer them; a second read path would be two sources for
 * one number.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Clusters is what the tenant form offers for its allowed-cluster list.
 */
export function Clusters(connID: number): $CancellablePromise<string[]> {
    return $Call.ByID(3709877861, connID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateNamespace adds one under the profile's tenant.
 */
export function CreateNamespace(connID: number, input: $models.PulsarNamespaceInput): $CancellablePromise<void> {
    return $Call.ByID(666421189, connID, input);
}

/**
 * CreateSubscription adds one to a topic.
 * 
 * startAt is "earliest" or "latest". Earliest is the default because a
 * subscription created at the latest position silently discards whatever is
 * already on the topic, which is the opposite of why one is created ahead of
 * the consumer that will use it.
 */
export function CreateSubscription(connID: number, topic: string, subscription: string, startAt: string): $CancellablePromise<void> {
    return $Call.ByID(686098651, connID, topic, subscription, startAt);
}

/**
 * CreateTopic declares a topic.
 */
export function CreateTopic(connID: number, input: $models.PulsarTopicInput): $CancellablePromise<void> {
    return $Call.ByID(1503351697, connID, input);
}

/**
 * DeadLetterQueues finds the topics dead letters land in, and the subscription
 * each of them came from.
 * 
 * A Pulsar dead-letter topic is a naming convention in the client libraries,
 * not a broker object, so this walks the namespace for names that follow it.
 * One whose origin topic is gone is reported without a source rather than
 * dropped: it holds a backlog nothing will drain, which is the row most worth
 * seeing.
 */
export function DeadLetterQueues(connID: number, $namespace: string): $CancellablePromise<(model$0.DeadLetterQueue | null)[]> {
    return $Call.ByID(3362966780, connID, $namespace).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DeleteNamespace removes one. Pulsar refuses while it still holds topics, and
 * that refusal reaches the user rather than being forced through.
 */
export function DeleteNamespace(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(882977176, connID, name);
}

/**
 * DeleteSubscription removes one. Pulsar refuses while a consumer is attached,
 * and that refusal reaches the user.
 */
export function DeleteSubscription(connID: number, topic: string, subscription: string): $CancellablePromise<void> {
    return $Call.ByID(425603228, connID, topic, subscription);
}

/**
 * DeleteTopic removes one. Pulsar refuses while a producer or consumer is
 * still attached, and that refusal reaches the user.
 */
export function DeleteTopic(connID: number, $namespace: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1055217916, connID, $namespace, name);
}

/**
 * Namespaces returns every namespace under the profile's tenant, with the
 * limits that are actually set on it.
 */
export function Namespaces(connID: number): $CancellablePromise<(model$0.Namespace | null)[]> {
    return $Call.ByID(1291508398, connID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * RaisePartitions adds partitions to a partitioned topic. Pulsar cannot remove
 * them, and cannot partition a topic that was created without partitions.
 */
export function RaisePartitions(connID: number, input: $models.PulsarTopicInput): $CancellablePromise<void> {
    return $Call.ByID(1275442749, connID, input);
}

/**
 * RemoveNamespaceLimit hands a limit back to the broker's own default. Not the
 * same as setting zero: zero producers is a namespace nothing can publish to.
 */
export function RemoveNamespaceLimit(connID: number, name: string, limit: string): $CancellablePromise<void> {
    return $Call.ByID(3006484580, connID, name, limit);
}

/**
 * RemoveTenant deletes one. Pulsar refuses while it still holds namespaces,
 * and that refusal reaches the user rather than being forced through.
 */
export function RemoveTenant(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2981887270, connID, name);
}

/**
 * SaveTenant creates a tenant or updates the one already there.
 */
export function SaveTenant(connID: number, input: $models.PulsarTenantInput): $CancellablePromise<void> {
    return $Call.ByID(3456165039, connID, input);
}

/**
 * SetNamespaceLimit caps a namespace as a whole.
 */
export function SetNamespaceLimit(connID: number, name: string, limit: string, value: number): $CancellablePromise<void> {
    return $Call.ByID(4201704584, connID, name, limit, value);
}

/**
 * SubscriptionClients is who is attached, as the broker reports them. No round
 * trip to any consumer: Pulsar carries their permits and rates in the topic's
 * own stats.
 */
export function SubscriptionClients(connID: number, topic: string, subscription: string): $CancellablePromise<(model$0.SubscriptionClient | null)[]> {
    return $Call.ByID(1693229665, connID, topic, subscription).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * SubscriptionStats is one subscription's figures.
 * 
 * Topic-scoped, which ConsumerService.Stats is not: it builds a ref with an
 * empty namespace, and a Pulsar subscription has no identity without the topic
 * it belongs to.
 */
export function SubscriptionStats(connID: number, topic: string, subscription: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2895460458, connID, topic, subscription).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Tenants lists every tenant on the cluster.
 */
export function Tenants(connID: number): $CancellablePromise<($models.PulsarTenantView | null)[]> {
    return $Call.ByID(3205204843, connID).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * TopicDetail is one topic in one namespace.
 */
export function TopicDetail(connID: number, $namespace: string, name: string): $CancellablePromise<model$0.Destination | null> {
    return $Call.ByID(1962758660, connID, $namespace, name).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * TopicStats is the per-partition breakdown the detail panel draws.
 */
export function TopicStats(connID: number, $namespace: string, name: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1539980380, connID, $namespace, name).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Topics returns every topic in one namespace.
 * 
 * Namespace-scoped, which TopicService is not: a Pulsar topic is addressed as
 * tenant/namespace/name, and the canonical service's Detail builds a ref with
 * no namespace in it at all.
 */
export function Topics(connID: number, $namespace: string, includeInternal: boolean): $CancellablePromise<(model$0.Destination | null)[]> {
    return $Call.ByID(447707186, connID, $namespace, includeInternal).then(($result: any) => {
        return $$createType16($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = model$0.DeadLetterQueue.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.Namespace.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = model$0.SubscriptionClient.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = $models.PulsarTenantView.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = model$0.Destination.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($$createType15);
