// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RabbitMQService exposes what only RabbitMQ has.
 * 
 * It is one service rather than several because it is one family's surface:
 * splitting virtual hosts, policies and the broker census into three would put
 * three names in the bindings for what a reader thinks of as "the RabbitMQ
 * pages".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * Census returns the broker's running totals: object counts, queued depth and
 * message rates for the whole cluster.
 * 
 * Nil means nothing is connected, which the overview renders as its own state
 * rather than as an error.
 */
export function Census(connID: number): $CancellablePromise<model$0.BrokerCensus | null> {
    return $Call.ByID(3727010242, connID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClientChannels returns the channels multiplexed inside those connections.
 */
export function ClientChannels(connID: number, $namespace: string): $CancellablePromise<(model$0.ClientChannel | null)[]> {
    return $Call.ByID(2651318602, connID, $namespace).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ClientConnections returns the transport connections open against the broker.
 */
export function ClientConnections(connID: number, $namespace: string): $CancellablePromise<(model$0.ClientConnection | null)[]> {
    return $Call.ByID(1012970279, connID, $namespace).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * DeadLetterQueues finds the queues dead letters land in, and the queues that
 * feed each one.
 */
export function DeadLetterQueues(connID: number, $namespace: string): $CancellablePromise<(model$0.DeadLetterQueue | null)[]> {
    return $Call.ByID(3828160863, connID, $namespace).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Health runs the broker's own checks, and reads its feature flags and the
 * deprecated features it still allows.
 */
export function Health(connID: number): $CancellablePromise<model$0.BrokerHealth | null> {
    return $Call.ByID(483013203, connID).then(($result: any) => {
        return $$createType12($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.BrokerCensus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ClientChannel.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = model$0.ClientConnection.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = model$0.DeadLetterQueue.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = model$0.BrokerHealth.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
