// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RabbitMQService exposes what only RabbitMQ has.
 * 
 * It is one service rather than several because it is one family's surface:
 * splitting virtual hosts, policies and the broker census into three would put
 * three names in the bindings for what a reader thinks of as "the RabbitMQ
 * pages".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Census returns the broker's running totals: object counts, queued depth and
 * message rates for the whole cluster.
 * 
 * Nil means nothing is connected, which the overview renders as its own state
 * rather than as an error.
 */
export function Census(connID: number): $CancellablePromise<model$0.BrokerCensus | null> {
    return $Call.ByID(3727010242, connID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClientChannels returns the channels multiplexed inside those connections.
 */
export function ClientChannels(connID: number, $namespace: string): $CancellablePromise<(model$0.ClientChannel | null)[]> {
    return $Call.ByID(2651318602, connID, $namespace).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ClientConnections returns the transport connections open against the broker.
 */
export function ClientConnections(connID: number, $namespace: string): $CancellablePromise<(model$0.ClientConnection | null)[]> {
    return $Call.ByID(1012970279, connID, $namespace).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * CloseClientConnection disconnects one connection. The reason reaches the
 * client being disconnected and the broker's log.
 */
export function CloseClientConnection(connID: number, name: string, reason: string): $CancellablePromise<void> {
    return $Call.ByID(3084805880, connID, name, reason);
}

/**
 * CloseUserConnections disconnects every connection one user holds, which is
 * how an application running several instances is evicted.
 */
export function CloseUserConnections(connID: number, username: string, reason: string): $CancellablePromise<void> {
    return $Call.ByID(2721346829, connID, username, reason);
}

/**
 * DeadLetterQueues finds the queues dead letters land in, and the queues that
 * feed each one.
 */
export function DeadLetterQueues(connID: number, $namespace: string): $CancellablePromise<(model$0.DeadLetterQueue | null)[]> {
    return $Call.ByID(3828160863, connID, $namespace).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * DeclareBinding routes an exchange to a queue or to another exchange.
 */
export function DeclareBinding(connID: number, input: $models.BindingInput): $CancellablePromise<void> {
    return $Call.ByID(2458090782, connID, input);
}

/**
 * DeclareExchange creates an exchange.
 */
export function DeclareExchange(connID: number, input: $models.ExchangeInput): $CancellablePromise<void> {
    return $Call.ByID(3355486020, connID, input);
}

/**
 * DeclareQueue creates a queue.
 */
export function DeclareQueue(connID: number, input: $models.QueueInput): $CancellablePromise<void> {
    return $Call.ByID(2471359076, connID, input);
}

/**
 * Definitions returns the broker's topology as one document, with a count of
 * what it holds. An empty vhost exports the whole broker.
 */
export function Definitions(connID: number, vhost: string): $CancellablePromise<model$0.Definitions | null> {
    return $Call.ByID(2606156981, connID, vhost).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * DeleteBinding removes one binding.
 */
export function DeleteBinding(connID: number, input: $models.BindingInput): $CancellablePromise<void> {
    return $Call.ByID(2772532011, connID, input);
}

/**
 * DeleteExchange removes an exchange, and its bindings with it.
 */
export function DeleteExchange(connID: number, vhost: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3256463559, connID, vhost, name);
}

/**
 * DeleteFederationUpstream removes an upstream, stopping its links.
 */
export function DeleteFederationUpstream(connID: number, vhost: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(1372449806, connID, vhost, name);
}

/**
 * DeleteIdentity removes a user, its permissions and its open connections.
 */
export function DeleteIdentity(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2155514932, connID, name);
}

/**
 * DeleteNamespace removes a virtual host and everything inside it.
 */
export function DeleteNamespace(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3210944853, connID, name);
}

/**
 * DeletePolicy removes one. Every destination it applied to reverts at once.
 */
export function DeletePolicy(connID: number, vhost: string, name: string, operator: boolean): $CancellablePromise<void> {
    return $Call.ByID(3230703960, connID, vhost, name, operator);
}

/**
 * DeleteQueue removes a queue and everything in it.
 * 
 * ifUnused and ifEmpty are the broker's own preconditions. They are checked
 * where the delete happens, which is the only place they can be checked
 * without a race.
 */
export function DeleteQueue(connID: number, vhost: string, name: string, ifUnused: boolean, ifEmpty: boolean): $CancellablePromise<void> {
    return $Call.ByID(1602678449, connID, vhost, name, ifUnused, ifEmpty);
}

/**
 * DeleteRuntimeParameter removes one component's stored configuration.
 */
export function DeleteRuntimeParameter(connID: number, component: string, vhost: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(926421657, connID, component, vhost, name);
}

/**
 * DeleteShovel removes a shovel, stopping it.
 */
export function DeleteShovel(connID: number, vhost: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(878180193, connID, vhost, name);
}

/**
 * DropMessages discards a bounded batch from the head of a queue and reports
 * how many are gone. There is no undo.
 */
export function DropMessages(connID: number, vhost: string, name: string, limit: number): $CancellablePromise<number> {
    return $Call.ByID(1134307524, connID, vhost, name, limit);
}

/**
 * ExportDefinitionsToFile prompts for a destination and writes the document
 * there. It returns the written path, or an empty string when the user
 * cancels.
 * 
 * The dialog is here rather than in the renderer because that is where the
 * application's window lives; the same pattern serves the settings export.
 */
export function ExportDefinitionsToFile(connID: number, vhost: string): $CancellablePromise<string> {
    return $Call.ByID(3493034352, connID, vhost);
}

/**
 * FederationUpstreams returns the brokers this one federates from, with their
 * links' state.
 */
export function FederationUpstreams(connID: number): $CancellablePromise<(model$0.FederationUpstream | null)[]> {
    return $Call.ByID(1567088666, connID).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * Health runs the broker's own checks, and reads its feature flags and the
 * deprecated features it still allows.
 */
export function Health(connID: number): $CancellablePromise<model$0.BrokerHealth | null> {
    return $Call.ByID(483013203, connID).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * Identities returns every user with its per-namespace permissions.
 */
export function Identities(connID: number): $CancellablePromise<(model$0.Identity | null)[]> {
    return $Call.ByID(2632006727, connID).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * ImportDefinitions applies a document. An empty vhost applies it broker-wide.
 */
export function ImportDefinitions(connID: number, vhost: string, document: string): $CancellablePromise<void> {
    return $Call.ByID(2982960286, connID, vhost, document);
}

/**
 * MatchingPolicies asks the broker which policies actually apply to one
 * destination. Only the highest-priority match does, and they do not merge.
 */
export function MatchingPolicies(connID: number, vhost: string, name: string, kind: string): $CancellablePromise<(model$0.Policy | null)[]> {
    return $Call.ByID(4267174108, connID, vhost, name, kind).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * MoveMessages returns how many reached the target, which is meaningful even
 * when the call also returns an error: that count already moved.
 */
export function MoveMessages(connID: number, input: $models.MoveInput): $CancellablePromise<number> {
    return $Call.ByID(3802146380, connID, input);
}

/**
 * Namespaces returns every virtual host with its limits.
 */
export function Namespaces(connID: number): $CancellablePromise<(model$0.Namespace | null)[]> {
    return $Call.ByID(2045585925, connID).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * Policies returns both user and operator policies, marked apart.
 */
export function Policies(connID: number): $CancellablePromise<(model$0.Policy | null)[]> {
    return $Call.ByID(1992342523, connID).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * Publish sends a message and reports how many the broker kept and how many it
 * handed back as unroutable. Those are two different facts.
 */
export function Publish(connID: number, input: $models.PublishInput): $CancellablePromise<model$0.PublishResult | null> {
    return $Call.ByID(718367916, connID, input).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * PurgeQueue drops everything a queue is holding. There is no undo.
 */
export function PurgeQueue(connID: number, vhost: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(4123808287, connID, vhost, name);
}

/**
 * ReadDefinitionsFile prompts for a file and reports what is in it.
 * 
 * Reading and applying are separate steps on purpose: the document is opaque,
 * and a count of what it will create is the only review anyone can actually
 * perform before it lands on a cluster.
 */
export function ReadDefinitionsFile(): $CancellablePromise<$models.DefinitionsPreview | null> {
    return $Call.ByID(998757875).then(($result: any) => {
        return $$createType30($result);
    });
}

/**
 * RebalanceQueues spreads quorum queue leaders back across the nodes.
 */
export function RebalanceQueues(connID: number): $CancellablePromise<void> {
    return $Call.ByID(3409348108, connID);
}

/**
 * RevokePermission removes the permission record entirely, which stops the
 * identity connecting to that virtual host at all - not the same as granting
 * nothing.
 */
export function RevokePermission(connID: number, vhost: string, identity: string): $CancellablePromise<void> {
    return $Call.ByID(875321072, connID, vhost, identity);
}

/**
 * RevokeTopicPermission lifts the narrowing, leaving the namespace permissions
 * alone.
 */
export function RevokeTopicPermission(connID: number, vhost: string, identity: string): $CancellablePromise<void> {
    return $Call.ByID(2781287781, connID, vhost, identity);
}

/**
 * RuntimeParameters returns the component configuration the broker stores for
 * its plugins - shovels and federation upstreams live here.
 */
export function RuntimeParameters(connID: number): $CancellablePromise<(model$0.RuntimeParameter | null)[]> {
    return $Call.ByID(2741188367, connID).then(($result: any) => {
        return $$createType33($result);
    });
}

/**
 * SaveIdentity creates a user or updates one.
 */
export function SaveIdentity(connID: number, input: $models.IdentityInput): $CancellablePromise<void> {
    return $Call.ByID(2854585134, connID, input);
}

/**
 * SaveNamespace creates a virtual host, or updates one that already exists.
 */
export function SaveNamespace(connID: number, input: $models.NamespaceInput): $CancellablePromise<void> {
    return $Call.ByID(2223265787, connID, input);
}

/**
 * SavePolicy creates a policy or replaces one of the same name.
 */
export function SavePolicy(connID: number, input: $models.RabbitPolicyInput): $CancellablePromise<void> {
    return $Call.ByID(915666862, connID, input);
}

/**
 * SetNamespaceLimit caps a virtual host. A negative value lifts the cap, which
 * is not the same as a cap of zero - zero forbids everything.
 */
export function SetNamespaceLimit(connID: number, name: string, limit: string, value: number): $CancellablePromise<void> {
    return $Call.ByID(630753097, connID, name, limit, value);
}

/**
 * SetPermission grants an identity rights inside one namespace.
 */
export function SetPermission(connID: number, input: $models.PermissionInput): $CancellablePromise<void> {
    return $Call.ByID(1852237624, connID, input);
}

/**
 * SetTopicPermission narrows write and read on one topic exchange.
 */
export function SetTopicPermission(connID: number, input: $models.TopicPermissionInput): $CancellablePromise<void> {
    return $Call.ByID(646115197, connID, input);
}

/**
 * Shovels returns every shovel with the state the broker reports for it. The
 * URIs come back with their passwords removed.
 */
export function Shovels(connID: number): $CancellablePromise<(model$0.Shovel | null)[]> {
    return $Call.ByID(644647587, connID).then(($result: any) => {
        return $$createType36($result);
    });
}

/**
 * StreamClients returns who is attached to a stream over the stream protocol,
 * which is nobody the AMQP consumer list would ever mention.
 */
export function StreamClients(connID: number, vhost: string, name: string): $CancellablePromise<model$0.StreamClients | null> {
    return $Call.ByID(2768359987, connID, vhost, name).then(($result: any) => {
        return $$createType38($result);
    });
}

/**
 * TopicPermissions returns the per-exchange narrowing on top of the namespace
 * permissions.
 */
export function TopicPermissions(connID: number): $CancellablePromise<(model$0.TopicPermission | null)[]> {
    return $Call.ByID(1841620516, connID).then(($result: any) => {
        return $$createType41($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.BrokerCensus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ClientChannel.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = model$0.ClientConnection.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = model$0.DeadLetterQueue.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = model$0.Definitions.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = model$0.FederationUpstream.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = model$0.BrokerHealth.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = model$0.Identity.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = model$0.Policy.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = model$0.Namespace.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = model$0.PublishResult.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = $models.DefinitionsPreview.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = model$0.RuntimeParameter.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = model$0.Shovel.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = model$0.StreamClients.createFrom;
const $$createType38 = $Create.Nullable($$createType37);
const $$createType39 = model$0.TopicPermission.createFrom;
const $$createType40 = $Create.Nullable($$createType39);
const $$createType41 = $Create.Array($$createType40);
