// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RedisStreamService exposes what only Redis Streams has.
 * 
 * It is one service rather than several because it is one family's surface:
 * splitting trimming, the pending list and the server's own figures into three
 * would put three names in the bindings for what a reader thinks of as "the
 * Redis pages".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AckEntries settles entries so they stop being owed, and reports how many
 * were actually owed - which is not how many were named.
 */
export function AckEntries(connID: number, stream: string, group: string, ids: string[]): $CancellablePromise<model$0.AckResult | null> {
    return $Call.ByID(496926891, connID, stream, group, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AclCategories are the command groups rules are written in terms of. They
 * differ by server version, so the form offers what the server reports.
 */
export function AclCategories(connID: number): $CancellablePromise<string[]> {
    return $Call.ByID(978512212, connID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * AclUsers lists the principals the server authenticates.
 */
export function AclUsers(connID: number): $CancellablePromise<(model$0.AclUser | null)[]> {
    return $Call.ByID(3951763496, connID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * AddEntry writes to a stream and returns the ids the server assigned.
 * 
 * The ids rather than a count: an id is the only handle on an entry, so a
 * console that reported "sent 5" would leave the user unable to find any of
 * them.
 */
export function AddEntry(connID: number, input: $models.EntryInput): $CancellablePromise<model$0.StreamAddResult | null> {
    return $Call.ByID(870285481, connID, input).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * AutoClaim moves whatever has been idle too long and reports what it found
 * gone as well as what it moved.
 */
export function AutoClaim(connID: number, input: $models.AutoClaimInput): $CancellablePromise<model$0.ClaimResult | null> {
    return $Call.ByID(2064203517, connID, input).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ClaimEntries moves named entries to another consumer.
 */
export function ClaimEntries(connID: number, input: $models.ClaimInput): $CancellablePromise<model$0.ClaimResult | null> {
    return $Call.ByID(220908984, connID, input).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ClientConnections lists what is connected to the server.
 */
export function ClientConnections(connID: number): $CancellablePromise<(model$0.ClientConnection | null)[]> {
    return $Call.ByID(1103629136, connID).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * CloseClient disconnects one client.
 * 
 * It takes the connection's id rather than its address: Redis kills by either,
 * and an address is reused the moment its port is - so a client that
 * reconnected between the page being drawn and the button being pressed would
 * be killed in place of the one the operator meant.
 */
export function CloseClient(connID: number, id: string): $CancellablePromise<void> {
    return $Call.ByID(3883244311, connID, id);
}

/**
 * CloseUserClients disconnects every connection one identity holds.
 */
export function CloseUserClients(connID: number, username: string): $CancellablePromise<void> {
    return $Call.ByID(544453405, connID, username);
}

/**
 * CreateGroup declares a consumer group on a stream.
 */
export function CreateGroup(connID: number, input: $models.GroupInput): $CancellablePromise<void> {
    return $Call.ByID(3890704243, connID, input);
}

/**
 * DeleteEntries removes named entries and reports how many were there to
 * remove, which is not the same as how many were asked for.
 */
export function DeleteEntries(connID: number, stream: string, ids: string[]): $CancellablePromise<model$0.TrimResult | null> {
    return $Call.ByID(3902121557, connID, stream, ids).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * DeleteGroup destroys a consumer group and the pending entries it holds.
 */
export function DeleteGroup(connID: number, stream: string, group: string): $CancellablePromise<void> {
    return $Call.ByID(1274717142, connID, stream, group);
}

/**
 * GroupConsumers lists a group's members and how long each has been quiet.
 */
export function GroupConsumers(connID: number, stream: string, group: string): $CancellablePromise<(model$0.GroupConsumer | null)[]> {
    return $Call.ByID(2477625508, connID, stream, group).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * PendingEntries walks a group's pending list.
 */
export function PendingEntries(connID: number, input: $models.PendingQueryInput): $CancellablePromise<(model$0.PendingEntry | null)[]> {
    return $Call.ByID(617713621, connID, input).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * PendingSummary returns a group's pending list at a glance.
 */
export function PendingSummary(connID: number, stream: string, group: string): $CancellablePromise<model$0.PendingSummary | null> {
    return $Call.ByID(932081609, connID, stream, group).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * RemoveAclUser deletes a user. Redis closes whatever was authenticated as it.
 */
export function RemoveAclUser(connID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(1927758299, connID, name);
}

/**
 * SaveAclUser creates or replaces a user.
 * 
 * Replaces: the server's own SETUSER is additive, so an edit that removed a
 * key pattern would leave it in place and the form would be lying about what
 * it saved.
 */
export function SaveAclUser(connID: number, input: $models.AclUserInput): $CancellablePromise<void> {
    return $Call.ByID(1225375772, connID, input);
}

/**
 * SetGroupPosition moves a consumer group to an entry id, to "0" for the
 * beginning of what the stream still holds, or to "$" for whatever arrives
 * next.
 */
export function SetGroupPosition(connID: number, stream: string, group: string, position: string): $CancellablePromise<void> {
    return $Call.ByID(4179560028, connID, stream, group, position);
}

/**
 * SlowLog reads the record a server keeps of its slowest commands.
 * 
 * It is not on ClusterService because no other family has one: what a node is
 * running with is a shared question, what has been slow on it is Redis's.
 */
export function SlowLog(connID: number, address: string, limit: number): $CancellablePromise<(model$0.SlowLogEntry | null)[]> {
    return $Call.ByID(1637452301, connID, address, limit).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * Trim discards entries from the head of a stream and reports how many went.
 */
export function Trim(connID: number, input: $models.TrimInput): $CancellablePromise<model$0.TrimResult | null> {
    return $Call.ByID(2317148112, connID, input).then(($result: any) => {
        return $$createType14($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.AckResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = model$0.AclUser.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.StreamAddResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.ClaimResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = model$0.ClientConnection.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = model$0.TrimResult.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = model$0.GroupConsumer.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = model$0.PendingEntry.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = model$0.PendingSummary.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = model$0.SlowLogEntry.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $Create.Array($$createType24);
