// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RedisStreamService exposes what only Redis Streams has.
 * 
 * It is one service rather than several because it is one family's surface:
 * splitting trimming, the pending list and the server's own figures into three
 * would put three names in the bindings for what a reader thinks of as "the
 * Redis pages".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AckEntries settles entries so they stop being owed, and reports how many
 * were actually owed - which is not how many were named.
 */
export function AckEntries(connID: number, stream: string, group: string, ids: string[]): $CancellablePromise<model$0.AckResult | null> {
    return $Call.ByID(496926891, connID, stream, group, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AddEntry writes to a stream and returns the ids the server assigned.
 * 
 * The ids rather than a count: an id is the only handle on an entry, so a
 * console that reported "sent 5" would leave the user unable to find any of
 * them.
 */
export function AddEntry(connID: number, input: $models.EntryInput): $CancellablePromise<model$0.StreamAddResult | null> {
    return $Call.ByID(870285481, connID, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * AutoClaim moves whatever has been idle too long and reports what it found
 * gone as well as what it moved.
 */
export function AutoClaim(connID: number, input: $models.AutoClaimInput): $CancellablePromise<model$0.ClaimResult | null> {
    return $Call.ByID(2064203517, connID, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ClaimEntries moves named entries to another consumer.
 */
export function ClaimEntries(connID: number, input: $models.ClaimInput): $CancellablePromise<model$0.ClaimResult | null> {
    return $Call.ByID(220908984, connID, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * CreateGroup declares a consumer group on a stream.
 */
export function CreateGroup(connID: number, input: $models.GroupInput): $CancellablePromise<void> {
    return $Call.ByID(3890704243, connID, input);
}

/**
 * DeleteEntries removes named entries and reports how many were there to
 * remove, which is not the same as how many were asked for.
 */
export function DeleteEntries(connID: number, stream: string, ids: string[]): $CancellablePromise<model$0.TrimResult | null> {
    return $Call.ByID(3902121557, connID, stream, ids).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * DeleteGroup destroys a consumer group and the pending entries it holds.
 */
export function DeleteGroup(connID: number, stream: string, group: string): $CancellablePromise<void> {
    return $Call.ByID(1274717142, connID, stream, group);
}

/**
 * GroupConsumers lists a group's members and how long each has been quiet.
 */
export function GroupConsumers(connID: number, stream: string, group: string): $CancellablePromise<(model$0.GroupConsumer | null)[]> {
    return $Call.ByID(2477625508, connID, stream, group).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * PendingEntries walks a group's pending list.
 */
export function PendingEntries(connID: number, input: $models.PendingQueryInput): $CancellablePromise<(model$0.PendingEntry | null)[]> {
    return $Call.ByID(617713621, connID, input).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * PendingSummary returns a group's pending list at a glance.
 */
export function PendingSummary(connID: number, stream: string, group: string): $CancellablePromise<model$0.PendingSummary | null> {
    return $Call.ByID(932081609, connID, stream, group).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SetGroupPosition moves a consumer group to an entry id, to "0" for the
 * beginning of what the stream still holds, or to "$" for whatever arrives
 * next.
 */
export function SetGroupPosition(connID: number, stream: string, group: string, position: string): $CancellablePromise<void> {
    return $Call.ByID(4179560028, connID, stream, group, position);
}

/**
 * Trim discards entries from the head of a stream and reports how many went.
 */
export function Trim(connID: number, input: $models.TrimInput): $CancellablePromise<model$0.TrimResult | null> {
    return $Call.ByID(2317148112, connID, input).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.AckResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.StreamAddResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ClaimResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.TrimResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.GroupConsumer.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = model$0.PendingEntry.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = model$0.PendingSummary.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
