// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RedisStreamService exposes what only Redis Streams has.
 * 
 * It is one service rather than several because it is one family's surface:
 * splitting trimming, the pending list and the server's own figures into three
 * would put three names in the bindings for what a reader thinks of as "the
 * Redis pages".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateGroup declares a consumer group on a stream.
 */
export function CreateGroup(connID: number, input: $models.GroupInput): $CancellablePromise<void> {
    return $Call.ByID(3890704243, connID, input);
}

/**
 * DeleteEntries removes named entries and reports how many were there to
 * remove, which is not the same as how many were asked for.
 */
export function DeleteEntries(connID: number, stream: string, ids: string[]): $CancellablePromise<model$0.TrimResult | null> {
    return $Call.ByID(3902121557, connID, stream, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteGroup destroys a consumer group and the pending entries it holds.
 */
export function DeleteGroup(connID: number, stream: string, group: string): $CancellablePromise<void> {
    return $Call.ByID(1274717142, connID, stream, group);
}

/**
 * Trim discards entries from the head of a stream and reports how many went.
 */
export function Trim(connID: number, input: $models.TrimInput): $CancellablePromise<model$0.TrimResult | null> {
    return $Call.ByID(2317148112, connID, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.TrimResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
