// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ShellService receives what the renderer is currently showing.
 * 
 * The tray menu is the only consumer, and it needs this because a page label
 * only exists in the renderer's i18n bundles: reporting the pages already
 * translated is what keeps six protocols' navigation out of the Go process.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ReportSession records the tab in front, the page it shows, and the pages
 * that tab's protocol offers, in sidebar order. An empty active tab means the
 * shell is showing something that sits beside the tabs.
 */
export function ReportSession(active: string, page: string, pages: $models.ShellPage[]): $CancellablePromise<void> {
    return $Call.ByID(1200836905, active, page, pages);
}
