// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TopicService exposes destination operations to the frontend.
 * 
 * It still speaks model.TopicItem. Converting back from the canonical shape
 * here keeps the renderer untouched through the backend refactor; the
 * conversion goes away when the frontend moves onto model.Destination.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create adds a topic on the target broker.
 */
export function Create(connID: number, input: $models.TopicInput): $CancellablePromise<void> {
    return $Call.ByID(2768344908, connID, input);
}

/**
 * Detail returns a single topic with its routes and metrics.
 */
export function Detail(connID: number, topicName: string): $CancellablePromise<model$0.TopicItem | null> {
    return $Call.ByID(4032733801, connID, topicName).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * List returns the user-visible topics.
 */
export function List(connID: number): $CancellablePromise<(model$0.TopicItem | null)[]> {
    return $Call.ByID(2639464304, connID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListAll returns every topic, including system topics.
 */
export function ListAll(connID: number): $CancellablePromise<(model$0.TopicItem | null)[]> {
    return $Call.ByID(3586990883, connID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Remove deletes a topic from the cluster.
 */
export function Remove(connID: number, topicName: string, clusterName: string): $CancellablePromise<void> {
    return $Call.ByID(4094727824, connID, topicName, clusterName);
}

/**
 * Stats returns the per-queue statistics for a topic.
 */
export function Stats(connID: number, topicName: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1748281291, connID, topicName).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Update changes the configuration of an existing topic.
 */
export function Update(connID: number, input: $models.TopicInput): $CancellablePromise<void> {
    return $Call.ByID(3319221225, connID, input);
}

// Private type creation functions
const $$createType0 = model$0.TopicItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
