// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes the update lifecycle to the renderer.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";

/**
 * Cancel stops a download in flight.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(3623391884);
}

/**
 * Check asks GitHub now, whatever the policy says. Pressing the button is the
 * one case that reports every outcome, including "you are up to date".
 */
export function Check(): $CancellablePromise<update$0.State> {
    return $Call.ByID(1580339606).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Download fetches and verifies the package for the newest release.
 */
export function Download(): $CancellablePromise<void> {
    return $Call.ByID(4044417950);
}

/**
 * Install applies the downloaded package and quits, having arranged for the
 * application to start again once this process is gone.
 */
export function Install(): $CancellablePromise<void> {
    return $Call.ByID(488237709);
}

/**
 * Skip stops a release from being announced again.
 */
export function Skip(version: string): $CancellablePromise<void> {
    return $Call.ByID(3891298541, version);
}

/**
 * State returns everything the update panel draws.
 */
export function State(): $CancellablePromise<update$0.State> {
    return $Call.ByID(3806053547).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = update$0.State.createFrom;
