// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService keeps the native window chrome in step with the renderer theme.
 * 
 * Everything else about the window - minimise, maximise, close - is driven from
 * the frontend through the Wails window runtime and needs no binding here.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * SetAppearance applies the light or dark window background colour.
 */
export function SetAppearance(dark: boolean): $CancellablePromise<void> {
    return $Call.ByID(2170341447, dark);
}

/**
 * SetTitleBarHeight re-centres the macOS window buttons in a title bar the
 * renderer has scaled. The buttons are native and keep their own size, so only
 * the bar's height changes with the UI scale. No-op off macOS.
 */
export function SetTitleBarHeight(height: number): $CancellablePromise<void> {
    return $Call.ByID(160893141, height);
}
